- src/static/js/AttributeManager.js
return safely if the attribute wasn't found.
fixes #2394
> Finally fix AttribManager#removeAttributeOnLine

- src/node/eejs/index.js
- src/package.json
> Support ejs 2.0

- src/node/handler/PadMessageHandler.js
CLIENT_READY)
fix for https://github.com/ether/etherpad-lite/issues/2454
> Stop processing a message without auth (i.e. a client did not send

- doc/api/hooks_server-side.md
- src/node/utils/ExportHtml.js
Fix for https://github.com/ether/etherpad-lite/issues/2486
> Better HTML Export rewrite hook allows functions to be passed instead of strings means state is saved between plugins

- doc/api/hooks_client-side.md
- src/static/js/contentcollector.js
Ready for testing.  Adds a hook that can be used to collect image contents on paste.
> clean support for image hook

- README.md
git-core package is an obsolete transitional package, it was renamed git.
> Change git-core to git

- doc/api/http_api.md
The doc says current version is 1.2.9, but there is getPadID which uses version 1.2.10.
> Set correct API version in doc

- src/node/easysync_tests.js
- src/node/utils/padDiff.js
- src/static/js/Changeset.js
This is similar to https://github.com/ether/etherpad-lite/pull/2405 
It adds the same sanity checks for + and - ops - just as the aforementioned pull request did for = op.
It prevents epl from accepting changesets that lie about newline counts. If such a cs is accepted it can result in disconnecting all clients and a crash of the whole epl instance can be triggered later on. ("lineassembler not finished")
Note that it does not prevent epl from crashing in case such a changeset was accepted in the past, but at least it prints the bad changeset now. You have to manually remove it from the database and repair/reimport - although this can be non-trivial because you may not precisely understand what the changeset was meant to do.
frontend&backend&easysync tests pass
Note also, that I actually …
> Deny changesets if newline count is wrong

- doc/api/http_api.md
- src/node/db/API.js
- src/node/db/Pad.js
- src/node/handler/APIHandler.js
- tests/backend/specs/api/pad.js
Add two functions to API :
* getSavedRevisionsCount
* listSavedRevisions
> Fixes #1870

- src/static/js/ace2_inner.js
> Trigger renumbering when deleting (via cut) the first item of a list

- src/node/handler/PadMessageHandler.js
- tests/frontend/specs/clear_authorship_colors.js
Users can submit changes as another author. Clients/new users think someone else did the change. Another possibility is that an author which never exists in globalAuthor is introduced to the pad's pool.
As of now I only know of one exception to the rule "only accept changes of the client's authorId' namely clearAuthorship which uses an empty author (like epl itself does, when it introduces newlines to the end of the document).
> Check author attribution and fix clearAuthorship test

- README.md
Out of the box, etherpad-lite does not work correctly if cloned/installed into a subdirectory within an existing project. To do so, a few minor tweaks to the installation process are necessary which are documented here.
> Add subdirectory installation instructions

- README.md
- bin/buildForWindows.sh
- bin/installDeps.sh
- bin/installOnWindows.bat
- src/node/db/SessionStore.js
- src/node/handler/ExportHandler.js
- src/node/handler/ImportHandler.js
- src/node/hooks/express.js
- src/node/hooks/express/errorhandling.js
- src/node/hooks/express/padreadonly.js
- src/node/hooks/express/padurlsanitize.js
- src/node/hooks/express/socketio.js
- src/node/hooks/express/specialpages.js
- src/node/hooks/express/static.js
- src/node/hooks/express/tests.js
- src/node/hooks/express/webaccess.js
- src/node/hooks/i18n.js
- src/node/padaccess.js
- src/node/utils/Minify.js
- src/package.json
Updated for express 4 support. Dropped connect dependency.
Note: express 4.x dropped support for node v0.8.
Known issues:
* caching middleware or minify middleware seems to be junking binary files (fonts).
Please review and let me know if you see any issues.
Fix for issue #1738
> Express 4 support

- src/node/hooks/express/static.js
This should correct the issue of fonts and images being corrupted, introduced in the express4 change.
> fix: only match /javascript/* for caching middleware

- src/node/handler/ImportHandler.js
- src/node/utils/ImportEtherpad.js
Made setPadRaw async. The async library expects functions to be asynchronous, but they aren't if you just call the callback immediately, and this can lead to blowing the stack. Wrapped callbacks in `setImmediate` to fix.
Also, file import handling streamlined a bit.
This will probably need some testing to make sure I didn't break the whole thing.
#2524
> fix large etherpad import, fixes #2524 

- src/node/utils/Minify.js
`filename = filename.replace(/\\/g, '/')` is now preceded by stripping out `..`, which should fix both problems.
fixes #2614
> revert to old path handling, but strip out "..". fixes #2614

- settings.json.template
- src/node/hooks/express.js
When running etherpad-lite with ssl through Node/expressjs, you would typically like to be able to provide intermediate certificates as part of the SSL handshake. This is supported by expressjs, but some extra config was needed.
> Adding support for providing intermediate CA certificates 

- src/static/js/timeslider.js
Names of the pads can contain more charaters than \w. So while
transforming the export links, we simply can allow all charaters
except the slash as pad names.
> timeslider: Fix export links

- src/node/db/Pad.js
- src/node/utils/ImportHtml.js
- src/static/js/Changeset.js
- tests/backend/specs/api/pad.js
Fix setText() to replace the full pad text rather than replacing all except the last letter.  Previously, e.g., calling setText() with a pad's existing contents would make the pad one character longer.
> When using setText(), replace the entire existing text of the pad.

- src/static/js/ace2_inner.js
In two lines of ace2_inner.js, the innerText property is used only for MSIE:
* https://github.com/ether/etherpad-lite/blob/develop/src/static/js/ace2_inner.js#L3230
* https://github.com/ether/etherpad-lite/blob/develop/src/static/js/ace2_inner.js#L3247
In a third line, innerText is used for any browser that implements innerText. That includes Chrome. 
* https://github.com/ether/etherpad-lite/blob/develop/src/static/js/ace2_inner.js#L1985
That fact causes a bug in a plug-in we#re developing. We worked around that bug, but liked to have a solution in etherpad.
Description of bug at https://github.com/tm-linkwerk/ep_linebreak/blob/WR-72-linebreak-cursorverhalten/static/hooks.js#L94
> Bugfix innerText

- src/node/hooks/express/webaccess.js
- src/node/padaccess.js
When running etherpad with:
- settings.requireSession = true;
- settings.sessionKey = "some value";
the PDF export will *always* return 403 because the cookies never get parsed and the access check in `src/node/padaccess` boils down to:
```javascript
req.cookies = {};
checkAccess(.., req.cookies.sessionID, ...);
```
> Use the cookie parser middleware

- doc/api/hooks_client-side.md
On documentation of `collectContentPre`, the explanation about how to set a value to an attribute was incorrect (it said you need to use `"attributeName:value"`, but it is actually `"attributeName::value"`).
> Fixing documentation of collectContentPre

- settings.json.template
- src/node/handler/ExportHandler.js
- src/node/utils/Settings.js
- src/node/utils/TidyHtml.js
- tests/backend/specs/api/tidy.js
We're running into quite a bit of issues in our production environment where users generate quite big documents (think lots of nested lists) and can't export them to PDF due to abiword not being able to handle the exported HTML.
This PR cleans up the HTML before handing it off to abiword which seems to help quite a bit
> Tidy HTML before trying to convert it with abiword

- src/static/js/html10n.js
Currently only `title`, `innerHTML`, `alt`, and `textContent` can be localizable using html10n.js. But if you have a form with submit button, as the [ep_comments_page plugin] (https://github.com/JohnMcLear/ep_comments) has (check the comment when user suggested a change 
), the button won't be localizable.
I've added `value` as an attribute that is allowed to be localized, ran the backend and frontend tests, everything working fine.
> Allowing 'value' to be a localizable attribute on HTML elements.

- bin/convert.js
The used mysql client API was outdated. This change uses the current API and was successfully tested on a database containing ~2500 pads.
> Conver.js: Use current mysql client API

- src/static/js/pad.js
After successfully importing a document, the loading circle didn't hide itself.
This can happen, if you try to access a variable, which was not declared before. Even if you soft-check it against null, when it was not declared before JS throws a ReferenceError (and doesn't return undefined).
> On Import, when successful, loading circle didn't go away

- src/node/handler/PadMessageHandler.js
- src/static/js/ace2_inner.js
Currently, if a pad ends with fewer than two newlines, Etherpad will add newlines.  Ending with a single newline should be sufficient, and avoids unnecessary diffs when integrating with other systems.
> Allow a pad to end with only a single newline.

- doc/api/hooks_server-side.md
- src/node/db/Pad.js
This gives the hooks access to information that's otherwise awkward to get.
Ran backend tests and they pass.
> Add author information to the context for padCreate and padUpdate hooks.

- bin/run.sh
$rocks has to be enclosed into a "string" so bash can treat is as a string.
We can compare two strings with the == operator then, ...
> run.sh [: too many arguments

- src/static/css/pad.css
When plugins use font icons from `fontawesome-etherpad` and `minify` is on, the icons cannot be displayed because the URL seems to be incorrect: it looks for the font at `http://localhost:9001/font/fontawesome-etherpad.*`, but the correct path is `http://localhost:9001/static/font/fontawesome-etherpad.*`.
To reproduce this, use `ep_comments_page` and check for the delete icon on the comment.
Should be:
But is:
This is the same change of 56ce8e8, but for `fontawesome-etherpad`, instead of `opendyslexic`.
> Fixing @font-face src path to be able to use font icons on plugins when minify is on

- src/node/handler/PadMessageHandler.js
Address issue 2674 by checking that the session is valid and has a valid
author and padId before using it to update the userInfo for that
session. Otherwise it is possible that by the time we try to update a
session with new userInfo that session has disconnected and is no longer
available to be updated. Without this commit the etherpad-lite service
gracefully shutsdown whenever this happens.
> Check for valid session in handleUserInfoUpdate

- src/node/db/Pad.js
- tests/backend/specs/api/pad.js
Also adds a test for the ending-in-'\n' case and update tests for the other case.
This is a followup to my previous pull request #2649 intended to fix issue #2700.
> Restore newline-adding to setText() if passed string does not end in '\n'.

- src/static/css/pad.css
On mobile devices (or at least on some iOS ones), if user scrolls the toolbar is not displayed anymore, and chat does not stick to the bottom of the page:
Tested on a Safari on Simulator + on Chrome on iPhone 5S with iOS 8.3.
With this PR:
> Fix toolbar and chat positioning on mobile devices

- src/static/css/pad.css
- src/static/js/pad_editbar.js
I've noticed my previous fix on #2718 was woking on my Etherpad because I have ep_page_view installed. When this plugin is not present, the editbar is still not fixed on top of the page when using iOS devices. So one of the commits of this PR is to fix that.
The other commit is to address an issue when pad is read-only and no button is on editbar, which I've noticed while testing the first commit:
This time I've tested on an Etherpad with no plugins, on these 4 scenarios: regular pad, read-only pad, inside of an iframe (using https://github.com/ether/etherpad-lite-jquery-plugin), and on timeslider. I've also tested on Safari@iPhone, Chrome@iPad, Chrome@desktop, and FF@desktop.
I hope this is all we need this time.
> Complementing #2718 + Fixing empty toolbar when on read-only & menu_left has no button

- src/static/css/pad.css
tl;dr
- avoid focus to be moved to the top every second when on iOS;
- but move back the issue that shows toolbar in the middle of the screen when editing on iOS:
Long story:
This PR reverts part of #2721, because that change made scroll on iOS devices very unstable. Using `position:scroll` as it was before this PR made the editor scroll to the top every second or so, even without any action from the user. I'm not sure if this issue is related to #2224, so maybe fixing one might fix both.
Anyway, I thought it was much worse to keep moving the focus to the top of the editor than having a toolbar "flying" on the screen when editing the pad.
Thoughts about these issues? Any suggestion?
> Removing style that makes editor scroll to the top on iOS without any action from the user

- src/static/js/AttributeManager.js
- src/static/js/ace2_inner.js
#2772 happened because attributes were being applied to the whole line, including the line markers, when selected range wrapped multiple lines.
To fix it, we changed the way `AtributeManager.setAttributesOnRange()` applies attributes to a multi-line selection: instead of applying it the whole selection at once, we apply line by line, skipping the line markers on the range.
This might generate multiple changesets that are not continuous, so in the end we compose them into a single one. By doing this, we don't affect the behaviour of undo operations.
> Fix 2772. Skipping line marker when applying attribs to a range

- doc/api/hooks_server-side.md
- src/node/handler/PadMessageHandler.js
I'm developing a plugin to send stats over from Etherpad to Graphite. I've added a new hook that I will use for the plugin, called from within the handleClientReady() function within PadMessageHandler.js. This seemed to be a good place to account for whenever a user enters a pad, and it also contains some information that I need---namely message.padId.
Let me know if you have any issue with this addition.
> added clientReady hook

- doc/api/hooks_server-side.md
- src/node/utils/ExportHtml.js
To handle attributes stored as `['key', 'value']` (and not only `['key', 'true']`). This is useful for plugins that use the former way of storing attributes on the AttributePool.
Tags provided as arrays will be exported to HTML as `<key:value>` (we could use any other string, I've used `":"` just to follow the standards I saw on some of the plugins, like ep_font_color and ep_comments).
> Accepting Arrays on 'exportHtmlAdditionalTags'

- src/node/db/API.js
- src/node/db/Pad.js
- src/node/handler/APIHandler.js
- tests/backend/specs/api/pad.js
I wanted to write a script that could stream text into an Etherpad, and the getText/setText APIs don't work well for this purpose, because setText clobbers attributes, so if anyone else is trying to edit the pad at the same time it results in errors. I added an appendText method which does exactly what I need.
> Add an appendText API

- settings.json.template
- src/node/handler/ExportHandler.js
- src/node/utils/ExportHtml.js
- src/node/utils/LibreOffice.js
- src/node/utils/Settings.js
This commit adds support for LibreOffice when exporting a pad to doc, pdf, ..
It also cleans up some export logic when exporting to txt.
This is similar as what https://github.com/ether/etherpad-lite/pull/2783/files#diff-d7655657171b783c2bc082522988848e is achieving but it's more complete as it still supports PDF.
> Allow LibreOffice to be used when exporting a pad

- settings.json.template
- src/node/handler/PadMessageHandler.js
- src/node/utils/Settings.js
- src/static/js/ace2_inner.js
- tests/frontend/specs/indentation.js
Currently pressing ENTER on a line that ends with ':', '[', '(' or '{'
automatically indents the new line with 4 spaces. The variable added by
this commit to settings.json allow an Etherpad instance to not have this
behavior.
Also added some tests for the default behavior.
Note: I've used `clientVars` to share the setting with `ace2_inner.js`, but I'm not sure if this is the best approach. Do you guys have any other suggestion?
> Create setting to control if a new line will be indented or not

- src/node/utils/Settings.js
* Used by https://github.com/debops/ansible-etherpad
> Get git commit hash even if the repo only points to a bare repo.

- src/static/js/admin/plugins.js
- src/static/js/admin/settings.js
this should allow the admin pages to run fully (socket.io was going to root) in a subdirectory or behind a reverse proxy and
> allow /admin to run in a subdirectory

- src/static/js/contentcollector.js
Since bf380eea504662ea41aa431e30d7e30ad6a36cd3, some spaces were removed when pasting text from a word processor (at least using Libre Office). To avoid double space creations and space removal, we only remove line break which are tight to a space character.
> Avoid space removal when pasting text from word processor.

- doc/api/hooks_client-side.md
- src/static/js/ace2_inner.js
No current hook seems to address this use case; you can fake key-related movement with aceKeyEvent, but there doesn't seem to be a way to catch mouse-related cursor changes.
> Add a aceSelectionChanged hook to allow plugins to react when the cursor moves

- src/static/js/ace2_inner.js
PR #984 fixed an issue with "esc" on older versions of Firefox (15-19), but avoided the key event to be sent to plugins on aceKeyEvent.
This issue was fixed in Firefox versions 20 and above. 
With this commit we keep the fix for the older Firefox versions, besides to allow to handle "ESC" by plugins.
More details about this issue :
http://blog.ffextensionguru.com/2013/01/11/changes-to-esc-key-behavior/
This was tested in Firefox 15, 20, 41 for Linux.
> Allow plugins handle "esc" key event

- src/static/js/ace2_inner.js
Instead of checking if only the first hook had returned true, we check
all hooks.
> Fix logic to check if any hook handled ACE key event. Fix #2818

- src/node/db/AuthorManager.js
Removed the hard-coded number for the colorId for a new author
> Fix for #2809

- doc/api/hooks_server-side.md
- src/node/utils/ExportHtml.js
The new hook does the same as exportHtmlAdditionalTags, but is declared
in another hook to avoid confusion about how to export tags when they
are stored as ['tag', 'value'] on attribute pool.
This complements #2762, as per @Gared suggestions.
> Create hook exportHtmlAdditionalTagsWithData

- src/static/js/ace2_inner.js
- src/static/js/browser.js
- src/templates/pad.html
- src/templates/timeslider.html
With this new version of bowser.js is possible detect the OS as well,
no only the browser as the previous one. It brings support to
new browsers as well.
Tested in 
Mac (10.8.5): Firefox (39.0), Chrome (46.0.2490.86), Safari (6.2.8)
Linux Fedora 22:  Chrome (46.0.2490.86), Firefox 42.
Windows 7: Internet Explorer 11
> Update the bowser.js to the new version

- doc/api/hooks_client-side.md
- src/static/js/ace.js
``aceEditorCSS`` hook to allow absolute paths to resources to include external CSS. 
Initially developed for https://github.com/tiblu/ep_themes_ext
This patch was the only way I could think of to make loading of externals stylesheets work without style flicker.
> aceEditorCSS hook to allow absolute paths to resources to include external CSS

- src/templates/index.html
It seems good to limit the padname length in the input field. As I could check, the max length accepted is 50 characters.
If this config depends on other server/installation configs, please let me know.
> Limit padname input field to 50 characters

- settings.json.template
See https://github.com/ether/etherpad-lite/issues/2516#issuecomment-164768811
Maybe we should output a warning on console if this parameter isn't set?!
This pull request is related to my change for ueberDB:
https://github.com/Pita/ueberDB/pull/87
> set charset for mysql connection in settings.json

- bin/run.sh
At the end of run, `exec` should be used to switch to the node process.  That way node will take over the pid of `sh run.sh`, making it easier to monitor and daemonize the server. 
```
exec [command [arg ...]]
Unless command is omitted, the shell process is replaced with the
specified program (which must be a real program, not a shell
built-in command or function).  Any redirections on the exec com-
mand are marked as permanent, so that they are not undone when
the exec command finishes.
```
> Use exec to switch to node process

- src/static/js/AttributeManager.js
This avoids raising error 'Trying to submit changes as another author in
changeset' when 2 authors change line attributes of the same line. This
fixes issue #2925.
> Update author when removing line attribute from line

- src/static/js/domline.js
- src/static/js/linestylefilter.js
- src/static/js/pad_utils.js
The URI schemes `about`, `geo` and `tel` are widespread, so they should be linked in the text area.
It is possibly a bad idea to make every occurence of ":" a link, but for some well-known URI schemes, this can be done with a whitelist.
> Highlight and link more URI schemes: about, geo, tel

- doc/api/editorInfo.md
- src/static/js/AttributeManager.js
- src/static/js/ace2_inner.js
Ready to test and hopefully merge
> extend attributesonselection method

- doc/api/hooks_client-side.md
- src/static/js/ace2_inner.js
One of the plugins I use triggers edit events under the hood that might change the text of the pad. This makes the scroll position to change at the end of the event, but I need to prevent this behavior. (Just to give a more concrete example, the plugin paginates the pad -- in batches, to avoid freezing the editor when changing long pads)
One possible solution was to add a new flag to callstack and check for it when going to call `scrollSelectionIntoView`, but I thought that would be too intrusive, so instead I've created a new hook where plugins can register edit events that won't scroll the viewport when event is complete.
Thoughts? Concerns?
> Create hook to register events that won't scroll editor after aceEditEvt

- src/static/js/linestylefilter.js
- tests/frontend/specs/urls_become_clickable.js
These characters are rarely used in URLs, and including them leads to
mislinkifying when editing various formats, such as wiki markup formats that
use [] around links.
> Remove [ and ] from the regexp used by the URL filter.

- tests/frontend/helper.js
- tests/frontend/specs/helper.js
- tests/frontend/specs/indentation.js
Some frontend tests need to have multiple lines selected, but `sendkeys` does not provide this feature -- and I assume it would be hard to implement it there because we would need something general as `"{downarrow}"` / `"{uparrow}"`, which would need extensive calculations about line lengths, etc.
So I've extended `helper` to have a method to select more than one line, with (optional) different offsets on start and end line. As an example, I've added a test for #2772, which fails if we run Etherpad with code before #2777...
... and passes if we run code after it:
> Enable multi-line selection on frontend tests

- src/static/js/ace2_inner.js
Without this change, a top margin on any element on the first line of pad
content would throw off the alignment of line numbers. The default stylesheet
doesn't define any elements with top margins, but plugins might. (This is also
explained in a code comment.)
In order to see the problem, add the following clause to `iframe_editor.css`
(before incorporating this commit):
#innerdocbody > :first-child {
margin-top: 100px;
}
> Account for any top margin on the first line.

- src/node/handler/ExportHandler.js
- src/node/hooks/express/padreadonly.js
- src/node/utils/ExportHtml.js
- src/node/utils/ExportTxt.js
- src/templates/export_html.html
The semantics of all the substitutions are identical to what they were before. I _did_ take the liberty of formatting the CSS to be a bit more readable (at the cost of adding a little bit of whitespace).
**Note:** I did _not_ fix the pre-existing misspellings in the CSS, e.g. `eigth`, `twelth`, and `sixthteenth`. Other than whitespace, I left the export document contents alone.
I checked both front-end and back-end tests, and they all seem to be okay when run on my local machine. (Two of the back-end tests come back as "pending." I assume that's okay because that's how they also report when I run on a clean checkout of the `develop` branch.)
> Use an EEJS template for HTML export instead of inlining it in the JS code.

- src/node/hooks/express/specialpages.js
- src/templates/admin/index.html
- src/templates/admin/plugins-info.html
- src/templates/admin/plugins.html
- src/templates/admin/settings.html
- src/templates/export_html.html
- src/templates/index.html
- src/templates/javascript.html
- src/templates/pad.html
- src/templates/timeslider.html
The source code should now be 100% LibreJS compliant via the web labels method (the least invasive, no modification to any of the JavaScript files required).
I could only test the homepage because LibreJS breaks when the callback is passed, but that's not Etherpad's fault and it's something they should look into.
Closes #2913, all changes released under the same license as etherpad-lite (Apache 2.0)
> Added LibreJS support

- doc/api/editbar.md
- src/static/js/pad_editbar.js
Passing through the item parameter makes it easier to have one registerAceCommand callback that handles multiple toolbar items in a plugin and makes the interface more similar between registerCommand() and registerAceCommand().
> Pass through the "item" parameter to registerAceCommand callbacks.

- README.md
Hi there,
`curl` was missing as a dependency on FreeBSD. I adjusted the readme.
Cheers,
tpltnt
> readme: added curl as dependency

- doc/api/hooks_server-side.md
`expressCreateServer` and `expressConfigure` are called from [`express.js`](/ether/etherpad-lite/blob/develop/src/node/hooks/express.js#L83-L84), not
from `server.js`.
> Update called from for two hooks

- src/node/hooks/express/webaccess.js
The session key is currently stored in SESSIONKEY.txt, so it is no longer reset
every time the server starts.
> Remove deprecated comment

- .travis.yml
- src/static/js/ace2_inner.js
Besides fixing #3118, this PR also includes the plugin [ep_test_line_attrib](https://github.com/storytouch/ep_test_line_attrib) when running tests on Travis. This was necessary because there was no way to run tests with the current Etherpad structure, due to the fact that there are no line attribs defined by Etherpad besides the one with lists -- and code was already working properly with lists, but was failing for other line attribs.
This plugin will also allow other tests for plugin-related features in the future.
Does anyone have any concerns about adding this plugin to the test?
> Create plugin to run tests for line attribs + fix #3118

- bin/doc/README.md
The generate.js is in the `/bin/doc/` directory.
And the origin cmd will cause error.
> wrong path of generate.js

- README.md
This change prevents mixed-content warnings on pages displaying the readme via HTTPS.
> Use HTTPS for images in README.md

- settings.json.template
- src/node/hooks/express/specialpages.js
- src/node/utils/Settings.js
- src/static/js/ace2_inner.js
Adds the pad shortcut disabling feature to the settings.json . The available shortcuts to enable/disable are whatever is available right now and checked in the pad by custom code (not all shortcuts). This deals with Issue #2884 until a UI can be developed to enable/disable shortcut keys.
> Added pad shortcut disabling feature to settings.json

- settings.json.template
- src/node/handler/PadMessageHandler.js
- src/node/hooks/express/specialpages.js
- src/node/utils/Settings.js
- src/static/js/ace2_inner.js
- tests/frontend/specs/ordered_list.js
Some minor fixes to #2891 + do not use cookie to store which shortcuts are enabled or not. As users still cannot choose their preferences, it does not make sense (yet) to have a cookie with shortcuts preferences.
> Adjustments of #2891

- doc/api/hooks_server-side.md
- src/node/db/Pad.js
Let plugins know when a pad is copied.
> [feat] New server-side hook: padCopy

- src/static/js/ace2_inner.js
- src/static/js/pad.js
- src/static/js/pad_editbar.js
- tests/frontend/specs/automatic_reconnect.js
- tests/frontend/specs/pad_modal.js
- disable pad edition when user is disconnected (but not when still trying to reconnect);
- do not hide error modal when user is disconnected;
- close non-error modals (like settings, for example) when user clicks on pad outer (and not only on pad inner)
> Improvements on modals and "force reconnect" messages

- src/node/utils/Cli.js
As I was working on containerizing this for use in OpenShift, I realized that overriding the location of the credentials.json file didn't work properly. There is code to override the value in [Settings.js](https://github.com/ether/etherpad-lite/blob/develop/src/node/utils/Settings.js#L318), but it looks like Cli.js never actually pulls the value for credentials out of the argument list. Adding support for that here.
> Add credentials arg to CLI module

- src/static/js/pad.js
- src/static/js/pad_cookie.js
PR to fix https://github.com/ether/etherpad-lite/issues/3179
> #3179 - Using EP on same domain, but over different protocols causes "Warning: it appears that your browser does not have cookies enabled.

- src/package.json
That in turn upgrades engine.io to 1.8.2. This fixes a crash for me when running behind a traefik reverse proxy.
The error is as described here: https://github.com/socketio/socket.io/issues/2779
> Update socket.io to 1.7.3

- src/node/hooks/express/errorhandling.js
Shut down database connection and exit the node process
when SIGTERM is encountered. This is especially important
when nodejs is run as PID1, e.g. in a docker container.
Shutting down connections to clients (browsers) is beyond
this patche's scope.
Resolves #3265
> Catch SIGTERM for graceful shutdown

- settings.json.template
- src/node/handler/PadMessageHandler.js
- src/node/utils/Settings.js
- src/static/js/ace2_inner.js
- src/static/js/caretPosition.js
- src/static/js/scroll.js
- tests/frontend/specs/scroll.js
By default, when there is an edition of a line, which is out of the
viewport, Etherpad scrolls the minimum necessary to make this line
visible. This makes that the line stays either on the top or the bottom
of the viewport. With this PR, we add a setting to make possible to
scroll to a position x% pixels from the viewport. Besides of that, we
add a setting to make an animation of this scroll and allow to scroll if the 
caret is at the last line of the viewport. Both of them are optional.
If nothing is changed on settings.json the Etherpad default behavior is
kept.
_Etherpad Default_
_Google Docs_
_Microsoft Word_
This PR has been used/tested for one year or so in production. 
We've tested this PR on differents browsers versions, some of them
ps: When there is a selection and user either …
> Add settings to scroll on edition out of viewport 

- src/node/db/Pad.js
> [fix] Don't show "pad deleted" message when copying pad

- src/node/utils/LibreOffice.js
When using LibreOffice to convert pads to doc, we got `Error: no export filter for /tmp/xxxx.doc` (tested with LO 5 and 6). Maybe it's a regression from LO. Anyway, converting HTML to odt, then to doc works.
> Fix .doc export with LibreOffice (soffice)

- bin/cleanRun.sh
Now works if the output of `pwd` has a space in it.
> Fix bug with cleanRun.sh

- src/static/js/ace2_inner.js
Line numbering display was broken when using page view since https://github.com/ether/etherpad-lite/commit/a3765d97853ecfe3fa608cd3b191a33cabe311ec.
The first number took the line height plus 100px, due to ep_page_view padding-top CSS rule.
This fixes the problem.
> Fix line number display when plugin add padding-top (like ep_page_view)

- bin/dirty-db-cleaner.py
This would fail e.g. on Archlinux otherwise
> specify python version in shebang

- src/node/handler/ImportHandler.js
Etherpad process .rtf files as txt files. It just reads all the ascii text from the file and displays it on the pad. This results in printing all the junk that's inside .rtf along with the actual text.
[ScreenshotBefore](http://imgur.com/a/lpFEV)
[ScreenshotAfter](http://imgur.com/a/NcQ2T)
Use abiword to process .rtf files
Issue link #3235
> Feature: Support for uploading .rtf files rich text format

- src/static/css/iframe_editor.css
Looks like the WA done in #1766 is now affecting to the newest Safari and epiphany browser versions and is not longer required for the latest version of Chrome. I just reverted this one and the copy&paste works well now in Epiphany:
See discussion here (https://github.com/ether/etherpad-lite/issues/2742) and  here (https://github.com/ether/etherpad-lite/issues/2078)
> WA added  in #1766 is not longer needed

- src/static/js/pluginfw/plugins.js
running ./bin/run.sh after the 1st time caused the following error "TypeError: Cannot read property 'dependencies' of undefined".
fixed it.
> fixed plugin dependency issue

- src/node/handler/APIHandler.js
- src/node/utils/Cli.js
- src/node/utils/Settings.js
Running multiple instances sometimes requires different api- and session-keys for security reasons.
> Make APIKEY and SESSIONKEY file customizable

- doc/api/hooks_server-side.md
- src/node/db/SecurityManager.js
This hook allows plugins to control access to pad. It gives an alternative way to grant/deny access. I've used it to create a simple solution that only requires password to create a new pad, not to access already created one.
> Feature: New server-side hook: onAccessCheck

- src/node/hooks/express/webaccess.js
This allows authenticators to do any extra session setup for a given user,
even if their username/password happens to match settings.json.
> Call authentication hooks before default basic authentication.

- src/static/js/pad.js
I have etherpad installed in a subdirectory
> made url relative

- src/locales/fr.json
FYI, the dateformat in translatewiki is correct.
> Fix FR dateformat

- src/static/js/ace2_inner.js
This related with issue #3383.
Firefox will not fire the keypress when target key is the non-printable keys. (like Enter / Tab / Delete... etc) For detail, see https://bugzilla.mozilla.org/show_bug.cgi?id=1440189.
This behavior is same as safari / chrome, So etherpad-lite will not need to special handling of these key when UA is Firefox. This PR will use keydown event when target key is no-printable keys.
> Use keydown instead of keypress on Firefox.

- tests/frontend/travis/remote_runner.js
Fix warning when running tests: "chain api has been deprecated, use promise chain instead." 
This fixes the Travis tests -- broken since #6d5dc93
> [fix:test] Use promise chain instead of chain (is deprecated)

- src/static/js/AttributeManager.js
- src/static/js/ace2_inner.js
- tests/frontend/specs/authorship_of_editions.js
When comparing original content with the changes made by the user, we need to ignore some line attribs that are added by content collector, otherwise we would consider the change started on the first char of the line -- the '*' that is added when line has line attribs.
In order to be able to handle both #3354 and #3118, we need to take into account both the styles attribs (to fix #3354) and the line attribs defined by any of the plugins (to fix #3118), but we can ignore those extra line attribs that are added by Etherpad and do not add any functionality (`'lmkr', 'insertorder', 'start'`).
Fix #3354 .
> [fix] Ignore default line attribs when detecting edges of changeset

- README.md
- src/node/utils/Cli.js
This pull requests adds some basic documentation for --credentials, --apikey and --sessionkey.
It removes the -k option, as it is currently used for both apikey and sessionkey.
> Document --credentials, --apikey and --sessionkey; remove -k (duplicate)

- src/node/hooks/express/static.js
- src/node/utils/Minify.js
The hostname:port of URIs used in Minify are currently bogus and refer to localhost only for historical reasons; there's no reason to retain them and omitting them avoids generating an invalid URI when "port" is not an integer.
For context: settings.port is passed to express's `listen`, which treats it as a filename for a Unix domain socket if it doesn't look like a port number. This is useful for starting a server to be reverse-proxied on a multi-user system without requiring fuss around port numbers or authentication.
Currently, etherpad-lite runs without error when configured to listen on a Unix domain socket; however, when a pad is accessed, the client JS fails with "Uncaught Error: The module at "ep_etherpad-lite/static/js/rjquery" does not exist." due to `pad.js` and …
> Fix misparse of port when binding Unix socket

- src/node/handler/APIHandler.js
- src/node/utils/AbsolutePaths.js
- src/node/utils/Settings.js
- src/package.json
Every relative path in Etherpad is resolved against the current working directory, or against `npm.dir`, which in turn depends on it.
Because of this, running the same Etherpad instance from different places litters the file system, and can lead to unpredictable results.
Affected files fixed by this PR are:
- `settings.json`
- `SESSION.txt`
- `APIKEY.txt`
- `dirty.db`
- `credentials.json`
This change aims to unify the behaviour: a relative path is always passed to `AbsolutePaths.makeAbsolute()`, that rewrites it to a common directory, eventually.
The strategy for determining this common directory is purely heuristic, because Unix install and the win32 package have a different layout on disk.
Fixes #3466 (and other similar issues).
> Resolve relative paths deterministically

- src/node/utils/LibreOffice.js
If you edit `src/templates/export_html.html` to remove the `<meta name="changedby" content="Etherpad">` tag[1], PDF export with soffice has a bug: the first word of the pad is deleted and a blank page is inserted as first page (the pad's text begins on the second page).
The `--writer` soffice option avoids that bug.
[1] you may want to delete that tag since it is inserted as a comment in .doc or .odt soffice export.
> Add --writer option to soffice convert command

- .travis.yml
should fix the current error
```
$ bin/installDeps.sh
Your npm version "2.15.1" is too old. npm 3.10.x or higher is required.
The command "bin/installDeps.sh" failed and exited with 1 during .
```
> travis-ci: updated nodejs version

- src/templates/index.html
URL encode entered pad names to allow special characters, which are currently causing some unexpected behaviour.
Some examples:
`test.html?q=abc` - currently creates a pad with the name `test.html`
`test.html/abc` - results in the error `Cannot GET /p/test.html/abc`
> url encode pad name

- tests/frontend/specs/authorship_of_editions.js
Original implementation of authorship test assumed a simple pad reload would switch the author -- and it actually did on Chrome. But other browsers might keep the author id on cookie.
To force the author switch, expire the cookie before reloading the pad.
Fixes: #3435
> tests: make sure author is switched on authorship test

- bin/dirty-db-cleaner.py
I noticed, that a dirtyDB can end up having invalid lines of JSON. Sadly this will also break this little clean'up tool. The patch just ignored invalid JSON.
> Try/catch to skip invalid JSON in dirtyDB

- src/templates/index.html
Etherpad-lite relies on the user's browser to generate a random pad
name, but the current solution is not safe against collisions. In order
to generate unique pad names, the following modifications are made:
* use a PRNG instead of Math.random() and ensure uniform distribution
when selecting chars.
* choose the pad name length to achieve a specific number of bits of
security.
Closes: #3516
> index.html: generate unique pad names

- bin/migrateDirtyDBtoRealDB.js
`bin/migrateDirtyDBtoRealDB.js`
---
(my) solution for #2214:
* the script ran out of memory -> added comment to give the script more memory in 4a41241
* ueberDB never write to the actual database -> disable write buffer in 055642e, write to the db directly
---
Since this is a maintenance script, there are no tests. I hope that's indented/alright.
> migrateDirtyDBtoRealDB: memory and buffer  #2214

- docker/README.md
- settings.json.template
- src/node/utils/Settings.js
This patch series prepares the `Settings.js` module, getting rid of duplicate code, and then implements support for configuring Etherpad via environment variables, as per proposal in #3543 (which, in turn, steals from [Elastic Search's configuration syntax](https://www.elastic.co/guide/en/elasticsearch/reference/6.5/settings.html#_environment_variable_substitution), albeit with a small difference).
All the configuration values can be read from environment variables using the syntax `"${ENV_VAR_NAME}"`.
This is useful, for example, when running in a Docker container.
```
"port":     "${PORT}"
"minify":   "${MINIFY}"
"skinName": "${SKIN_NAME}"
```
Would read the configuration values for those items from the environment
variables `PORT`, `MINIFY` and `SKIN_NAME`.
Please note that **a …
> support configuration via environment variables

- README.md
- docker/README.md
- settings.json.template
- src/node/utils/Settings.js
This patch series prepares the code for supporting using the `${ENV_VAR:default_value}` syntax in the configuration file, as specified in #3578.
The final commit implements the functionality.
| Configuration string in settings.json | Value of ENV_VAR | Resulting configuration value |
| ---- | ---- | ---- |
| `"${ENV_VAR}"` | `"some_string"` | `"some_string"` |
| `"${ENV_VAR}"` | `"9001"` | `9001` |
| `"${ENV_VAR}"` | `undefined` | `null` |
| `"${ENV_VAR:some_default}"` | `"some_string"` | `"some_string"` |
| `"${ENV_VAR:some_default}"` | `undefined` | `"some_default"` |
> Support for default values in envvars lookup

- src/node/db/API.js
- src/node/db/Pad.js
- src/node/handler/PadMessageHandler.js
- src/node/hooks/express/padreadonly.js
- src/node/utils/Minify.js
These are assorted fixes found while during an experimental conversion to Typescript.
The most notable fixes are:
- `PadMessageHandler.handleMessage()` got the wrong `padId` for read only pads. This would lead to a crash.
- a redundant `callback` parameter to `pad.remove()` in `Pad.prototype.copy()` could cause a crash at runtime.
- in case of error, `restoreRevision()` would crash instead of writing a log message
> Some fixes caught by the Typescript compiler

- docker/Dockerfile
- docker/README.md
While trying to build Etherpad for ARM , it fails due to devdeps , so I removed them from prod docker builds.
This also generates smaller builds. (mine is around 50Mb)
My docker images are at https://gitlab.com/alm-docker/etherpad/container_registry 
I enabled multiarch builds
> remove devdeps from prod builds

- src/static/css/pad.css
- src/static/js/pad.js
The current behaviour is to show the chat bubble and hide if chat is
disabled.
Because of this, the bubble appears wrongfully for a short time.
With this PR, by default it is hidden and displayed only if chat is
enabled.
Fixes: #3088
> Chat bubble: by default hide in CSS

- docker/Dockerfile
- docker/README.md
This PR implements #3618, introducing support for a new build argument, `ETHERPAD_PLUGINS`, which can contain a space-separated (and double quoted) list of plugins to be installed while building the container.
Example:
```bash
docker build --build-arg ETHERPAD_PLUGINS="ep_codepad ep_author_neat" --tag <YOUR_USERNAME>/etherpad .
```
> Support plugin installation when building docker image

- docker/Dockerfile
Setting the NODE_ENV to production does not change the run-time behaviour of etherpad-lite:
> [2019-08-07 10:29:49.914] [WARN] console - Etherpad is running in Development mode.  This mode is slower for users and less secure than production mode.  You should set the NODE_ENV environment variable to production by using: export NODE_ENV=production
Using the ENV command in the Dockerfile resolves this.
> NODE_ENV controls run-time behaviour, thus needs to be set by ENV

- src/node/utils/ExportHelper.js
Currently there is a bug in the HTML exporter.
Steps to reproduce:
- Create a new pad
- Add any character with a Unicode value above 0x10000, for example `👍`.
- Export the pad to HTML
The character will not be encoded correctly for HTML. It will be represented by two character references, which refer to surrogate code units. Therefore a browser cannot display the character correctly.
After applying this commit, the character is exported as just one character reference and gets displayed properly.
> Fix Unicode bug in HTML export

- docker/Dockerfile
downsized the docker image using buster slim and a removing the npm cache.  
see: https://hub.docker.com/r/foosinn/etherpad/tags
> smaller docker images

- .gitignore
- docker/Dockerfile
- docker/README.md
- docker/nop
- docker/settings.json
By leveraging the templating mechanism in `settings.json`, this change
allows a Docker client to run a prebuilt image and change some basic
configuration settings, like the instance name or, more importantly, the
database coordinates.
Also addresses https://github.com/ether/etherpad-lite/issues/3623
> docker: Enable env var settings by default

- docker/Dockerfile
Processes in containers should not run as root.
This change creates an unprivileged user in the Docker container, and
runs the main process using that user.
* with a volume attached
* with MySQL
A container built to run as non-root will not have access to volumes created with a container built to run as root.
Fixes https://github.com/ether/etherpad-lite/issues/3629
> docker: Run as unprivileged user

- docker/Dockerfile
The "conditional copy trick" was removed in #3644, but I failed to
update the corresponding comment.
> docker: Fix the comments about settings.json copy

- CHANGELOG.md
- src/node/hooks/express.js
- src/node/utils/ExportHtml.js
- src/static/js/domline.js
- src/static/js/pad_utils.js
Before this patch I managed to send a bunch of referrers to third party websites with Firefox. Unfortunately, meta name="referrer" isn't enough.
I added "noopener" because that's also what Nextcloud does. One may want to check another pull request from 2015 which may be more complete, but it was denied with a plugin proposal: #2498
References to earlier issues: #1603, #3043
> change referrer policy. Stop sending referers as much as possible

- Dockerfile
Before this change, the docker user had home in a directory it had no
permissions on. The inability of creating a cache directory in `$HOME`
prevented npm to work properly.
Additionally, the `node_modules` in the base working directory had its
owner set to root, preventing further changes.
With this change, the `etherpad` user has a home directory.
Additionally, `npm i` is now run by `etherpad` rather than the root
user; this way, it is possible to dynamically change the `node_modules`
content in day 2 operations.
Note that while switching to the `useradd` builtin, a conflict was
discovered with the GID 65534 that was previously used. This change is
changing the `etherpad` user's UID to 5001 to avoid said conflict. As a
consequence, a `chmod -R 5001:5001` must be run prior to attaching …
> docker: Set the home directory for the user

- .travis.yml
- src/package.json
- tests/backend/loadSettings.js
- tests/backend/specs/api/pad.js
- tests/container/loadSettings.js
- tests/container/specs/api/pad.js
- tests/frontend/travis/sauce_tunnel.sh
Add a `Test Dockerfile` job to Travis.
The new job:
* checks that `docker build` succeeds
* performs a few very basic calls against the app in the container
> Test the Dockerfile

- src/node/utils/toolbar.js
https://github.com/ether/etherpad-lite/issues/3707
Also reports the error to the server admin / plugin dev via console.warn.
I can't see any security considerations here but haven't done thorough testing.
> Fixes #3707

- src/static/js/contentcollector.js
- tests/frontend/specs/importexport.js
This pull request Fixes: #3620
> Issue 3620 fix

- src/node/handler/ImportHandler.js
`fs.rename()` is callback based, we need `fsp_rename()` which is declared above and is promised based, in order to catch the `unhandled promised rejection ...` warning
PS: I haven't tested this at all. I was looking at what kind of issues are open for this project and this one seems the obvious fix. Also, sorry if this PR is useless, feel free to close it, especially if it causes more work for integrating it than it helps.
> Fix allowUnknownFileEnds in 1.8.0 when importing files with unknown extension

- src/static/js/contentcollector.js
- tests/frontend/specs/importexport.js
This PR reverts #3622, which has caused bad issues with space & cursor behaviour (see issue #3728).
#3663 seems not related.
Please help testing it.
> Revert pr 3622

- src/node/utils/Minify.js
`if-modified-since` header does not include milliseconds, so https://github.com/ether/etherpad-lite/blob/develop/src/node/utils/Minify.js#L219 will always be `false`
> Fix minify cache ms

- .travis.yml
- tests/frontend/travis/remote_runner.js
- tests/frontend/travis/sauce_tunnel.sh
Suggest doing a squash when merging.
Intentionally commited to ether repo.
> Testing travis ci sauce labs - Ready for Review / Merge @muxator

- tests/frontend/travis/runner.sh
This change only slightly modifies the bahaviour of travis/runner.sh, but:
1. **speeds up the tests**, because it does not install dependencies before running them.
Dependencies are already installed by .travis.yml in its "install" section;
2. if for some reason Etherpad does not start, there is a sudden failure, instead of launching the front end tests anyway, and then **having to wait 10 minutes for them to time out**;
3. it is **compatible with a different way of installing Etherpad dependencies** ("npm ci" instead of "npm install"), whereas the previous one broke.
This will probably be introduced in a while, so this change future-proofs for it (see #3778).
4. it is **more robust**, because it detects more reliably the paths, and changes between them correctly;
Please note that the …
> tests: future proof travis/runner.sh and make it more robust

- src/node/utils/caching_middleware.js
This is a fix for #3502 where the cacheKey being a base64 encoding of the path can cause `ENAMETOOLONG` errors to be thrown.
> Switches cacheKey from base64 of path to sha256 of path; fixes #3502

- src/node/utils/caching_middleware.js
This is a follow up to #3794, which fixed #3502 using `sha256` to compute the cache keys.
According to the [nodejs docs](https://nodejs.org/docs/latest-v10.x/api/crypto.html#crypto_determining_if_crypto_support_is_unavailable) the `crypto` module might be unavailable on some platforms:
> It is possible for Node.js to be built without including support for the crypto module.
> In such cases, calling require('crypto') will result in an error being thrown
A description of such scenarios can be found [here](https://github.com/microsoft/TypeScript/issues/19100#issuecomment-335871998).
> * running non-standard node in a resource- or security-constrained environment
> * running in emulated environment (browserify, webpack etc.)
> * building node from source and omitting openssl/crypto for random …
> caching_midleware: also run when nodejs does not have crypto module

- src/node/utils/customError.js
This fixes a deprecation warning on node 10
> Rewrite the customError module with class syntax

- doc/docker.md
- settings.json.docker
- settings.json.template
- src/node/utils/Settings.js
I had to escape the line breaks otherwise the default string will be converted by `JSON.parse()` into multiple strings over multiple lines so that the the `lookupEnvironmentVariables` logic will not work for this value.
> Add env var for defaultPadText

- Dockerfile
I'm using OpenShift and this is running the containers by arbitrary user ids for security reasons but the users are always a member of the root group. So the `USER` definition of the `Dockerfile` will be ignored and the container crashes because the user has no permissions. This PR will just adjust the permissions a bit.
More information you can find here:
https://docs.openshift.com/container-platform/3.11/creating_images/guidelines.html#use-uid
> docker: add support for arbitrary user ids (OpenShift compatibility)

- src/node/db/PadManager.js
- tests/backend/specs/api/pad.js
Before this change, an array containing the ID of all the pads was scanned each time a new pad was created or deleted.
This change uses a Set, which improves the performances when there are many pads.
It also slightly optimizes a regex, anchoring it to the start of the DB key.
This PR is the same as #3752 by @Chocobozzz, only the order of the commits was modified to introduce the tests before everything else. It was resubmitted here to sidestep merge conflicts.
> PadManager: use a Set instead of an array in padList

- src/static/js/scroll.js
This was introduced by f1fcd16894e5 ("Add settings to scroll on edition out of viewport") in 2018-01-03.
@joassouza: was there a specific reason to use `require('/caretPosition')` instead of `require('./caretPosition')`, or was it just an oversight?
> scroll: replace absolute import with relative one

- src/node/handler/PadMessageHandler.js
`r` is undefined outside of the for loop, but used in the catch block of the try
statement
This fix is a quickfix.
This PR is based on devlop
> PadMessageHandler: fix for scoping error hiding original error

- Dockerfile
- doc/docker.md
This is leaner (no development dependencies are included in the container) and
faster (among other things, assets are minified & compressed).
> docker: build & run the container in production mode

- src/node/utils/Settings.js
- src/static/js/pluginfw/plugins.js
At the moment, Etherpad needs to be run from a specific directory, otherwise it stops without any hints of what's happening. In general, having the bahaviour of a program being dependent on CWD is surprising at best, and insecure at worst.
Some of this work already started with the module `AbsolutePaths`, released in **1.7.5**.
This PR moves on in that direction: it is no longer necessary to "cd" to the Etherpad base directory to start it: Etherpad runs from everywhere.
Known issues:
- unless the program is started as before (CWD == base directory) it is still not possible to install & uninstall plugins via the web interface
For this reason, the PR does not change the startup scripts yet.
> Absolute paths: initial work to allow Etherpad to be run independently on CWD

- doc/docker.md
- settings.json.docker
- settings.json.template
- src/node/utils/Settings.js
* Refactored docs for env vars using tables
* Added new env vars for nearly all configuration options
* Added possibility to set env setting to `null` using env vars
Please note: I was not able to test everything. Theoretically everything should work.
> docker: make settings fully configurable via env vars

- src/static/js/ace2_inner.js
This PR closes gritter pop ups when your focus is in the editor.  It closes ALL gritter notifications.  
This solves the problem of gritters taking too much focus from the editor, it is an accessibility requirement.
> close all gritters on escape key

- .dockerignore
Removing git-objects, which are not needed, from final docker image, to make it smaller.
@muxator : This follows wrong fix in issue #3776
Code base on branch "develop"
> chore(docker): removing git-objects from final docker image

- src/static/js/html10n.js
589b174
On a users first visit (no cookie present) the language cookie was being set to padOptions.lang (from settings.json on server). Removes this behavior, allowing l10n to localize based on priority (cookie, navigator.language, navigator.userLanguage, 'en'), the users first visit will instead have no language cookie, giving browser language priority unless another language is selected in the menu (setting language cookie)
77a3059
Better handling of locale variants (e.g when browser language is ru-RU)
closes #3882
> Improved browser language (navigator.language) support

- src/node/db/Pad.js
- src/node/utils/promises.js
Fix freeze on pad deletion (if it has many revisions)
Needs https://github.com/Pita/ueberDB/pull/118 first (because of https://github.com/Pita/ueberDB/pull/118/files#diff-0a774d4a9cc6e6d690c76811449906c1R214)
> Fix freeze on pad deletion

- bin/buildForWindows.sh
Bump node windows runtime: **10.18.0** -> **10.20.1**.
This is the latest version as of today.
**n.b.**: I just realized we are shippign the 32 bit version if nodejs. Probably it is time to switch to 64 bits by **1.8.4**.
> windows: bump the node version included in the prebuilt package

- src/package-lock.json
- src/package.json
For the first time in a VERY long time, we now have exactly 0 vulnerabilities reported by npm audit.
**BEFORE** this PR:
```
$ npm audit
=== npm audit security report ===
┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
[...]
found 4 low severity vulnerabilities in 13796 scanned packages
4 vulnerabilities require manual review. See the full report for details. …
```
> ZERO reported vulnerabilities in Etherpad 1.8.3

- src/static/js/Changeset.js
It's a simple fix but it had to be nuanced enough to solve it properly.
Bug Ref: #3932
> Fix inconsistencies when deleting content while timeslider is open

- doc/assets/style.css
**Details**
Basic styles for tables in documentation to improve readability.
Related to:
* https://github.com/ether/etherpad-lite/issues/3563
> DOCS: Basic styles for tables - https://github.com/ether/etherpad-lite/issues/3563

- src/static/css/timeslider.css
If the pad is bigger than height of screen, is was cropped (impossible to access the bottom). Fixed now
> timeslider: important fix pad content was cropped 

- src/package-lock.json
- src/package.json
This PR resolves a performance regression on MySQL introduced in ueberDb **0.4.5** (which was released as part of Etherpad **1.8.3**), bumping ueberDb to **0.4.9**.
This PR replaces #3952, in order to also include https://github.com/ether/ueberDB/issues/127 (backport of the performance fix on `bulkDelete()`). It also resolves merge conflicts on `package-lock.json`.
For a discussion on the performance fix, please see https://github.com/ether/ueberDB/commit/7762f0096458bcb1ada3ad634d1a43f99a1354f0 and the issue that came out of it: https://github.com/ether/ueberDB/issues/125.
> ueberdb: update 0.4.5 -> 0.4.9 to fix a performance regression

- tests/frontend/helper.js
- tests/frontend/specs/helper.js
I mentioned in #3730 that I thought that there needed to be a delay between resetting the cookies and returning from `newPad`, because the change wasn't taking effect otherwise. However, this test proves that incorrect, at least _almost all of the time_. Seemingly on rare occasion, it fails, which means either:
a) occasionally it does indeed need the delay
b) something else entirely is going on
When I have a bit more time, I can try to test it with and without the delay enough times to prove that the delay actually fixes it. But it's quite a rare occurrence so I'm not sure how to be sure about it. Alternately: it's so rare that it's fine, given that this is a test suite; this question is up to the reviewers.
> Fix clear cookies tests

- src/node/handler/PadMessageHandler.js
- src/node/utils/Minify.js
- src/static/js/ace.js
This is a proposal to fix #3956.
There is:
1. a problem of cache busting in ace.js left open by 95fd5ce2a45e;
2. 4177b3f9434 moved the font-face declarations from `src/static/css/pad.css` to two
imported files in a different directory, and this requires a rebase on clean-css.
Tested the following 4 combinations with **Firefox 75** on linux:
- minify: **true**|**false**
- directly invoking http://localhost:9001/p/somepad and http://localhost/pad/foo/p/somepad using the following nginx configuration:
```nginx
server {
listen       80;
server_name  pad.example.com;
access_log  /var/log/nginx/eplite.access.log;
error_log   /var/log/nginx/eplite.error.log;
location /pad/foo {
rewrite                /pad/foo/(.*) /$1 break;
rewrite                ^/pad/foo$ /pad/foo permanent;
proxy_pass …
```
> Fix/fonts behind reverse proxy when minify = true

- CHANGELOG.md
- src/package-lock.json
- src/package.json
Excerpt from the changelog:
* FIX: fix a performance regression on MySQL introduced in 1.8.3
* FIX: when running behind a reverse proxy and exposed in an inner directory, fonts and toolbar icons should now be visible. This is a regression introduced in 1.8.3
* FIX: cleanups in the UI after the CSS rehaul of 1.8.3
* MINOR: protect against bugged/stale UI elements after updates. An explicit cache busting via random query string is performed at each start. This needs to be replaced with hashed names in static assets.
* MINOR: improved some tests
* MINOR: fixed long-standing bugs in the maintenance tools in /bin (migrateDirtyDBtoRealDB, rebuildPad, convert, importSqlFile)
> release: prepare for 1.8.4

- bin/installDeps.sh
- bin/installOnWindows.bat
Advantages:
- reproducible install: every user will have the same, exact install, instead of
a slightly different one
- speed: installation of dependencies is measurably faster
- explicit: if a user setup is broken, from now on he'll have a clear error
message
Closes #3778
**TODO**:
Check impact on plugins (both via npm install and the admin interface)
> startup: use "npm ci" instead of "npm install" in startup scripts

- doc/localization.md
- settings.json.docker
- settings.json.template
- src/node/hooks/express/adminsettings.js
- src/node/hooks/i18n.js
- src/node/utils/Settings.js
- src/templates/admin/index.html
Allow locale string overrides in `settings.json`, an described in https://github.com/ether/ep_webrtc/issues/31. See documentation change in this PR for example.
> feat(i18n) Custom i18n strings

- tests/frontend/helper.js
- tests/frontend/specs/embed_value.js
- tests/frontend/specs/helper.js
This allows for setting "prefs" in tests, which is going to be very useful if not vital for testing ep_webrtc. (I use it here: https://github.com/ether/ep_webrtc/pull/56).
Also, I fixed a couple unrelated front end tests that were failing locally. All pass now on Firefox and Chromium!
> Testing: Add and test padPrefs for helper.newPad

- src/static/js/chat.js
- src/static/js/pad.js
- tests/frontend/helper.js
- tests/frontend/specs/chat.js
Fixes: https://github.com/ether/etherpad-lite/issues/3541
> Tests: ShowChat fix

- .travis.yml
- src/package.json
- tests/frontend/travis/remote_runner.js
- tests/frontend/travis/runnerBackend.sh
These changes have to be done on ether/etherpad-lite repo because if not they don't fire a travis build..
1. Remove npm cache from Travis, this was causing a world of pain.
2. Remove the broken line attribute tests.
3. Do a HTTP get against Etherpad to begin minification.
4. Wait 10 seconds after minification before running tests.
Still to do:
* [  ] Edge(all pass in local browser) = authorship_of_editions.js, select_formatting_buttons.js (bold & strikethrough)
I'm inclined to suggest these are saucelabs / selenium bugs.
> tests: Gateway timeout during tests

- src/static/js/pad.js
Solution for https://github.com/ether/etherpad-lite/issues/3830
OR
> Timeout logic - Ready for review

- .travis.yml
- tests/frontend/travis/runnerBackend.sh
Backend tests were dependent on cache which is a terrible idea.
1. Builds clean.
2. Doesn't spam log with curl request.
> tests: Fix backend testing which were always partially broken due to cache

- tests/frontend/specs/automatic_reconnect.js
- tests/frontend/travis/remote_runner.js
Isolating why Chrome is now failing in tests where it has been fine before.
> testing: New chrome testing hack slash workaround

- src/node/hooks/express/adminplugins.js
- src/node/server.js
- src/node/utils/UpdateCheck.js
- src/templates/admin/plugins-info.html
This PR checks on static.etherpad.org for the latest etherpad version and will show a hint in the console at runtime and on the troubleshooting page in the admin area.
closes #3937
> Add etherpad update check

- bin/buildForWindows.sh
Do not use old node version. Always use latest erbium node version for windows build
> Always use latest erbium node version for windows build

- settings.json.template
- src/node/handler/PadMessageHandler.js
- src/node/hooks/express/importexport.js
- src/node/utils/Settings.js
- src/static/js/pad_editbar.js
https://github.com/ether/etherpad-lite/issues/3964
Reasoning:  If you have already authed a user you can assume they are "trusted".  So a setting to override this is fine for instances which use an authentication plugin.
> Setting for allowing import - Ready for Review / Merge

- src/locales/en.json
- src/templates/index.html
Hide create/open pad buttons on index page since when requireSession or editOnly is set these buttons always fail
fixes #3970
This hides the buttons solely based on the settings and not depending on wether there is a session or not but i didn't know how to check that.
I also added a new translation key but only in en.json
Tests seem to be unaffected but it's hard to tell since running them multiple times results in different failures.
> ui: hide create/open pad buttons on index page

- Dockerfile
Without this change, plugin install failures are silently ignored.
> Docker: Abort image build when `npm install` fails

- src/locales/en.json
- src/node/hooks/express/socketio.js
- src/static/js/pad.js
- src/static/js/pad_cookie.js
- src/templates/pad.html
Here is a PR with a much better UX.  This is a proposed fix.
Safari / Brave users CAN use a pad in an iframe BUT if they refresh/rejoin Etherpad is not aware of who they are.
For #4031
> Better ux for no cookies

- tests/frontend/index.html
- tests/frontend/lib/mocha.js
- tests/frontend/runner.js
A new version of Mocha 7.1.2 was added, downloaded from Mocha official source, and integrated into the front-end tests infrastructure and running on the Browser.
The current version of Mocha was used with a workaround to extend the HTML reporter to add a custom reporter as a hidden div when runs on the browser.
To update this version I had to remove this custom runner `WebdriverAndHtmlReporter`, used to generate a text output in a hidden div to be generated by Mocha events.
Closes #3434
> updating mocha and refactoring the custom html reporter using events

- .travis.yml
Travis conditional to only run frontend tests if they are from the ether/ repository.  This is due to saucelabs environment variables not being set if they are from a pull request.
> tests: using travis conditions to decide if front end tests should be run or not.

- .travis.yml
Currently EVERY test job loads the sauce tunnel.  This is dumb and breaks a lot of things.
> tests: remove sauce tunnel for none frontend tests

- src/static/skins/colibris/src/components/chat.css
- src/static/skins/colibris/src/components/gritter.css
- src/static/skins/colibris/src/components/popup.css
Fix #4136 
Adds media queries to 3 CSS files in colibris skin folder, no changes outside of them. Tested on my installation & works well.
If you want to test it out quickly in Firefox, you can add `ui.prefersReducedMotion` to your about:config in Firefox and toggle the Boolean between 1 (on) and 0 (off).
New behavior for users with the setting enabled:
> Fix(UX): Add prefers-reduced-motion query for Colibris skin #4136

- tests/frontend/travis/runnerBackend.sh
Changes the behaviour of backendRunner.sh:
It will not terminate immediately on error, but instead run all the tests. I think it's useful to see the results of all test suites even when a single one fails (although there are only two atm - but this might change in the future). There was also a "kill and sleep" at the end, which had no effect. (Maybe it was meant to kill the node-process?)
Also removes the minification step for backend tests, because they don't need them.
> Fix backendRunner's exitcode

- tests/frontend/runner.js
- tests/frontend/travis/remote_runner.js
- tests/frontend/travis/sauce_tunnel.sh
1. prints duration of every test case to travis console
2. saves browser's console output in saucelabs (better way would be to print it too, but I don't know how to do that right now) - this will help in the future to detect warnings/errors printed to browser console during test runs - maybe we should also include ep server logs in travis?
3. sends sauce connect proxy tunnelIdentifier during test runs
4. sets parallel runs to ~~4~~ 6 again - this seems to work now (because of tunnelIdentifier?)
5. removes hard coded 10 seconds wait time for minification
6. update sauce connect proxy to 4.6.2
7. fixes the behaviour how we check, if a test run has succeeded. When the [killTimeout in runner.js](https://github.com/ether/etherpad-lite/blob/develop/tests/frontend/runner.js#L72) stops our tests …
> frontend test improvements

- src/node/handler/PadMessageHandler.js
prints the actual error message when an error is thrown in getChangesetInfo
> getChangesetInfo: print error message

- tests/frontend/specs/scroll.js
Changes to scroll tests to make them pass but afaik everything is broken due to browser restrictions RE sending keypresses so you can't trust these tests.
Resolves https://github.com/ether/etherpad-lite/issues/3748
> tests: Scroll test update (but potentially not fix)

- src/static/js/pluginfw/hooks.js
This PR fixes the error of not waiting the async code to finish.
As the forEach did not wait until the async code finish we may get a
hook set up incorrectly. To fix it, we use an "Array.map" to iterate and
wait the promises to be resolved and then return the values.
Fixes #4193
A better explanation why this should avoided can found here
https://codeburst.io/javascript-async-await-with-foreach-b6ba62bbf404
> fix: fix async code inside of loop

- tests/frontend/travis/remote_runner.js
This is more or less required (but probably not sufficient) for a successful test run of ep_webrtc on Chrome on Travis.
> Command line argument for chromium test for fake webrtc

- src/node/hooks/express/webaccess.js
This PR contains several commits that each do some minor cleanups to webaccess.js.
**PLEASE DO NOT SQUASH MERGE THIS PR—do a regular merge instead.**
* Whitespace fixes
* Add semicolons after statements
* Use single quotes everywhere
* Use arrow functions instead of `function` keyword
* Use `const` or `let` instead of `var`
* Simplify object construction
* Use `===` instead of `==` for comparison
* Rename `basicAuth` to `checkAccess`
* Restructure for readability and future changes
Future PRs will build on this PR to add some new features required for an authentication plugin I am writing.
> webaccess: Various cleanups

- src/static/js/pluginfw/hooks.js
Every existing caller of `aCallFirst` expects a list and will throw an exception if given `undefined`. (Nobody calls `callFirst`, except maybe plugins.)
> hooks: Always return a list from `aCallFirst` and `callFirst`

- src/static/js/pluginfw/plugins.js
- src/static/js/pluginfw/shared.js
Plugin authors are allowed to omit the function name in the `ep.json` parts definition. For example:
```
{
"parts": [
{
"name": "ep_example",
"hooks": {
"authenticate": "ep_example",
"authFailure": "ep_example"
}
}
]
}
```
If omitted, the function name is assumed to be the same as the hook name. Before this change, `hook_fn_name` for the example hooks would both be `/opt/etherpad-lite/node_modules/ep_example`. Now they are suffixed with `:authenticate` and `:authFailure`. This improves logging, and it makes it possible to use `hook_fn_name` to uniquely identify a particular hook function.
> pluginfw: Always include the function name in `hook_fn_name`

- src/node/hooks/express/webaccess.js
Not all authentication plugins require the Authorization header, so it might not be present in subsequent attempts. (In particular, a reverse proxy might strip it.)
> webaccess: Always sleep for 1s before returning HTTP 401

- src/node/handler/PadMessageHandler.js
This check is already made very early in `handleMessage`.
> PadMessageHandler: Delete redundant check

- src/static/js/pluginfw/plugins.js
`exports.parts` is a topologically sorted array, but the intermediate collection of parts assembled in `plugins.update()` is associative.
> plugins: Fix type typo

- src/static/js/pluginfw/hooks.js
I plan on splitting authFailure into authnFailure and authzFailure so that separate authentication and authentication plugins can coexist peacefully. This change will make it possible to mark the authFailure hook as deprecated (which simply logs a warning).
> hooks: New mechanism to deprecate hooks

- src/static/css/iframe_editor.css
- src/static/js/ace2_inner.js
> Fix performance for large pads

- tests/frontend/specs/responsiveness.js
run responsivness test but skip it on ff52.0/windows
> skip responsivness test on firefox 52.0/windows

- src/static/js/pad.js
`decodeURIComponent(null)` returns the string `'null'`, which we don't want.
> Use `null`, not `"null"`, if `sessionID` cookie doesn't exist

- src/node/handler/PadMessageHandler.js
This PR contains a few commits that each do some minor cleanups to PadMessageHandler.js.
**PLEASE DO NOT SQUASH MERGE THIS PR—do a regular merge instead.**
* Simplify `handleClientReady` a bit
* Invert logic to improve readability
* Use `===` instead of `==` for comparison
* Rename createSessionInfo to createSessionInfoAuth
> PadMessageHandler: Various cleanups

- src/node/db/SecurityManager.js
- src/node/db/SessionManager.js
- src/node/utils/promises.js
* Move session validity check and session author ID fetch to a separate function. This separate function can be used by hooks, making it easier for them to properly determine the author ID.
* Rewrite the remainder of checkAccess. Benefits:
* The function is more readable and maintainable now.
* Vulnerability fix: Before, the session IDs in sessionCookie were not validated when checking settings.requireSession. Now, sessionCookie must identify a valid session for the settings.requireSession test to pass.
* Bug fix: Before, checkAccess would sometimes use the author ID associated with the token even if sessionCookie identified a valid session. Now it always uses the author ID associated with the session if available.
> SecurityManager: Refactor checkAccess for readability, correctness

- src/node/hooks/express/socketio.js
Before, anyone who could create a socket.io connection to Etherpad could read, modify, and create pads at will without authenticating first.
The `checkAccess` middleware in `webaccess.js` normally handles authentication and authorization, but it does not run for `/socket.io` requests. This means that the connection handler in `socketio.js` must handle authentication and authorization. However, before this change:
* The handler did not require a signed `express_sid` cookie.
* After loading the express-session state, the handler did not check to see if the user had authenticated.
Now the handler requires a signed `express_sid` cookie, and it ensures that `socket.request.session.user` is non-null if authentication is required. (`socket.request.session.user` is non-null if and only if the …
> security: Fix authentication bypass vulnerability

- src/static/css/iframe_editor.css
Tested with both `no-skin` and `colibris`.
Fixes #4297.
cc @seballot
> css: Line up line numbers with their rows

- src/node/hooks/i18n.js
Before it only logged an error like this:
SyntaxError: Unexpected string in JSON at position XYZ
Now it also logs the filename, making it easier to figure out where
the bad data is:
failed to read file /path/to/etherpad-lite/src/locales/en.json: SyntaxError: Unexpected string in JSON at position XYZ
> i18n: Improve error logging when language JSON read fails

- src/node/hooks/express/webaccess.js
The authorization logic determines whether the user has already successfully authenticated by looking to see if `req.session.user` exists. If an authentication plugin says that it successfully authenticated the user but it did not create `req.session.user` then authentication will re-run for every access, and authorization plugins will be unable to determine whether the user has been authenticated. Return a 500 internal server error to prevent these problems.
> webaccess: Enforce creation of `req.session.user` by authn plugins

- doc/api/hooks_server-side.md
- src/node/hooks/express/webaccess.js
Authentication plugins almost always want to read and modify `settings.users`. The settings can already be accessed in a few other ways, but this is much more convenient.
> webaccess: Pass `settings.users` to the authenticate hook

- src/static/js/pad.js
- src/static/js/pad_editbar.js
I noticed this while troubleshooting a difficult-to-reproduce reconnect problem. If you know how to simulate a disconnect please let me know.
> Pad: Disable toolbar and import/export when reconnecting

- src/node/hooks/express/webaccess.js
Somehow I introduced this bug in commit 2bc26b8ef89ea0a5b447ad12586b694c6a830d4e but never noticed.
> webaccess: Fix syntax error (missing close curly brace)

- src/package-lock.json
- src/package.json
If mocha hangs after running the tests, hit Ctrl-C and wtfnode will print open files, open sockets, running timers, and running intervals. Adding an `after` function that closes/stops all of those things will ensure that mocha exits when it finishes running the tests.
> tests: Use wtfnode to determine why mocha isn't exiting

- doc/api/hooks_server-side.md
- src/node/db/SecurityManager.js
- src/node/hooks/express/webaccess.js
- tests/backend/specs/socketio.js
Before, a malicious user could bypass authorization restrictions imposed by the authorize hook:
* Step 1: Fetch any resource that the malicious user is authorized to access (e.g., static content).
* Step 2: Use the signed express_sid cookie generated in step 1 to create a socket.io connection.
* Step 3: Perform the CLIENT_READY handshake for the desired pad.
* Step 4: Profit!
Now the authorization decision made by the authorize hook is propagated to SecurityManager so that it can approve or reject socket.io messages as appropriate.
This also sets up future support for per-user read-only and modify-only (no create) authorization levels.
> security: Fix authorization bypass vulnerability

- doc/api/http_api.md
- src/node/db/API.js
- src/node/db/Pad.js
- src/node/handler/APIHandler.js
- src/node/handler/PadMessageHandler.js
- tests/backend/specs/api/pad.js
This PR is an implementation of https://github.com/ether/etherpad-lite/issues/4242
With this change we provide a way to copy pads without bringing all the history information (revisions, chats).
Etherpad is such a great tool, but in our instance we were having some problems with the current mechanism of pads duplication. A pad with 100k revisions has to perform 200k operations at least - get 100k information on the source pad and save 100k into the new pad. Although Etherpad provides a good mechanism of caching, that amount of operation occupies the CPU time too much. 
In our case we could use small instances of AWS machines t2.micro* to host Etherpad without a hitch if it wasn't that problem. As we have lots of users duplicating their pads, we had to increase our server capacity to a …
> Feature: copy without history

- src/package.json
- tests/frontend/travis/runnerBackend.sh
the backend tests currently fail but are green (due to wtfnode added recently always exiting with 0 - I already asked @rhansen if the problem with non-exiting tests is still present)
fixes #4311 
It's probably not the best method. For frontend tests we iterate over all node_modules subdirectories to find static/tests/frontend and in the backend case I just look for ep_* - all plugins start with ep_ right?
It seems to work in every of the following cases:
- no plugins installed
- plugin installed via /admin
- plugin installed via `npm i ep_comments_page` (when https://github.com/ether/ep_comments/pull/135 is resolved)
- more than one plugin with backend tests (I tested ep_comments, ep_font_color. ep_webpack seems to work too, but also has dependency resolution problems like ep_comments …
> Plugin backendtests in ci

- src/static/css/pad/layout.css
- src/static/css/pad/popup.css
- src/static/css/pad/popup_users.css
- src/static/css/pad/toolbar.css
- src/static/js/pad_editbar.js
- src/static/skins/colibris/src/components/toolbar.css
- src/static/skins/colibris/src/layout.css
Until now, the "mobile layout" (with right toolbar on bottom of the screen) was displayed only when screen was smaller than 800px. It made the toolbar break for screen about 1000px when a lot of plugins are in the toolbar.
Now instead, we detect with javascript when the toolbar icons overflow the natural space available, and we switch in "mobile layout" in such case
> Improve toolbar responsiveness for small screen Fixes #4321

- src/node/utils/promises.js
- tests/backend/specs/promises.js
Before this change, `promises.timesLimit()` created `concurrency - 1` too many promises. The only users of this function use a concurrency of 500, so this meant that 499 extra promises were created each time it was used. The bug didn't affect correctness, but it did result in a large number of unnecessary database operations whenever a pad was deleted. This change fixes that bug.
Also:
* Convert the function to async and have it resolve after all of the created promises are resolved.
* Reject concurrency of 0 (unless total is 0).
* Document the function.
* Add tests.
> utils: Fix promise creation accounting bug in promises.timesLimit

- doc/api/hooks_server-side.md
- src/ep.json
- src/node/db/DB.js
- src/node/hooks/express.js
- src/node/hooks/express/adminsettings.js
- src/node/hooks/express/errorhandling.js
- src/node/server.js
- src/node/stats.js
- src/node/utils/Minify.js
- src/package.json
- tests/backend/specs/socketio.js
* `src/node/server.js` can now be run as a script (for normal operation) or imported as a module (for tests).
* Move shutdown actions to `src/node/server.js` to be close to the startup actions.
* Put startup and shutdown in functions so that tests can call them.
* Use `await` instead of callbacks.
* Block until the HTTP server is listening to avoid races during test startup.
* Add a new `shutdown` hook.
* Use the `shutdown` hook to:
* close the HTTP server
* call `end()` on the stats collection to cancel its timers
* call `terminate()` on the Threads.Pool to stop the workers
* Exit with exit code 0 (instead of 1) on SIGTERM.
* Export the HTTP server so that tests can get the HTTP server's port via `server.address().port` when `settings.port` is 0.
> Refactor startup/shutdown for tests

- src/node/handler/PadMessageHandler.js
A session's sessioninfo could go away asynchronously due to a disconnect. Grab a reference once and use it throughout the function to avoid dereferencing a null sessioninfo object.
> PadMessageHandler: Make sessioninfo tracking more robust

- src/package-lock.json
- src/package.json
This reverts commit ae1142a799b91f20c9a54c233b8c1a80ca99d0a5.
According to https://github.com/ether/etherpad-lite/pull/4304#issuecomment-694833456 wtfnode always seems to exit with 0 even if the tests fail.
> Revert "tests: Use wtfnode to determine why mocha isn't exiting"

- doc/api/hooks_server-side.md
- src/node/handler/PadMessageHandler.js
Move the handleMessageSecurity and handleMessage hooks after the call to securityManager.checkAccess.
Benefits:
* A handleMessage plugin can safely assume the message will be handled unless the plugin itself drops the message, so it doesn't need to repeat the access checks done by the `handleMessage` function.
* This paves the way for a future enhancement: pass the author ID to the hooks.
Note: The handleMessageSecurity hook is broken in several ways:
* The hook result is ignored for `CLIENT_READY` and `SWITCH_TO_PAD` messages because the `handleClientReady` function overwrites the hook result. This causes the client to receive client vars with `readonly` set to true, which causes the client to display an immutable pad even though the pad is technically writable.
* The formatting toolbar …
> PadMessageHandler: Move handleMessage hooks after access check

- doc/api/hooks_server-side.md
- src/node/hooks/express/webaccess.js
- src/node/server.js
- tests/backend/specs/webaccess.js
This makes it possible for reverse proxies to transform 403 errors into something like "upgrade to a premium account to access this pad".
> webaccess: Return 401 for authn failure, 403 for authz failure

- src/node/hooks/express/socketio.js
- tests/backend/specs/socketio.js
This should make it possible to embed a pad in an iframe from another site as long as `settings.requireAuthentication` is false.
Fixes #4332
> security: Don't require express_sid if authn not required

- src/package-lock.json
- src/package.json
- tests/backend/specs/api/importexportGetPost.js
This PR contains some commits that improve the import and export tests. **Please do not squash merge this PR.**
* Delete unused imports and code
* Fix abiword/soffice check
* Use `this.skip()` when skipping tests
* Skip all import/export tests if `!allowAnyoneToImport`
* Factor out common skip checks
* Rewrite import/export tests to use async and supertest
> tests: Import/export test fixes and cleanups

- src/node/handler/PadMessageHandler.js
- src/node/handler/SocketIORouter.js
Benefits:
* More functions are now async which makes it possible for future changes to use await in those functions.
* This will help keep the server from drowning in too many messages if we ever add acknowledgements or if WebSocket backpressure ever becomes reality.
* This might make tests less flaky because changes triggered by a message will complete before the Promise resolves.
> PadMessageHandler: Block Promise resolution until message is handled

- src/node/hooks/express/webaccess.js
- tests/backend/specs/socketio.js
Also:
* Minor test cleanups (`function` instead of arrow functions, etc.).
* Add a test for a case that was previously not covered.
Fixes #4345
> security: Fix authz check for pad names with encoded characters

- src/static/js/pad.js
Commit 0bb8d73ba2969bc2c871c5095de19188a75b2b54 fixed the author ID that is saved in the socket.io sessioninfo when the client sends a `CLIENT_READY` with `reconnect` set to true, so it is now safe to undo the workaround from PR #3868.
Fixes #4331.
> pad: Revert back to sending `CLIENT_READY` on reconnect

- tests/backend/specs/api/sessionsAndGroups.js
This PR contains some commits that clean up the tests for the session and group API. **Please do not squash merge this PR.**
* Delete unused variable
* Use `let` and `const` instead of `var`
* Group session and group tests to improve readability
* Use async/await instead of callbacks, use assert
* Fix typo (publicstatus -> publicStatus)
* Check for true/false, not truthiness
> tests: Session and group test cleanups and minor bugfixes

- src/node/db/ReadOnlyManager.js
- src/node/handler/ExportHandler.js
- src/node/hooks/express/importexport.js
The export request hook wasn't testing if the pad's id was from a read-only
pad before validating with the pad manager.
This includes an extra step that makes the read-only id verification and also
avoids setting the original pad's id as the file's name.
Closes #3154.
> importexport: Fix readOnly pad export

- doc/api/hooks_server-side.md
- src/node/hooks/express/webaccess.js
- src/static/js/pluginfw/hooks.js
- tests/backend/specs/socketio.js
- tests/backend/specs/webaccess.js
Before this change, the authorize hook was invoked twice: once before authentication and again after (if settings.requireAuthorization is true). Now pre-authentication authorization is instead handled by a new preAuthorize hook, and the authorize hook is only invoked after the user has authenticated.
Rationale: Without this change it is too easy to write an authorization plugin that is too permissive. Specifically:
* If the plugin does not check the path for /admin then a non-admin user might be able to access /admin pages.
* If the plugin assumes that the user has already been authenticated by the time the authorize function is called then unauthenticated users might be able to gain access to restricted resources.
This change also avoids calling the plugin's authorize function twice per …
> webaccess: Move pre-authn authz check to a separate hook

- doc/api/hooks_server-side.md
- settings.json.docker
- settings.json.template
- src/node/db/SecurityManager.js
- src/node/hooks/express/webaccess.js
- tests/backend/specs/socketio.js
Also:
* Group the tests for readability.
* Factor out some common test setup.
Fixes #4325
> New user-specific `readOnly` and `canCreate` settings

- settings.json.docker
- settings.json.template
- src/node/hooks/express/webaccess.js
- src/node/utils/Minify.js
- src/node/utils/Settings.js
- src/node/utils/tar.json
- src/package-lock.json
- src/package.json
- src/static/js/pad.js
- src/static/js/pad_cookie.js
- src/static/js/pad_editor.js
- src/static/js/pad_utils.js
- src/static/js/timeslider.js
This PR contains a few commits to improve cookie handling:
* Embedding Etherpad in an iframe from another site should work better, especially if the user sets `cookie.sameSite` to `"None"` in `settings.json`. Using `None` for `SameSite` allows the cookies to be used as third-party cookies.
* `SameSite` is set to `Lax` by default, which should provide a better user experience vs. `Strict`.
* Special characters in cookie values and properties (semicolon in particular) are properly escaped, which should help prevent some XSS vulnerabilities.
**Please do not squash merge this PR** because the commits are intentionally separate:
* Refactor `pad_cookie.js`
* Use js-cookie to read and write cookies
* Use `Lax` instead of `Strict` for `SameSite`
* Use `SameSite=None` if in an iframe from another …
> cookies: Improve experience for third-party iframes

- src/node/db/SecurityManager.js
- src/node/hooks/express.js
- src/node/hooks/express/socketio.js
- src/node/hooks/express/webaccess.js
- tests/backend/specs/socketio.js
This PR contains a few commits to simplify and improve the Express and express-session middleware setup. **Please do not squash merge this PR** because the commits are intentionally separate:
* webaccess: Wrap long lines
* webaccess: Simplify Express and express-session setup
* express: Use `const` and `let` instead of `var`
* socketio: Delete redundant authentication check
* socketio: Reuse the `express-session` middleware
* express: Move general Express setup from `webaccess.js`
> Express and express-session middleware cleanup

- settings.json.template
- src/locales/en.json
- src/node/handler/PadMessageHandler.js
- src/node/hooks/express/importexport.js
- src/node/hooks/express/webaccess.js
- src/node/utils/Settings.js
- src/static/css/pad.css
- src/static/js/collab_client.js
- src/static/js/pad_editbar.js
- src/templates/pad.html
- tests/backend/common.js
- tests/backend/specs/api/importexportGetPost.js
- tests/backend/specs/socketio.js
- tests/backend/specs/webaccess.js
- tests/frontend/travis/runnerBackend.sh
This PR removes the `allowAnyoneToImport` setting and replaces it with a call to the `webaccess.canUserModify` function. **Please do not squash merge this PR** because it has a few commits that are intentionally separate:
* tests: Factor out common server setup/teardown
* tests: Switch import/export tests to self-contained server
* tests: Always run the import unsupported file type test
* webaccess: Check for read-only pad ID in `userCanModify`
* webaccess: Fix pad ID extraction for import and export paths
* import: Allow import if pad does not yet exist
* import: Replace the `allowAnyoneToImport` check with `userCanModify`
Fixes #4381.
> import: Replace the `allowAnyoneToImport` check with `userCanModify`

- tests/backend/common.js
This makes it easier to see the test results, and it hides some scary-looking but intentional error messages.
This code will likely have to be updated if/when we change the logging library (see issue #1922).
> tests: Disable non-test logging unless level <= DEBUG

- Dockerfile
- bin/cleanRun.sh
- bin/debugRun.sh
- bin/fastRun.sh
- bin/functions.sh
- bin/installDeps.sh
- bin/run.sh
Fixes: #4335 for both Docker and Linux setup:
- add `--experimental-worker` to Dockerfile
- move common constants and functions to `functions.sh` adding a new `compute_node_args` that may compute additionals node arguments based on several tests. Here, use this function to add `--experimental-worker` when node 10 is detected.
- source `functions.sh` in all startup scripts, and use `compute_node_args` as a node argument
I did not check Windows environment since I don't have any
> WIP: Run node 10 with '--experimental_worker' flags

- .travis.yml
- tests/frontend/travis/runner.sh
We should now be able to re-run the travis tests due to node 10 being fixed.
> tests: re-enable docker tests in travis

- src/static/js/pluginfw/read-installed.js
The debug statement mostly printed the following useless message over and over, causing Travis CI logs to become truncated:
[DEBUG] pluginfw - [ undefined ] returning
> plugins: Delete noisy and useless debug message

- src/node/hooks/express/tests.js
- tests/frontend/helper.js
- tests/frontend/specs/helper.js
This PR contains several of the easy fixes from #4408, plus some additional fixes. I wanted to get them in quickly because some of the test work I'm doing depends on them.
**Please do not squash merge** because the commits are intentionally separate:
* Aggressively filter out non-.js files
* Fix unchainable `helper.waitFor().fail()`
* Use default arguments for `helper.waitFor`
* Teach `waitFor()` to reject if the predicate throws
* Change `waitFor()` to check before first sleep
* don't force a callback in it, so we can use async in tests
* add waitForPromise method and test for it
* `waitForPromise()` test improvements
cc @webzwo0i
> tests: Frontend test infrastructure low-hanging fruit

- src/static/js/chat.js
- src/static/js/gritter.js
- src/static/js/pad.js
- src/static/js/pad_utils.js
* pad: Include .js URL in `/jserror` error report
* gritter: Accept jQuery or DOM objects for title and text
* pad: Improve rendering of uncaught exceptions
* gritter: Treat strings as text, not HTML
* pad: Delete do-nothing `sendClientReady` wrapper
* pad: Check for null collabClient in socket.io event handlers
* pad: Pop up an error message dialog box upon socket.io error
Addresses #3405.
> pad: Pop up an error message dialog box upon socket.io error

- src/locales/en.json
- src/static/js/pad_automatic_reconnect.js
* Use jQuery methods to build DOM elements
* Move out pad.modals.reconnecttimer trailing space
* Use an ellipsis instead of two periods
cc @Nikerabbit
> l10n: Minor string fixes

- doc/api/hooks_server-side.md
- src/node/db/Pad.js
This PR gives additional access to `revs` and `changeset` within a `padUpdate` hook.
It is actually a commit which is since 2019 already part (https://github.com/bigbluebutton/etherpad-lite/commit/5bc37fc92714e82165386dc0a5dd467609169a87) of the [BigBlueButton Etherpad fork](https://github.com/bigbluebutton/etherpad-lite) and is used there, along with [ep_redis_publisher](https://github.com/pedrobmarin/ep_redis_publisher), to create a nice live subtitles / closed captions feature.
I think it would be nice to merge this for following reasons:
1. Allows more possibilities for other use cases.
2. Gives BigBlueButton the opportunity to switch back to the official etherpad branch again instead of maintaining a, currently quite outdated, fork.
> plugins: include more data within padUpdate hook

- tests/frontend/helper.js
- tests/frontend/helper/methods.js
- tests/frontend/helper/ui.js
- tests/frontend/index.html
- tests/frontend/specs/chat.js
- tests/frontend/specs/delete.js
- tests/frontend/specs/helper.js
- tests/frontend/specs/responsiveness.js
- tests/frontend/specs/timeslider_follow.js
- tests/frontend/specs/timeslider_labels.js
- tests/frontend/specs/timeslider_numeric_padID.js
- include test for #4389 
- don't include sendkeys in index.html as it's included in helper.init
- don't force the usage of callbacks in `it`, so we can use async
- mocha opts: add default timeout and replace ignoreLeaks with checkLeaks as the former is deprecated
refactored chat.js, timeslider_labels, timeslider_numeric_padID and timeslider_follow
Should I issue single PRs only with one test file at a time?
> refactor some frontend tests

- tests/frontend/specs/helper.js
it errored in https://travis-ci.org/github/ether/ep_table_of_contents/jobs/738010629#L2313
Not optimal but CI is probably not super accurate when running in a shared environment
> tests: relaxed constraint on the number of interval triggers

- tests/frontend/helper/methods.js
This tries to work around one bug was with timeslider not loading properly:
https://app.saucelabs.com/tests/a2e793dffb5c4f07a2e52855fd0a4df1 at minute ~4:26 (I don't know how to link to specific frames and used ffmpeg to see the video frame-by-frame)
You can see the empty timeslider without locale strings, then locale strings are added ("No authors" and "Return") and then the timeout happens. I can reproduce the same behaviour when manually removing timeslider.js. Because you can see a delay between loading the timeslider's html and loading en.json there is probably also an delay for timeslider.js, so it's not loaded in time.
Better loading times should be achieved when https://github.com/ether/etherpad-lite/pull/4285 is ready, but there is some more work to do before that'll be finished.
> tests: 10 sec maximum wait time for timeslider

- doc/api/hooks_overview.md
- src/node/hooks/express/admin.js
- src/node/hooks/express/adminplugins.js
- src/node/hooks/express/adminsettings.js
- src/node/hooks/express/apicalls.js
- src/node/hooks/express/errorhandling.js
- src/node/hooks/express/importexport.js
- src/node/hooks/express/openapi.js
- src/node/hooks/express/padreadonly.js
- src/node/hooks/express/padurlsanitize.js
- src/node/hooks/express/socketio.js
- src/node/hooks/express/specialpages.js
- src/node/hooks/express/static.js
- src/node/hooks/express/tests.js
- src/node/hooks/express/webaccess.js
- src/node/hooks/i18n.js
- src/package-lock.json
- src/package.json
- src/static/js/pluginfw/hooks.js
- tests/backend/common.js
- tests/backend/specs/hooks.js
Rewrite the `callAll` and `aCallAll` functions to support all reasonable hook behaviors and to report errors for unreasonable behaviors (e.g., calling the callback twice).
Now a hook function like the following works as expected when invoked by `aCallAll`:
```
exports.myHookFn = (hookName, context, cb) => {
cb('some value');
return;
};
```
> hooks: Rewrite `callAll` and `aCallAll` for consistency

- src/node/utils/Settings.js
Closes https://github.com/ether/etherpad-lite/issues/4417
This makes it possible for Etherpad to find the latest commit when the HEAD is detached. Not sure what the right way to go about testing this is, or if tests are needed.
> utils: Fix commit checking on detached HEAD

- src/node/hooks/express/openapi.js
- src/package-lock.json
- src/package.json
Fixes error message mentioned in #4378, upgrades to `http-errors@1.8.0`, utilise new isHttpError utility introduced by the new version of the package.
> Use correct constructor for 404,501 error handlers

- doc/api/hooks_server-side.md
I accidentally describe the wrong key name in the docs during this merge request ["plugins: include more data within padUpdate hook" (#4425)](https://github.com/ether/etherpad-lite/pull/4425)
this fixes it.
There was the wish by @rhansen to change the name from `revs` to `rev`:
My main motivation is to merge some changes from the [BigBlueButton fork](https://github.com/bigbluebutton/etherpad-lite) upstream, so that it eventually could throw away the fork and use the official etherpad releases again. Changes the key would also require changes in the BigBlueButton code itself which would make the process way more difficult.
So I would prefer, even if it would make the key slightly more reasonable, to not change it :)
> docs: fix key in padUpdate context

- src/node/utils/tar.json
I can't get to the bottom of it because of time constraints, but the inclusion of async in tar.json is problematic. Without this PR caching_middleware.js won't add max-age, last-modified and expires headers. As a result this file will never be cached. It's even worse, because the file is downloaded two times resulting in 700kb+. (The problem is also present on video.etherpad.com)
The reason, why the file is downloaded two times is probably connected with iframes/pad.html not sharing javascript when a pad loads. (e.g. https://github.com/ether/etherpad-lite/blob/develop/src/static/js/ace.js#L266-L269 needs ace2_common.js). 
With this PR proper headers are added, so all subsequent requests are served from browser cache.
> performance/bugfix: remove broken async inclusion in tar.json

- tests/backend/specs/api/importexportGetPost.js
- tests/backend/specs/socketio.js
* tests: Delete unnecessary `describe()` wrapper
* tests: Clear auth hooks before running socket.io unit tests
* tests: Clear auth hooks before running import/export unit tests
> tests: Clear auth hooks before running unit tests

- .travis.yml
- tests/frontend/specs/helper.js
- tests/frontend/travis/remote_runner.js
- set default exit code of the frontend tests (remote_runner.js) to 1. In case saucelabs runner aren't started (limit of parallel worker) the callback of the worker that is pushed to `async#queue` won't be called. This results in `queue#drain` to never be called and the script just silently exits with a default exit code (cf https://travis-ci.com/github/ether/ep_comments/jobs/413945558)
- Increase the "no messages received" timeout of travis from 10 to 15 minutes. (frontend tests would start to exceed the limit very soon) - I did not see builds that hang for more than ten minutes recently, but if this would happen again and 15 minutes delay for a hanging test would be too much, we certainly can lower it again.
- libreoffice is only used during backend tests at the moment. instead of …
> Speed up and fix travis

- CHANGELOG.md
- src/node/db/SecurityManager.js
- src/node/db/SessionManager.js
v1.8.6 was released with a couple of critical session bugs. Cherry-pick the fixes to `master` so that users checking out `master` can use sessions.
Fixes #4454.
> Cherry-pick important v1.8.6 fixes to master

- .gitignore
That file is checked in so there's no reason to ignore it.
Fixes #4460.
cc @mcblum
> Remove `src/static/js/jquery.js` from `.gitignore`

- src/node/hooks/express/admin.js
- src/node/hooks/express/adminplugins.js
- src/node/hooks/express/adminsettings.js
- src/node/hooks/express/specialpages.js
This makes it possible for EJS templates and `eejsBlock_*` hook functions to access the user's express-session state.
> Add `req` to EJS render args when possible

- doc/api/hooks_server-side.md
- src/node/handler/PadMessageHandler.js
The `client` variable is actually a socket.io Socket object. Rename it to reduce confusion.
> PadMessageHandler: Rename `client` to `socket`

- src/static/js/ace2_inner.js
This makes it possible to disable `contentEditable` for certain elements in some circumstances (e.g., on links so that users can click on them normally).
Addresses (but does not fix) #4456.
Also some cleanups (**multiple commits**):
* Delete commented-out code
* Replace `setClassPresence(x, ...)` with `x.classList.toggle(...)`
> Use `contentEditable` for all browsers

- src/node/hooks/express/webaccess.js
- src/node/utils/Settings.js
- tests/backend/specs/webaccess.js
Two commits:
* webaccess: Be extra paranoid about nullish password
* Settings: Don't filter out users based on `password` or `hash`
Some authentication plugins use the users defined in the `users` object but ignore the `password` and `hash` properties.
The second commit deletes all of the filtering logic, including the logic that filters out users that have both `password` and `hash` properties defined. I could have kept that check, but decided to remove it because:
* There's no harm in defining both `hash` and `password`.
* Allowing both makes it easier to transition from one scheme to another.
* It's fewer lines of code to maintain.
> Settings: Don't filter out users based on `password` or `hash`

- src/static/css/pad/gritter.css
- src/static/js/html10n.js
When translation expects arguments to be replaced, but the arguments are missing big red error message is displayed. I believe that that kind of translation errors should be only visible in the console just as errors when a value is missing for the current translation key in the users current selected language. Also added style update to gritter.css as long error messages where overflowing the error popup and hard to read and close by the user:
> bugfix/translations: Fix missing arg handling in html10n.js

- doc/api/hooks_server-side.md
- src/node/utils/ExportEtherpad.js
- src/node/utils/ImportEtherpad.js
The goal of this PR is to include the ability for .etherpad exports and imports to be extended by plugins which want to export and import additional data as well as padIds..  
Still to do 
Opinions on approach invited.
Also worth noting that comments exportHTML.js tests are broken, they are only defining a selection as a comment but not storing the actual comment contents rendering setHTML pretty much useless for these tests..... :\  
For me I can use preformatted JSON to import pre-created .etherpad blobs which contain comments and test against those...
Tests are included in ep_comments which runs in travis so will be covered.
> pluginfw: Export .etherpad hooks

- doc/api/hooks_server-side.md
- src/node/utils/ExportHtml.js
The ep_comments_page plugin will have to be updated. See: https://github.com/ether/ep_comments/pull/157
> HTML export: Move `padId` to context object property

- doc/api/pluginfw.md
- doc/plugins.md
- src/static/js/pluginfw/hooks.js
- src/static/js/pluginfw/installer.js
- src/static/js/pluginfw/plugins.js
- src/static/js/pluginfw/shared.js
- tests/backend/specs/hooks.js
* docs: Wrap long lines
* docs: Revise plugin documentation
* plugins: Fix plugin name in error messages
* plugins: Use functions from `fs.promises`
* plugins: Call `require('./hooks')` at top level
* plugins: Don't export `callInit`
* plugins: Delete unused `ensure` function
* plugins: `async`ify more functions
* plugins: Use a log4js logger for npm messages
* plugins: Default the module name to the plugin name
> plugins: Various minor improvements

- src/node/utils/Minify.js
Terser is not called because of a mime type mismatch.
Please do not merge yet! I have more minify stuff coming in. I have struggled a while with testing this and finally made puppeteer-tests, because it allowed me to easily spy on requests. However, the recent webaccess tests from @rhansen made me think again and now I want to include more unit-style tests instead.
The reason not to merge yet: there is a performance degradation with caching middleware and minify regarding file system access. With this terser-fix caching_middleware would always regenerate packages. Will fix this.
another thing: static assets are directly served in Minify. Minify stats files on every request, which is good, when we want to serve updated files directly without restart. However, the caching_middleware does …
> Performance bigfix: minify fixes

- src/static/js/pad_utils.js
* pad: Use a relative URL to simplify
* pad: Pop up an error message on unhandled Promise rejection
* pad: Include the stack in the data sent to `/jserror`
> pad: Pop up an error message on unhandled Promise rejection (and other improvements)

- src/node/hooks/express/specialpages.js
- tests/backend/specs/specialpages.js
- tests/backend/specs/webaccess.js
This fixes a bug introduced in commit ed5a635f4c113ba7a535b51b30245adc5cfb6cf0.
Fixes #4495
cc @webzwo0i 
Also:
* add regression test for #4495
* Move `/javascript` test to `specialpages.js`
> Fix bad paren placement in `/javascript` handler

- src/node/hooks/express/webaccess.js
Multiple commits, with the main one being the `async`ification of `checkAccess`:
* webaccess: Use a non-capturing regex group
* webaccess: Fix some ESLint errors
* webaccess: Don't export `checkAccess`
* webaccess: Asyncify `checkAccess`
> webaccess: Asyncify `checkAccess`

- src/node/utils/caching_middleware.js
- tests/backend/specs/caching_middleware.js
A mime type mismatch, too.
The responseCache caches all headers, including `Content-Encoding`. In case a client does not set `Accept-Encoding: gzip` while another client requested the resource before and had this header set, the resource would be delivered uncompressed, but the `Content-Encoding: gzip` header would be present.
I think this is wrong, so now the `Content-Encoding` header gets deleted in that case.
> Fix gzip not triggered for packages

- src/node/utils/LibreOffice.js
This prevents `npm test` from freezing for two minutes after the tests complete.
Also switch to an arrow function for the `setTimeout` callback.
> Clear hang timeout timer when LibreOffice exits

- tests/frontend/travis/runnerBackend.sh
On loglevel INFO, when running the backend tests, etherpad prints blob of 80k length text and lots of emojis & their HTML entities.
Github does not like that and takes forever. Setting loglevel to WARN seems to fix it.
> backend tests: change loglevel to WARN

- tests/frontend/runner.js
another small typo that leads to hanging pads on saucelabs for some browsers
> frontend tests: fix trailing comma in runner.js

- package-lock.json
- package.json
- tests/frontend/runner.js
- tests/frontend/specs/change_user_color.js
- tests/frontend/specs/change_user_name.js
- tests/frontend/specs/clear_authorship_colors.js
- tests/frontend/specs/importexport.js
- tests/frontend/specs/responsiveness.js
- tests/frontend/specs/timeslider.js
- tests/frontend/specs/timeslider_follow.js
- tests/frontend/travis/remote_runner.js
Trailing commas in function arguments is only supported in ECMAScript 2017 and later. https://github.com/ether/eslint-config-etherpad/commit/673ab07acfdf9df5eb6e6580703e7715c7cb1354 reconfigured the `comma-dangle` rule to prohibit such commas. This PR applies that rule change.
* lint: Bump eslint-config-etherpad to 1.0.11
* lint: Rerun `eslint --fix` to nuke trailing function call commas
cc @webzwo0i
> tests: Delete trailing commas in function arguments

- src/node/hooks/express/adminplugins.js
- src/node/hooks/express/adminsettings.js
- src/static/js/admin/plugins.js
* admin: Delete unused `search_results`
* lint: Fix ESLint errors in `/admin/plugins` code
* admin/plugins: Simplify jQuery search for plugin actions
* admin/plugins: Use jQuery to build the Update button
* admin/plugins: Don't keep adding more Update buttons
> admin/plugins: Don't keep adding more Update buttons

- src/static/js/pad_utils.js
This fixes a bug introduced in commit c845d985e0d6014f2c2474564c59f33cdc552de6.
> pad: Fix wrong variable name in global exception handler

- src/node/utils/padDiff.js
Missing await in call to this._pad.getInternalRevisionAText(rev). Function returns a promise (see call in line 81 of same file). This bug breaks the createDiffHTML API call (how I discovered it).
> missing await in createClearStartAtext

- src/static/css/pad.css
- src/static/css/pad/loadingbox.css
- src/templates/pad.html
* css: Delete absolute `line-height`
* css: Apply font formatting to the text, not the high-level div
* pad: Add a hook for the permission denied block
> pad: New eejsBlock hook for the permissionDenied div

- tests/backend/specs/api/importexport.js
- tests/backend/specs/contentcollector.js
due to a write to a global variable, only the last defined test in importexport.js was run.
also does some improvement on readability of the test results and activates a test in contentcollector.js that was not executed due to duplicate keys.
> Enable importexport tests

- src/node/handler/ImportHandler.js
- src/node/utils/ImportHtml.js
- tests/backend/specs/api/importexport.js
- tests/backend/specs/contentcollector.js
import should only use body. removes a workaround that results in empty pads if an empty title element is present.
The PR is based on another PR that enables the tests for importexport, so it needs rebasing in case the other gets merged in first. alternatively merge this without squashing, then the other PR can be closed.
It might be useful in the future to parse style tags inside <head> on import though
> Ignore head tag on import

- src/templates/export_html.html
- tests/backend/specs/api/importexport.js
An indented list is rendered with bullets when exported as HTML. When exported as text, tabs are used (and no `*` is present, in contrast to bullet lists).
One solution is to include CSS for `list-style: none` on uls that have the indent class. That's what I did.
(Another would be to remove ul and adding tab/spaces instead)
When HTML is exported via API its up to the client to understand the semantics of the ul's class attribute.
> add list-style:none for ul.indents in exported HTML

- tests/backend/specs/api/importexport.js
- tests/backend/specs/contentcollector.js
some tests for the space bug, also adding a test for preformatted text.
If you have an idea on two weird nbsp issues:
https://github.com/ether/etherpad-lite/compare/space-bug-tests?expand=1#diff-a90433e636d6f460547f9069a3ca81bbbccfa776da404a902d6ac898edb22a81R75 
It swaps the nbsp and normal space - while normally the a nbsp preceeding a word is replaced by a normal space, here a normal space also got replaced by nbsp
https://github.com/ether/etherpad-lite/compare/space-bug-tests?expand=1#diff-a90433e636d6f460547f9069a3ca81bbbccfa776da404a902d6ac898edb22a81R173
In that preformatted element, a normal space got replaced by nbsp, while in the other lines the last space before a word is a normal space.
> tests: tests for space & nbsp; characters

- src/static/js/broadcast.js
- tests/frontend/specs/timeslider_follow.js
@JohnMcLear can you test if you can still replicate the failing timeslider_follow test?
It changes the scroll-behavior from smooth to auto. After that the test is never failing for me. I've seen that the smooth scrolling sometimes stops before reaching the offset. With auto I can't reproduce this anymore.
I also increased the number of lines that are in the pad view below the changed line. consider a pad with 40 lines and a change in the last line. To meet the test assumption, the last line should be the first visible line in the pad. That's not the case, when the display size is large enough. With a lot of lines after the changed line, so that the whole view port consists of lines, it will successfully scroll the changed line into the position of the "first visible line"
> change scroll-behavior to auto

- doc/api/hooks_server-side.md
- src/ep.json
- src/node/db/DB.js
- src/node/hooks/express.js
- src/node/hooks/express/adminsettings.js
- src/node/hooks/express/socketio.js
- src/node/server.js
- src/node/stats.js
- src/node/utils/Minify.js
- src/node/utils/tar.json
- src/static/js/admin/plugins.js
- src/static/js/admin/settings.js
- src/static/js/pad.js
- src/static/js/socketio.js
- src/static/js/timeslider.js
- src/templates/admin/plugins.html
- src/templates/admin/settings.html
- tests/backend/common.js
- tests/backend/specs/socketio.js
* lint: Fix some straightforward ESLint errors
* express: Factor out common server shutdown logic
* express: New expressCloseServer hook
* Reformat `src/ep.json`
* socket.io: Delete ignored `resource` option
* socket.io: Factor out client connection logic
* socket.io: Reconnect if the server disconnects
* socket.io: Disconnect clients when closing HTTP server
Fixes #4546.
TODO:
> socketio: Disconnect clients when closing HTTP server

- src/node/utils/Settings.js
The idea of this line is good: when we set loglevel DEBUG it should set socket.io into debug mode, too. However, that line is wrong (syntax is more like `socket.io:*` not `socket.io:DEBUG`) and it also blocks all other dependencies that use the debug package to print debug statements that'd be visible when using `DEBUG=* node src/node/server.js`.
If you find that enabling DEBUG logging should activate debug logging in *all* dependencies, that use the debug package, then changing this line to `if (loglevel === 'DEBUG') {process.env.DEBUG="*";}` would probable work. I'm okay with that, but in this PR I simply remove that line, so that DEBUG loglevel only applies to etherpad-internal logging and if someone wants the debug logs from dependencies that use the debug package, they need to set …
> remove explicitly setting process.env.DEBUG

- bin/plugins/checkPlugin.js
* checkPlugin: New `execSync()` convenience function
* checkPlugin: Move log messages where they make more sense
* checkPlugin: Don't capture stdout when unnecessary
* checkPlugin: Add lots of Git sanity checks
* checkPlugin: Don't create an empty commit
> Various checkPlugin improvements

- bin/plugins/checkPlugin.js
* checkPlugin: Use `--name-status` for `git diff-index`
* checkPlugin: Split dirty working directory check into two checks
> checkPlugin: Fix git sanity checks

- bin/plugins/README.md
- bin/plugins/checkPlugin.js
* checkPlugin: New `writePackageJson()` convenience function
* checkPlugin: Make sure `package.json` ends with a newline
* checkPlugin: Unconditionally run `npm install`
* checkPlugin: Use absolute path when installing `ep_etherpad-lite`
* checkPlugin: Move dependency update logic to a generic function
* checkPlugin: Ensure that a peer dep for `ep_etherpad-lite` exists
* checkPlugin: Use git to determine whether there were changes
* checkPlugin: Don't nuke `node_modules/`
* checkPlugin: Display a diff of the changes
* checkPlugin: Revise README.md
* checkPlugin: Make `autocommit` imply `autoupdate`, `autoupdate` imply `autofix`
* checkPlugin: Merge the `autoupdate` option into `autofix`
> More checkPlugin.js enhancements

- package-lock.json
- src/node/db/DB.js
* Revert "db: Capitalize `Database` constructor"
* Sync top-level `package-lock.json`
> Fix name of ueberdb constructor

- README.md
Removes ep_page_view plugin from the installation instructions in README.md to aid new users installing etherpad-lite.
According to the plugin directory at https://static.etherpad.org/index.html, the plugin is defunct as it is now part of etherpad-lite core and when I tried installing etherpad with the plugin (following the instructions), its installation resulted in an error every time I opened a pad.
> docs: Remove ep_page_view from README

- src/node/eejs/examples/bar.ejs
- src/node/eejs/examples/foo.ejs
- src/node/eejs/index.js
* eejs: Unwrap unnecessarily wrapped line
* eejs: Delete broken example
* eejs: Delete unused functions
* eejs: Inline `begin_capture`, `end_capture`
* eejs: Simplify cache lookup logic
* eejs: Cache the compiled template, not the template string
> Various eejs cleanups

- src/static/js/contentcollector.js
- src/static/js/domline.js
- tests/backend/specs/api/importexport.js
Linting of both files.
Also includes a fix for ``lineAttributes.img`` which erroneously were able to be carried onto the next line...  
**We need a proper fix for this.**  
The bug can be replicated by using API to try and upload an image when image support is enabled via a plugin.  Also can be see on the image support branch.
> lint: contentcollector and domline

- src/node/utils/toolbar.js
Simple bugfix if no buttons are present in toolbar. 
Details: Runtime error occurs with message `Cannot set property 'grouping' of undefined`
> Fixed possible runtime error if no buttons are present - especially read only mode

- doc/api/hooks_client-side.md
- src/node/hooks/express/openapi.js
- src/static/js/ace2_inner.js
- src/static/js/contentcollector.js
- tests/backend/specs/api/characterEncoding.js
- tests/backend/specs/api/importexport.js
- tests/backend/specs/contentcollector.js
* lint: Fix some straightforward ESLint errors
* tests: Re-enable import/export test that is now working
* tests: Delete invalid contentcollector test
* tests: Fix invalid HTML in contentcollector tests
* tests: Delete erroneous `describe()` calls
* tests: Use `assert.deepEqual()` to simplify equality checks
* tests: Replace "expected" with "want", "received" with "got"
* tests: Fix missing call to `done` callback
* openapi: Fix error logging
* contentcollector: Delete unused `domInterface` parameter
* contentcollector: Document the `dom` object
* contentcollector: Factor out call to `.toLowerCase()`
* contentcollector: Fix Element attribute accesses
* contentcollector: Rename `dom` functions for consistency with DOM spec
* contentcollector: Avoid `for..in` iteration of …
> contentcollector fixes

- src/package-lock.json
- src/package.json
There are some problems with nyc:
* The coverage numbers aren't useful in our case because most of the code is executed outside the test process (the test code is mostly API client logic).
* nyc messes with line numbers, which makes it much harder to debug problems.
* We're seeing frequent SIGABRT crashes while nyc is printing the results table. I'm not sure if nyc is the cause of the crashes, or if it's making a race condition worse, or if the crashes have nothing to do with nyc, but we don't lose much by removing it so we might as well see if the crash frequency improves.
Addresses #4684.
> tests: Stop using nyc

- bin/checkAllPads.js
- bin/checkPad.js
- bin/checkPadDeltas.js
- bin/extractPadData.js
- bin/importSqlFile.js
- bin/migrateDirtyDBtoRealDB.js
- bin/rebuildPad.js
- bin/repairPad.js
* bin scripts: compare against null, not undefined
* bin scripts: Use destructuring instead of long condition checks
* bin scripts: Promisify npm.load
* bin scripts: Delete redundant exception log messages
* bin scripts: Promisify db.init and db.close
* bin/rebuildPad.js: Add missing calls to `util.callbackify`
* bin/rebuildPad.js: Fix sequencing of asynchronous functions
* bin/rebuildPad.js: Asyncify
* bin/rebuildPad.js: PadManager must be loaded before Pad
* bin/rebuildPad.js: Close the database when done
* bin/rebuildPad.js: Don't overwrite DB settings
* bin/rebuildPad.js: Fix check for existing rev
> bin scripts: Various fixes and cleanups

- package-lock.json
- src/node/server.js
- src/package-lock.json
- src/package.json
- tests/backend/common.js
I'm dusting off some old commits I had in the works a while ago:
* server: Exit on unhandled Promise rejection
* server: Perform init after adding uncaught exception handler
* server: Refactor `stop()` to avoid no-async-promise-executor lint error
* server: Refine process lifetime management
* server: Remove all other signal listeners
* server: Use wtfnode to log reasons why node isn't exiting
I'm hoping this PR will avoid whatever is causing #4684.
> Rework server shutdown

- package.json
The files in these directories contain test drivers, not tests.
> lint: Use node config for tests/frontend/travis, tests/ratelimit

- src/static/js/linestylefilter.js
- src/static/js/pluginfw/hooks.js
- tests/backend/specs/hooks.js
- tests/backend/specs/webaccess.js
* hooks: Remove unnecessary `callAllStr()` function
* lint: Fix more ESLint errors
* tests: Make the fake webaccess hook registrations look more real
* hooks: Delete unused `bubbleExceptions` setting
* hooks: Don't export `syncMapFirst` or `mapFirst`
* hooks: Rename `args` to `context` for consistency
* hooks: Refine caveat comments about function parameter count
* hooks: Simplify `syncMapFirst` iteration
* hooks: Asyncify `mapFirst`
* hooks: Inline `syncMapFirst()` into `callFirst()` for readability
* hooks: Inline `mapFirst()` into `aCallFirst()` for readability
* hooks: Factor out callback attachment
* hooks: Never pass a falsy error to a callback
* hooks: Factor out value normalization
* hooks: Asyncify `aCallFirst`
* hooks: Inline `aCallFirst()` into …
> hooks.js improvements

- package-lock.json
- src/node/hooks/express/adminplugins.js
- src/node/server.js
- src/package-lock.json
- src/package.json
- src/static/js/pluginfw/plugins.js
- src/static/js/pluginfw/read-installed.js
- src/static/js/pluginfw/shared.js
- src/templates/admin/plugins-info.html
* pluginfw: Call `npm.load()` before using `npm`
* pluginfw: Delete commented-out code
* pluginfw: Return from `findUnmet()` early if not given an object
* pluginfw: Fix state reset logic
* lint: src/static/js/pluginfw/plugins.js
* lint: src/static/js/pluginfw/read-installed.js
* lint: src/static/js/pluginfw/shared.js
* lint: Move functions up to fix more lint errors
* /admin/plugins/info: Move logic to `.js` file
* pluginfw: In-line `formatPluginsWithVersion()`
* pluginfw: Replace `slide.asyncMap()` with `Promise.all()`
* pluginfw: Use `for` loops to improve readability
* pluginfw: Delete unused return value
These changes are to prepare for migrating from `require('npm')` to running the `npm` CLI tool directly.
> Various pluginfw fixes and cleanups

- src/tests/frontend/specs/ordered_list.js
`waitForPromise()` should always be used with `await` (either directly or with a later `await` on the returned Promise). In this case, the condition should be immediately true so `waitForPromise()` is not the right tool here.
> tests: Fix erroneous use of `waitForPromise()` in `ordered_list.js`

- src/node/hooks/express/openapi.js
- src/tests/frontend/travis/runnerBackend.sh
* openapi: Turn down logging verbosity
* Revert "backend tests: change loglevel to WARN (#4514)"
> backend tests: Turn up logging verbosity to INFO

- src/node/server.js
* server: Use a log4js logger object for logging
* server: Simplify gating of state transition waiters
* server: Only pass `err` arg to `exports.exit()`
* server: Fix handling of errors during startup and shutdown
> server: Fix handling of errors during startup and shutdown

- src/static/js/domline.js
- src/tests/frontend/specs/ordered_list.js
#4748 is a bug report where ordered list items were not properly formatted due to a lazy check.  The lazy check was ``x == 1`` and when we linted we changed it to ``x === 1``, the ``1`` was coming from a string check so it was typeOf string which meant when we did a more strict check it never returned true causing line number snot to incremented.
This PR.
* Fixes bug by parsing the string to an integer
* Fixes test by adding a new test which covers this edge case, although I'm not sure why it wasn't failing before on other tests..   we can investigate why once this is merged and we have order restored so can release.
> Fix OL list items not increasing

- CHANGELOG.md
- src/node/hooks/express.js
- src/node/hooks/express/static.js
- src/node/utils/Minify.js
- src/static/js/ace.js
* lint: Replace use of underscore.js with plain ECMAScript
* express: Call expressConfigure, expressCreateServer hooks asynchronously
* ace: Fix EMBEDDED check
* Minify: Move tar processing into a function
* Minify: Move `getTar()` to `static.js`
* static: Asyncify
* Minify: Un-export `requestURI()`
* Minify: Asyncify `requestURI()`
* Minify: Use `Promise.all()` to simplify `requestURIs()`
* Minify: Replace `async.forEach()` with `Promise.all()`
* Minify: Asyncify `getAceFile()`
* Minify: Asyncify `lastModifiedDateOfEverything()`
* Minify: Asyncify `getFile()`
* Minify: Asyncify `statFile()`
* Minify: Asyncify `getFileCompressed()`
* Minify: Don't set cache headers if `statFile()` causes 500
* Minify: Asyncify `minify()`
* Minify: Use `fs.promises`
* Minify: Return …
> Minify: asyncify, plus some fixes

- .github/workflows/backend-tests.yml
- .github/workflows/frontend-tests.yml
- src/node/hooks/express/socketio.js
The initial value was 10k, @Exploder98 rightly pointed out this value is far too low.
@webzwo0i I hope this is still inline with your testing on this issue?
> socketio: include image upload frontend test coverage and increase socketio limit to something workable

- src/node/hooks/express/socketio.js
This change is required for socket.io 3.x because in 3.x `io.sockets.clients()` no longer returns all client Socket objects.
Necessary (but probably not sufficient) before #4740 can be merged.
> socket.io: Manually track client connections/disconnections

- src/tests/backend/common.js
- src/tests/backend/specs/api/api.js
- src/tests/frontend/helper.js
- src/tests/frontend/specs/helper.js
* lint: Delete unnecessary `eslint-disable-line` comment
* tests: Wait for `common.init()` to complete before returning
* tests: Always call backend `common.init()` at startup
* tests: Delete unnecessary `describe()` calls in `api.js`
* tests: Use the supertest agent from `common.js` for `api.js`
* tests: Asyncify tests in `api.js`
* tests: Give `helper.waitFor()` timeout errors a useful stack trace
* tests: Accept async condition functions for `helper.waitFor()`
> tests: Various improvements

- CHANGELOG.md
- src/node/hooks/express.js
- src/tests/frontend/specs/adminsettings.js
It's better to provide a primitive value and let the consumer of the metric do math if desired.
> express: Change `httpUptime` to `httpStartTime`

- src/tests/frontend/lib/mocha.js
- src/tests/frontend/runner.css
The test runner was hiding durations before and presenting broken HTML.
This PR remedies those issues.
Rebase or squash, I'm not fussed but it's clean enough to rebase.
> tests: test runner output HTML and CSS improvements to show duration

- src/node/handler/ImportHandler.js
- src/node/hooks/express/importexport.js
- src/static/js/pad.js
- src/static/js/pad_impexp.js
- src/tests/backend/specs/api/importexportGetPost.js
**Please do not squash merge** because the commits in this PR are intentionally separate:
* import/export: Make sure Express sees async errors
* pad: Delete dead code
* pad_impexp: Delete unnecessary `importFailed` wrapper
* pad_impexp: Invert logic to improve readability
* pad_impexp: Style fixes to improve readability
* pad_impexp: Simplify creation of import failure message
* pad_impexp: Use jQuery to build the import failure popup
* ImportHandler: Delete redundant variable
* ImportHandler: Avoid deprecated `fs.exists()` function
* ImportHandler: Use asynchronous rename instead of `fs.renameSync()`
* ImportHandler: Switch to `fs/promises` API
* ImportHandler: Use `return reject(...)` to avoid double settle
* ImportHandler: Throw Errors, not strings
* ImportHandler: Lint the response …
> import: Ajaxify pad import

- src/node/eejs/index.js
- src/package-lock.json
- src/package.json
This PR works around the breakage that happens if we upgrade to the latest version of EJS, which changes the type of __output from array to string.
> Bugfix for latest version of EJS

- src/node/hooks/express/adminsettings.js
This should match the normal startup procedure a bit more closely.
Fixes #4678.
> /admin/settings: Reload plugins, call `loadSettings` hook on restart

- CHANGELOG.md
- settings.json.docker
- settings.json.template
- src/node/hooks/express/socketio.js
- src/node/utils/Settings.js
By default we limit insertion size to ~10k.
ep_image_upload modifies this value in https://github.com/citizenos/ep_image_upload/commit/aac99c998780f1fd45554e3956e8213dcfee8f94 to a much larger number.
This is a stop gap solution until we chop socket messages up instead of allowing large ones to be sent.
> maxHttpBufferSize as a setting

- src/static/js/ace2_inner.js
I can't see any reason this would be necessary, and it appears to not behave as intended (`scroll.scrollWhenPressArrowKeys()` is not invoked after a continuously held arrow key is finally let up).
> ace2_inner: Delete special arrow key handling

- src/node/utils/run_cmd.js
- src/package-lock.json
- src/package.json
On Windows, npm should be invoked as `npm.cmd`, not `npm`. Use a drop-in replacement for `child_process.spawn()` that does the right thing on Windows.
Fixes bug #4787.
> plugins: Fix "Error: spawn npm ENOENT" error on Windows

- src/bin/plugins/lib/backend-tests.yml
- src/tests/frontend/travis/runnerBackend.sh
`runnerBackend.sh` was deleted in commit 7dae5e3db8b68da09a064f21aa837ccdcdb94b08 but plugins still need it until their GitHub workflow definitions have been updated.
> tests: Restore `runnerBackend.sh`

- Dockerfile
- doc/docker.md
This MR introduces a docker build variable `INSTALL_ABIWORD`. When set
to any value other than `0`, ABIWORD is installed in the resulting
docker container, enabling the possibility to configure ABIWORD in
settings.json.docker or via ENV VAR `ABIWORD` for exporting to
DOC/PDF/ODT.
Documentation is included inline and in the docker markdown file.
> feat(docker): Add build var for optionally installing abiword

- src/static/js/AttributeManager.js
- src/static/js/Changeset.js
- src/static/js/ChangesetUtils.js
- src/static/js/broadcast.js
- src/static/js/changesettracker.js
- src/static/js/collab_client.js
- src/static/js/index.js
- src/static/js/l10n.js
- src/static/js/pad_userlist.js
- src/static/js/security.js
- src/static/js/underscore.js
- src/static/skins/colibris/index.js
- src/static/skins/colibris/pad.js
- src/static/skins/colibris/timeslider.js
- src/static/skins/no-skin/index.js
- src/static/skins/no-skin/pad.js
- src/static/skins/no-skin/timeslider.js
This PR just leaves two more things in the front-end code that I'm too much of a noob to fix.  It would be awesome to see them sent as commits but I also don't mind getting to them when I have time.
I tried to keep my commit history as clean as possible but I wont be offended if this is squashed.
There are a few places that ``self`` is used and I lacked the patience to resolve it at that point as I wanted the lions share of the linting done so we can come back at a future date and remove the ``self`` and lines I have been forced to add eslint disables for.
Tests are passing.
> lint: vast majority of the remaining frontend code. - READY FOR REVIEW

- src/node/utils/ImportEtherpad.js
- src/static/js/contentcollector.js
Add functionality to console.warn when a plugin is missing.  This will help admins know when people are trying to use plugins that are missing.  Resolves https://github.com/ether/etherpad-lite/issues/4730
> pluginfw: Warn plugins on missing plugin

- src/node/utils/Settings.js
- src/static/js/pluginfw/client_plugins.js
- src/static/js/pluginfw/installer.js
- src/templates/pad.html
- src/templates/timeslider.html
see https://github.com/ether/etherpad-lite/pull/4761#issuecomment-779016536
Sets the randomVersionString earlier when delivering pad.html/timeslider.html and prevents jquery from adding a query parameter to circumvent the cache.
> fix for caching plugin-definitions

- .github/workflows/backend-tests.yml
- .github/workflows/frontend-admin-tests.yml
- .github/workflows/frontend-tests.yml
- .github/workflows/load-test.yml
- .travis.yml
- README.md
- doc/plugins.md
- src/bin/plugins/lib/README.md
- src/static/js/pluginfw/installer.js
- src/tests/backend/assert-legacy.js
- src/tests/backend/specs/caching_middleware.js
- src/tests/backend/specs/hooks.js
- src/tests/frontend/travis/remote_runner.js
We should run our tests with all node versions that we currently support. This PR uses v10/12/14/15 for our backend tests. Maybe adding different versions to the admin tests would be clever too, as they use npm
> tests: Try all supported node versions during backend tests

- src/static/js/caretPosition.js
* caretPosition: Invert condition in `getPosition()` for readability
* caretPosition: Delete unused var in `getPosition()`
* caretPosition: Delete no-op `Range.detach()` call
* caretPosition: Delete pointless logic in `getPosition()`
* caretPosition: Clarify comment in `getPosition()`
> caretPosition: Simplify `getPosition()`

- src/tests/frontend/specs/bold.js
- src/tests/frontend/specs/embed_value.js
- src/tests/frontend/travis/remote_runner.js
Firefox 52 has issues with rendering SVG animations which caused random tests to fail.  Less than 2% of total Firefox users now use Firefox 52 so we're safe to drop testing for it.
> tests: Use more modern relevant Firefox version in Sauce Labs

- .github/workflows/windows-zip.yml
npm might do something different on Windows when setting up the executables in `src/node_modules/.bin`.
> CI: Use Windows to build the Windows zip

- README.md
I adjusted the installation instructions for Etherpad on Windows in the Readme, so that it recommends installation via the prebuilt package and warns about potential issues with symlinks while performing a manual installation. See #4848.
> docs: Update Installation Instructions for Windows

- .github/workflows/windows-installer.yml
This PR introduces CI builds of a windows installer(using NSIS) .
It builds an executable that installs Etherpad and runs it.
There are obvious steps to make once this has been merged. But I'd suggest on each release we include both the .zip and the .exe and allow users to have a portable zip or an installed executable.
https://github.com/ether/etherpad_nsis
This was a relatively rushed project (4 hours) and I didn't want to spend any more time on it so it will need a foster parent to maintain it :)
props to @joncloud for https://github.com/joncloud/makensis-action-test and the nsis team that while have a horrible UX make relatively easy to use and rapid tools.
Note for review: I'm using linux to build the windows executable, this may need to be reviewed and we might want to switch to …
> Windows CI Installer

- src/node/utils/Minify.js
- src/node/utils/tar.json
- src/static/tests.html
* /static/tests.html: Fix `jquery.js` path
* Minify: Also serve `jquery.js` from old path for compatibility
* Minify: Improve pathname sanitization
* Minify: Consistently use `path.join()` to build pathnames
I'm hoping this will help with #4800.
> Minifiy: Pathname calculation refinements

- src/templates/pad.html
This was long due and also makes the crashes in https://github.com/ether/etherpad-lite/issues/4800 look strange (as no error is written, but instead padutils fails)
The padutils stuff in pad.html never actually worked, as there is no global variable padutils even after requiring padutils. Instead simply whitelist some characters and display the error message.
> avoid pad_utils in pad.html

- src/node/utils/Minify.js
- src/node/utils/tar.json
Backward compatibility for plugins that were written when underscore lived at src/static/js/underscore.js.
> reversecompat: underscore

- src/node/handler/PadMessageHandler.js
* PadMessageHandler: Delete unnecessary use of `Promise.then()`
* PadMessageHandler: Fix fetching of socket.io Sockets for a pad
Fixes #4701.
Fixes #4708.
cc @webzwo0i
> PadMessageHandler: Fix fetching of socket.io Sockets for a pad

- src/node/hooks/express/static.js
- src/node/utils/caching_middleware.js
- src/tests/backend/specs/caching_middleware.js
* lint: `src/node/utils/caching_middleware.js`
* lint: Move up `respond()` in `caching_middleware.js`
* CachingMiddleware: Switch to ES6 class syntax
* CachingMiddleware: Asyncify
* tests: Refine CachingMiddleware tests
> CachingMiddleware: Lint, asyncify, and refine tests

- src/node/utils/tar.json
- src/static/js/ace.js
removes 4 307s redirections.
It also ensures that there is no request without a `versionString` made from the inner iframe, because it explicitly downloads the needed files via script tag now. (Before the change, the files were loaded on demand via require-kernel which did not append the `versionString` which could have resulted in problems during upgrades.)
> performance: Page load improvements by way of removal of unnecessary 307 redirections

- CHANGELOG.md
- src/static/js/ace2_inner.js
This fixes a bug that was introduced in commit c38c34bef47a74467394797b34165641a87ac620.
Fixes #4885.
> Ace2Inner: Fix missing spread operator on `args`

- .github/workflows/load-test.yml
- src/tests/frontend/travis/runnerLoadTest.sh
Designed to catch issues that only appear X duration.
We might want to introduce some "chaos" into the load test tool or do we think this will be sufficient?
> tests: run a long test

- src/node/utils/Minify.js
- src/static/js/ace.js
- src/static/js/ace2_inner.js
- src/static/js/pad_editor.js
* ace: Delete unused `Ace2Editor.getFrame()` method
* ace: Delete ignored class attribute
* ace: Format script strings for readability
* ace: Lint and simplify script strings
* ace: Delete unnecessary IIFE
* ace: Delete unused `clientVars.disableCustomScriptsAndStyles`
* ace: Factor out duplicated `$$INCLUDE_CSS` code
* ace: Simplify the `aceEditorCSS` hook map function
* ace: Use absolute URLs when building iframes
* ace: Pass objects to Ace2Inner via function args
* ace: Simplify passing of `editorInfo`
* ace: Asyncify `Ace2Editor.init()`
* ace: Build the outer and inner iframes programmatically
* ace: Debug logging
* ace: Delete all `$$INCLUDE_CSS` logic
cc @webzwo0i
> ace: Refactor to avoid `document.write()`, remove EMBEDED logic

- src/node/utils/Minify.js
- src/node/utils/MinifyWorker.js
Constructing a relative pathname on Windows is problematic because the two absolute pathnames might be on different drives (or UNC paths). Use `path.resolve()` instead of `path.join()` where appropriate to avoid the need to construct a relative path.
Fixes #4800.
> Minify: Avoid `path.relative()`

- src/node/utils/ImportEtherpad.js
- src/static/js/contentcollector.js
Currently Etherpad warns about too many elements that are actually supported (spans, strong etc).
This PR puts the arrays separate from blockElems (I could use a ... to create but it's nice to have an array that can be copy/pasted between the two files without concern).
The outcome of this PR is that admins will have less warnings in their console and the only warnings they should see will be the ones for the plugins they actually need.
If anything todays bug report (of a lot of noise) is a good indicator that this functionality is working as expected
> Import plugins less warny

- src/node/hooks/express/adminplugins.js
- src/node/server.js
- src/static/js/pluginfw/plugins.js
- src/static/js/pluginfw/shared.js
There are two main benefits:
* HTML is no longer printed in the startup debug logs.
* `require()` is no longer called on client-side files. This eliminates "Failed to load \<file\> for \<plugin\>: ReferenceError: window is not defined" errors when users visit `/admin/plugins/info`.
Fixes #3245.
> pluginfw: Improve rendering of hook list

- .github/workflows/major-version-git-pull-update.yml
In response to cypress-eslint breaking changes I thought I'd put some CI testing for if a PR might break automated upgrading.
Matrix usage is probably overkill.  Cypress might be too but gives us decent coverage.
Needs squashing.
> tests: CI of updating from master > this commit.

- src/tests/frontend/cypress/integration/test.js
Minification happens after the initial visit and request to pages.
It could be that I can use timeout on the iframe elements but I'd rather just have a known static wait here for test stability temporarily.
> tests: Allow time for minification to complete

- src/static/css/iframe_editor.css
- src/static/css/pad/layout.css
- src/static/js/ace.js
- src/static/skins/no-skin/pad.css
- src/templates/pad.html
* CSS: Fix class name for outer iframe `<html>` tag
* CSS: Use `auto` for iframe body height
* CSS: Delete bogus `<link>` tag
* CSS: Add comment to `no-skin/pad.css` to silence warning
> Various CSS fixes

- src/node/hooks/express/webaccess.js
cc @rhansen 
I automatically extracted the routes and I think those should not create a session.
Left out are `/admin.*`, `/ro/.*`, `/p/.*` and `/` for the moment. I think `/` should also not create a session though.
> add more endpoints that do not need a session

- src/static/js/ace.js
This makes the code easier to read and it silences Chrome's `document.write()` warning: https://developers.google.com/web/updates/2016/08/removing-document-write
This is a redo of commit a17f9bf3cfc745a44d0e57b77912e346ffd3ce1c, which was reverted in commit 912f0f195faf19b11a5db928b3846fbb09388004 due to a CSS bug. That CSS bug was fixed in PR #4920.
cc @webzwo0i
> ace: Build the outer and inner iframes programmatically

- src/bin/safeRun.sh
This fixes a copy+paste bug introduced in commit 8b28e007842efefccf852a55f783761f86dc6090 (v1.8.8).
Fixes #4930.
cc @ldidry
> bin/safeRun.sh: Fix `try: not found` bug

- src/static/js/Changeset.js
better error message in cases like https://github.com/ether/etherpad-lite/issues/4937
> arrow functions dont have arguments

- src/node/handler/ExportHandler.js
- src/node/handler/ImportHandler.js
- src/node/hooks/express/importexport.js
- src/node/utils/Abiword.js
- src/node/utils/LibreOffice.js
- src/tests/backend/specs/api/importexport.js
- src/tests/backend/specs/export.js
* tests: Increase import/export test timeouts
* tests: Promisify import/export tests
* tests: Use `assert` to simplify import/export tests
* import/export: Delete unnecessary comments
* Abiword: Reset stdout buffer when starting abiword
* ExportHandler: Replace unnecessary exception with `return`
* import/export: Use Error objects for errors, not strings
* ExportHandler: Pass the error unmodified
* import/export: Spelling fix: "convertor" -> "converter"
* import/export: On export error return 500 instead of crashing
* Abiword: Don't call the callback if null
* Abiword: Reduce log spam
* Abiword: Fix logging of conversion failure
* Abiword: Use the async-provided callback to signal errors
* LibreOffice: Add missing `fileExtension` property on intermediate step
* …
> import/export: Improve error handling, promisify

- src/static/js/ace.js
This seems to fix "null is not an object (evaluating 'browserSheet.insertRule')" errors on Safari.
cc @webzwo0i
> ace: Use iframe `srcdoc` property to refine frame load logic

- src/tests/frontend/specs/inner_height.js
Small test case for inner height regression, ie clientHeight should be identical to scrollHeight on pads with few lines, but should be less than scrollHeight on pads with lots of lines.
This is useful as a guard against a regression where scrolling, line number links (and maybe other things that depend on [getInnerHeight](https://github.com/ether/etherpad-lite/blob/develop/src/static/js/ace2_inner.js#L3646) or `clientHeight`) stopped working. The solution to this problem was https://github.com/ether/etherpad-lite/commit/cb9f6d67768da5c87651c03bcc24e019574121aa
See https://github.com/ether/etherpad-lite/pull/4954#issuecomment-802954752 for details why this test should be extended to check if the editor "has grown" when the number of pad lines reach below the viewport area and why I …
> add test for wrong clientHeight

- src/node/utils/Abiword.js
- src/node/utils/LibreOffice.js
Follow-up to PR #4957:
* Abiword: Avoid calling `stdoutCallback` multiple times
* LibreOffice: Remove unnecessary callbackification
> import/export: Minor fixes

- CHANGELOG.md
misleading entry. It is not done yet, ie sessions are still created
> fix wrong changelog entry

- src/static/js/Changeset.js
Reusing the same op object for each iteration can result in very weird behaviors because previously yielded op objects will get a surprise mutation.
It is unclear why the code was written to reuse the same object. There was no comment, nor is there a commit message providing rationale (it has behaved this way since the very first commit). Perhaps the objects were reused to improve performance (fewer object allocations that need to be garbage collected). I do expect this change to reduce performance somewhat, but not enough to warrant reverting this commit.
> Changeset: Return a new op object by default when iterating

- src/static/js/ace.js
- src/static/js/ace2_inner.js
- src/static/js/collab_client.js
- src/tests/frontend/helper/multipleUsers.js
- src/tests/frontend/index.html
- src/tests/frontend/specs/collab_client.js
* collab_client: Factor out duplicate `ACCEPT_COMMIT` code
* collab_client: Delete unused `caughtErrors`
* collab_client: Convert `state` var to `committing` bool
* collab_client: Use `Date.now()` instead of casting a Date object
* collab_client: Redo server message queueing
* collab_client: Delete unused `NO_COMMIT_PENDING` handling
* tests: Add regression tests for character composition race
This should fix #4978. Also see PR #4979, which is a different approach  to fix the same problem.
@ingoncalves What are your thoughts about this approach?
> collab_client: Fix race condition with character composition

- src/node/hooks/express/specialpages.js
See https://github.com/ether/etherpad-lite/issues/4976#issuecomment-809200250
> Don't make browsers fail on sync-xhr until require-kernel is dropped

- doc/api/changeset_library.md
- doc/assets/style.css
- src/bin/doc/html.js
Some links in the docs were broken as there were 2 different implementations generating ID slugs - homebrew and the Marked one. Using Marked all over.
Example broken link in docs: https://etherpad.org/doc/v1.8.12/#index_server_side - does not take to correct section.
> DOCS: Fix TOC links. Add basic styling for tables in the docs. Add "Resources / further reading" section to the Changeset documentation. 

- doc/api/hooks_client-side.md
- src/static/js/chat.js
* chat: Allow `chatNewMessage` hook to modify more values
* chat: Use jQuery to build the chat message DOM object
* chat: Ensure that `ctx.text` is interpreted as HTML
This is a follow-up to PR #4992.
cc @webzwo0i
> chat: Safer construction of chat message DOM object

- doc/api/hooks_server-side.md
- src/node/db/ReadOnlyManager.js
- src/node/db/SecurityManager.js
- src/node/handler/PadMessageHandler.js
- src/node/hooks/express/specialpages.js
- src/node/hooks/express/webaccess.js
- src/node/padaccess.js
- src/tests/backend/specs/api/importexportGetPost.js
- src/tests/backend/specs/socketio.js
Before this PR, webaccess.checkAccess saved the authorization in
user.padAuthorizations[padId] with padId being the read-only pad ID,
however later stages, e.g. in PadMessageHandler, use the real pad ID for
access checks. This led to authorization being denied.
This commit fixes it by only storing and comparing the real pad IDs and
not read-only pad IDs.
This fixes test case "authn user readonly pad -> 200, ok" (which is also introduced in this PR) in
src/tests/backend/specs/socketio.js.
---
Note that I haven't really understood the design principles behind the authorization architecture. In particular, the `padAuthorizations` being part of the user session seems really weird to me and is the root cause behind the bug being fixed by this PR.
> Fix read only pad access with authentication

- settings.json.docker
- settings.json.template
- src/node/server.js
- src/node/utils/Settings.js
Consumes a lot of CPU (because of https://github.com/myndzi/wtfnode/blob/master/index.js#L123) so it's better to enable it on purpose in production.
> fix(perf): Disable wtfnode dump by default

- src/node/utils/Minify.js
* Minify: Refactor `requestURI()` for readability
* Minify: Treat `ENOTDIR` like `ENOENT` when statting a file
* Minify: Avoid crash due to unhandled Promise rejection if stat fails
> Minify: Improve handling of stat errors

- src/node/db/API.js
- src/node/handler/PadMessageHandler.js
* PadMessageHandler: Register `activePads` metric only once
* PadMessageHandler: Improve documentation of `sessioninfos`
* PadMessageHandler: Avoid unnecessary property lookups
* PadMessageHandler: Assume sessioninfo stays valid during client update
* PadMessageHandler: Parallelize client updates
* PadMessageHandler: Use a `Map` for `sessioninfos`
> PadMessageHandler: Various minor cleanups

- src/static/js/AttributeManager.js
- src/static/js/Changeset.js
- src/static/js/ace2_inner.js
- src/static/js/skiplist.js
- src/tests/frontend/index.html
- src/tests/frontend/runner.js
- src/tests/frontend/specs/skiplist.js
* editor: Delete commented-out code
* editor: Delete unused `PROFILER` code
* skiplist: Delete unused methods
* AttributeManager: Simplify logic
* AttributeManager: Add sanity checks
* editor: Improve documentation comments
* skiplist: Use ES6 class syntax
* skiplist: Remove unnecessary `newKey` arg from `_insertKeyAtPoint()`
* skiplist: Save entry in `_insertKeyAtPoint()`
* skiplist: Move point creation to a new `Point` class
* skiplist: Convert point operations into `Point` methods
* skiplist: Define a new `Node` class
* skiplist: Move `propagateWidthChange()` to `Node` class
* skiplist: Sanity check inserted entries
* skiplist: Convert `_keyToNodeMap` to a `Map` object
* skiplist: Use `Map.size` to get number of nodes
* tests: Add tests for `SkipList.atOffset()`
> skiplist: Readability improvements and sanity checks

- src/static/js/caretPosition.js
as per https://developer.mozilla.org/en-US/docs/Web/API/Window/getSelection browser either return `null` or set selection.type to `None` when the loaded iframe is hidden
> caretPosition: fix loading when iframe is hidden

- src/node/db/API.js
- src/node/handler/PadMessageHandler.js
Switching to a Map broke ep_webrtc and maybe other plugins.
This reverts commit eeead4643792d2e7a10aef935112bab8e620375c.
> Revert "PadMessageHandler: Use a `Map` for `sessioninfos`"

- src/node/hooks/express/tests.js
- src/node/utils/Minify.js
- src/node/utils/sanitizePathname.js
- src/package-lock.json
- src/package.json
- src/tests/backend/specs/sanitizePathname.js
- src/tests/frontend/helper.js
- src/tests/frontend/index.html
- src/tests/frontend/runner.css
- src/tests/frontend/runner.js
* sanitizePathname: Move to separate module to facilitate reuse
* tests: Use `async`/`await` instead of returning Promises
* tests: Avoid `.then()` inside `async` functions
* tests: Use `fs.promises` instead of wrapping with `util.promisify`
* tests: Switch to promisified `readFile`
* tests: URL decode test spec pathnames
* tests: Only wrap `*.js` files in `describe()`
* tests: Combine frontend test file handlers
* tests: Reuse `sanitizePathname` when serving frontend specs
* tests: Simplify iteration over frontend test specs
* tests: Rename `specs_list` to `frontendTestSpecs`
* tests: Use `window.foo` instead of `var foo`
* tests: Pretty-print `frontendTestSpecs.js` to make troubleshooting easier
* tests: Unexport unnecessarily exported functions
* tests: Remove …
> tests: Numerous frontend test improvements

- CHANGELOG.md
- settings.json.docker
- settings.json.template
- src/node/utils/Settings.js
- src/tests/backend/specs/settings.js
- src/tests/backend/specs/settings.json
* Settings: Support null and undefined env var substitutions
* Docker: Explicitly default env var substitutions to null
* Settings: Deprecate null as the default default value
* Docker: If `DB_*` env var is unset, remove the corresponding setting
* tests: Add tests for `settings.json` parsing
Fixes #5048
@JustAnotherArchivist: Would you test this PR to see if it fixes the bug you reported?
> Settings: Support `null` and `undefined` environment var substitutions

- src/package-lock.json
- src/package.json
- src/tests/frontend/travis/remote_runner.js
* tests: Avoid jQuery when reading Mocha output
* tests: Migrate from `wd` to `selenium-webdriver`
* tests: Also pass `--use-fake-ui-for-media-stream` to Chrome
* tests: Configure Firefox to use fake webcam
Fixes #4344
cc @packardone
> tests: Configure Firefox to use fake webcam

- src/static/js/pad_utils.js
* Display error name in the gritter box
* Move error message to the top of the gritter box
> Improve client-side error display

- src/tests/frontend/runner.js
* tests: Wrap more Mocha functions
* tests: Don't attempt to wrap non-functions
Fixes #5063
> tests: Wrap more Mocha functions

- src/bin/updatePlugins.sh
* cd to top-level Etherpad directory is now more robust.
* Only attempt to update packages whose names begin with `ep_`.
* Don't create `package-lock.json`.
* Improve logging.
* Improve error handling.
> bin/updatePlugins.sh: Many refinements

- src/static/js/ace.js
Using `.innerHTML` to create a `<script>` element does create a DOM node, but the script is not actually executed. Fortunately, creating a DocumentFragment does cause the script to execute.
Fixes ether/ep_prompt_for_name#3
> Pad: Fix `<script>` elements in `aceInitInnerdocbodyHead` hook

- Dockerfile
* Docker: Don't create `package-lock.json` when installing plugins
* Docker: Nuke all of `~/.npm` after installing packages
* Docker: Install plugins before core deps
* Docker: Combine `abiword` and `libreoffice` install steps
* Docker: Use `apt-get` instead of `apt`
* Docker: Set `DEBIAN_FRONTEND=noninteractive` when running `apt-get`
* Docker: Pass `--no-install-recommends` to `apt-get intall`
* Docker: Install `git` and `ca-certificates` packages
@Evadon-Nathan would you please test this to see if it fixes plugin install and uninstall for you?
Note that unless you bind mount `${EP_DIR}/node_modules` to something on your host you will lose all changes to your installed plugins whenever you restart the container.
Fixes #5069
> Docker: Multiple improvements

- src/static/css/iframe_editor.css
- src/static/js/ace2_inner.js
This prevents the padding from clashing with plugins that use the `aceSetAuthorStyle` hook.
> CSS: Move author color padding to `setAuthorStyle()`

- .github/stale.yml
I feel like this is a good idea. We can easily filter feature requests in the issue tab and it's good to see open feature requests, that aren't implemented yet, but seem to be a good idea.
Stale should close issues that aren't labeled (at least as bug or feature request) when they didn't have activity for a longer time.
> stop closing feature requests by stale bot

- doc/docker.md
The configuration option `DB_FILENAME` is also used in conjunction with the `sqlite` ueberdb2 adapter.
> doc/docker.md - add sqlite to DB_FILENAME

- src/static/css/pad/popup.css
Underlining was removed for unknown reasons by commit d872b42e31ec4698d9a9e0c3bc04e4f215ae7473.
> CSS: Underline links in error dialogs

- src/static/js/pad_utils.js
- src/tests/frontend/specs/urls_become_clickable.js
This reverts commit 9022877cc60efb694578506771c294c25793415e.
Fixes #5095
cc @disturbio
cc @xavidotron in case there are any objections to undoing PR #2970
> Add support for square brackets in URLs

- src/static/js/pad.js
When settings.useMonospaceFontGlobal is set to `true`, it sets the default
font to 'monospace'. This font seems to have been removed in
a5164dad430d99f1fc0a7fd045c37ce56e70efa6.
This commit sets the default font to "RobotoMono" which is a valid
option.
Tested in a Docker environment, setting `PAD_OPTIONS_USE_MONOSPACE_FONT`
to `true`
> Fix settings.useMonospaceFontGlobal

- src/static/css/pad/chat.css
- src/static/js/chat.js
- src/templates/pad.html
- src/tests/frontend/lib/sendkeys.js
- src/tests/frontend/specs/change_user_color.js
- src/tests/frontend/specs/chat.js
* tests: sendkeys: Fix `{enter}` keypress event
* Chat: Use a `<textarea>` for message input
* Chat: Display whitespace in chat messages
* Chat: Use `KeyboardEvent.key` instead of deprecated `.which`
* Chat: Allow Shift-Enter to insert a newline
cc @packardone
> Chat: Input text area improvements

- src/tests/frontend/helper.js
- src/tests/frontend/helper/multipleUsers.js
- src/tests/frontend/index.html
- src/tests/frontend/runner.js
My idea in https://github.com/ether/etherpad-lite/pull/5103 didn't work, but I have some new insights: I can reproduce this reliably in Chromium when I disable cache and use a remote server, so there is some latency between requests.
sendkeys depends on jQuery to be loaded first. When cache is enabled, jQuery is downloaded via https://github.com/ether/etherpad-lite/blob/develop/src/tests/frontend/index.html#L18 and all later requests are cached, so when issuing the get requests with Promise.all, jQuery will immediately load and sendkeys will work properly.
However, when in a non-cached, higher latency scenario, jQuery will almost always be received after sendkeys was received, because the size of the jQuery file is larger (uncompressed 257kb vs 19kb), so sendkeys gets executed before …
> tests: fix unaccessible sendkeys

- src/node/handler/PadMessageHandler.js
It is possible for the stats to be read before the `expressCreateServer` hook is called (in particular: when there is an
error during startup), which is when the `socketio` variable is set. Check for non-null `socketio` before attempting to count the number of socket.io connections.
> PadMessageHandler: Fix stats null dereference

- src/static/empty.html
- src/static/js/ace.js
- src/static/js/ace2_inner.js
Using srcdoc, especially with multiple nested iframes, seems to be
problematic when using `self` in CSP policies.
Fixes #4975
> ace.js: Don't use srcdoc when creating iframes

- src/static/js/ace.js
- src/static/js/domline.js
ace.js: removed the role 'application' from innerDocument.body. JAWS do not read any text from the edit lines if this role is set.
domline.createDomLine: to give JAWS the ability to read the lines correctly, it is required to set the attribute 'aria-live' to 'assertive'.
> Accessibility fix for JAWS screen readers

- doc/api/editbar.md
- src/static/js/pad_editbar.js
- src/static/js/pad_modals.js
* pad_editbar: Use `this` instead of `self`
* pad_editbar: Use arrow functions for callbacks, IIFEs
* pad_editbar: Fix invalid use of `this`
* pad_editbar: Convert `bodyKeyEvent()` into a method
* pad_editbar: Simplify iteration
* pad_editbar: Convert `registerDefaultCommands()` into a method
* pad_editbar: Remove unnecessary `syncAnimationFn` variable
* pad_editbar: Move `syncAnimation` out of `padeditbar` IIFE
* pad_editbar: Move `dropdowns` initialization to constructor
* pad_editbar: Move `commands` up for readability
* pad_editbar: Delete unnecessary `returned` variable
* pad_editbar: Don't pass a callback to `toggleDropDown()`
* pad_editbar: Call the callback after all work is done
* pad_editbar: Always call the callback
* pad_editbar: Call the callback …
> pad_editbar: Various cleanups

- src/static/js/ace.js
- src/static/js/ace2_inner.js
* ace2_inner: Formatting improvements
* ace2_inner: Delete redundant class assignment
* ace2_inner: Replace `initLineNumbers()` with an IIFE
* ace2_inner: Combine declaration and initialization
* ace2_inner: Build `sidedivinner` programmatically
* ace2_inner: Move `sidedivinner` creation to ace.js
* ace2_inner: Use destructuring assignment to simplify
* ace2_inner: Consistently use `outerWin` and `outerDoc`
* ace2_inner: Simplify document body selection
* ace2_inner: Delete unnecessary `doc` and `root` variables
* ace2_inner: Delete unnecessary `container` variable
* ace2_inner: Delete unnecessary `innerdocbody` variable
* ace2_inner: Add line number divs directly, not via fragment
* ace2_inner: Replace `lineNumbersShown` with number of children
* ace2_inner: Factor out …
> ace2_inner: Various cleanups

- src/bin/installDeps.sh
* installDeps.sh: Simplify log message
* installDeps.sh: Wrap long lines
* installDeps.sh: Quote underquoted expansions
* installDeps.sh: Ensure that `ep_etherpad-lite` is a directory. This should avoid errors like #5165, or at least make them easier to troubleshoot.
* installDeps.sh: Handle errors
* installDeps.sh: Don't nuke `src/node_modules` on error
cc @sennewood
> installDeps.sh improvements

- src/node/handler/SocketIORouter.js
- src/tests/backend/specs/socketio.js
* SocketIORouter: Rename variables to improve readability
* SocketIORouter: Logging improvements
* SocketIORouter: Add ability to unregister handler
* SocketIORouter: Add unit tests
* SocketIORouter: Don't crash if message handler throws
* SocketIORouter: Add acknowledgement support
There are two main goals of this PR:
1. Stop the server from crashing if a socket.io message handler throws. This will make it easier to resolve the feedback for PR #5106 (cc @webzwo0i).
2. Make it possible for a future PR to improve UX when the client sends a bad message.
> SocketIORouter: Add acknowledgement support

- doc/docker.md
- settings.json.docker
Unlike all other (simple) settings, these two were previously not available as environment variables. This change makes it possible to modify them without having to rebuild the image (cf. 85adaa44).
> Docker: Expose socketIo.maxHttpBufferSize and dumpOnUncleanExit settings as environment variables

- src/tests/frontend/helper.js
This should make it easier to avoid race conditions.
> tests: Wait for pad init before returning from `helper.aNewPad()`

- .github/workflows/backend-tests.yml
- src/bin/installOnWindows.bat
Changing directory on [`installOnWindows.bat`](https://github.com/ether/etherpad-lite/blob/develop/src/bin/installOnWindows.bat) file in lines [4](https://github.com/ether/etherpad-lite/blob/4d2839457a903d210e9790e43e0b353fa9e1eb6c/src/bin/installOnWindows.bat#L4) and [19](https://github.com/ether/etherpad-lite/blob/4d2839457a903d210e9790e43e0b353fa9e1eb6c/src/bin/installOnWindows.bat#L19) are wrong!
**[Reason/Solution]:** we need to go back one more directory to reach etherpad-lite root.
**Also,**
It's better to change the Github action flow in [`backend-tests.yml`](https://github.com/ether/etherpad-lite/blob/develop/.github/workflows/backend-tests.yml) on lines [119 ](https://github.com/ether/etherpad-lite/blob/4d2839457a903d210e9790e43e0b353fa9e1eb6c/.github/workflows/backend-tests.yml# …
> Fix #5200, Windows Installer and back-end tests  

- .github/workflows/frontend-admin-tests.yml
- src/tests/frontend/specs/adminsettings.js
- src/tests/frontend/specs/adminupdateplugins.js
The adminsettings.js test was flaky. This PR:
- increases maxHttpBufferSize so that settings.json fits into socketio messages (I'm not sure how it's possible the test was green sometimes)
- avoids comparing the timestamp/clock of the SauceLabs runner and Etherpad instance. When `Date.now()` on SL is in the past (compared to the Etherpad server), tests no longer fail.
- adds a method to log messages to the DOM which are printed when the test suite finishes. It's mainly for debugging but I thought it could be helpful to others. Most Chrome and Firefox versions on SL have a console.json file attached to the test run, but Safari does not.
> Fix adminsettings test

- src/static/js/Changeset.js
These are the documentation changes from PR #2911.
cc @webzwo0i
> Changeset: Add documentation for `textLinesMutator()`

- .github/PULL_REQUEST_TEMPLATE.md
Some changes to PULL_REQUEST_TEMPLATE.md:
1. Begin with CONTRIBUTING.md 
2. Refer to the tests as "front-end" and "back-end" like CONTRIBUTING.md does
3. Remove http://karma-runner.github.io/4.0/dev/git-commit-msg.html , which is about a convention that etherpad contributors don't follow, and also is about commit message rather than PR message.
> Clarify instructions in PULL_REQUEST_TEMPLATE.md

- CHANGELOG.md
- doc/api/hooks_client-side.md
- doc/api/hooks_server-side.md
- src/node/db/API.js
- src/node/db/Pad.js
- src/node/handler/PadMessageHandler.js
- src/node/utils/tar.json
- src/static/css/pad/chat.css
- src/static/js/ChatMessage.js
- src/static/js/chat.js
- src/static/js/collab_client.js
- src/static/js/pad.js
- src/templates/pad.html
- src/tests/backend/common.js
- src/tests/backend/specs/chat.js
- src/tests/backend/specs/socketio.js
- src/tests/frontend/helper.js
- src/tests/frontend/helper/methods.js
- src/tests/frontend/runner.js
- src/tests/frontend/specs/chat_hooks.js
Multiple commits, do not squash.
Plugins can now access the raw chat message object (to set and get custom metadata) and can completely override the rendering of any chat message. This can be used to add user joined/left notices or IRC-like "/me \<message\>" commands.
cc @packardone
> Chat hook improvements

- src/node/handler/PadMessageHandler.js
> PadMessageHandler: Don't fire `userLeave` if user hasn't joined yet

- src/node/db/SessionManager.js
This bug was introduced in #4667 where `==` was changed to `===`, resulting in a type comparison. However, the type of `err` is `CustomError`, not `string`. The comparison is therefore always false, resulting in the API error "sessionId does not exist" when `listSessionsWithDBKey` is called and some sessions do not exist instead of simply returning null for these sessions as was previously the case.
> Fix comparison between `CustomError` and `string`

- .gitignore
- CHANGELOG.md
- doc/api/hooks_server-side.md
- src/bin/plugins/lib/gitignore
- src/static/js/pluginfw/plugins.js
These files cause problems with Docker images and read-only directories/mounts, and they have dubious value (any install-time setup should instead be done at startup).
Fixes #2683
> plugins: Don't create `.ep_initialized` files

- CHANGELOG.md
- src/node/utils/padDiff.js
- src/static/js/Changeset.js
- src/static/js/contentcollector.js
- src/static/js/linestylefilter.js
- src/tests/frontend/specs/easysync.js
This is the first batch of commits from PR #5233.
@webzwo0i This is likely to conflict with #5253.
> Changeset: Various minor cleanups and fixes

- CHANGELOG.md
- src/static/js/Changeset.js
- src/static/js/pad_utils.js
This is the next batch of commits from PR #5233.
cc @webzwo0i
> Changeset: Move `SmartOpAssembler.appendOpWithText()` to a standalone function

- CHANGELOG.md
- doc/api/hooks_server-side.md
- src/node/handler/PadMessageHandler.js
- src/node/utils/ExportHelper.js
- src/node/utils/ExportHtml.js
- src/node/utils/ExportTxt.js
- src/node/utils/padDiff.js
- src/node/utils/tar.json
- src/static/js/AttributeManager.js
- src/static/js/AttributeMap.js
- src/static/js/Changeset.js
- src/static/js/ace2_inner.js
- src/static/js/attributes.js
- src/static/js/broadcast.js
- src/static/js/changesettracker.js
- src/static/js/contentcollector.js
- src/static/js/linestylefilter.js
- src/tests/backend/specs/contentcollector.js
- src/tests/frontend/specs/AttributeMap.js
- src/tests/frontend/specs/attributes.js
The existing code to manipulate attributes was awkward. This PR introduces a new AttributeMap class that subclasses Map and has easy conversion to/from attribute strings.
I think we should bump the Etherpad minor version to 1.9.0 so that plugins can easily depend on the new class.
This PR is some yak shaving required to move import processing to a worker thread. (cc @packardone)
> New attributes processing library

- CHANGELOG.md
- src/node/utils/padDiff.js
- src/static/js/Changeset.js
- src/static/js/ace2_inner.js
- src/static/js/contentcollector.js
- src/static/js/linestylefilter.js
- src/tests/frontend/specs/easysync.js
Turn some functions that return objects into real ES6 `class`es to improve readability.
This is the next batch of commits from PR #5233.
> Changeset: `class`-ify some objects to improve readability

- CHANGELOG.md
- doc/api/hooks_server-side.md
- src/node/db/API.js
- src/node/handler/PadMessageHandler.js
- src/node/utils/ExportHelper.js
- src/node/utils/ExportHtml.js
- src/node/utils/ExportTxt.js
- src/node/utils/ImportHtml.js
- src/node/utils/padDiff.js
- src/static/js/AttributeManager.js
- src/static/js/Changeset.js
- src/static/js/ace2_inner.js
- src/static/js/broadcast.js
- src/static/js/changesettracker.js
- src/static/js/linestylefilter.js
- src/tests/frontend/specs/easysync.js
New `deserializeOps()` generator function to replace the `OpIter` class. This makes it possible to use `for..of` iteration to iterate over operations.
This is the next batch from PR #5233.
> Changeset: Improved operation iteration

- src/node/db/GroupManager.js
- src/node/db/SessionManager.js
Currently, when a session is deleted, the session itself is removed before the session entries are removed from `group2sessions` and `author2sessions`. This leads to an unclean state when the application is killed or an error occurs after the session was deleted but before all references are deleted because sessions that do not exist are still referenced. This pull request changes the order to delete the references first.
> Delete session after corresponding group2session and author2session entries

- CHANGELOG.md
- src/node/db/GroupManager.js
- src/tests/backend/specs/api/sessionsAndGroups.js
Thanks @timonegk for pointing out the oversight in https://github.com/ether/etherpad-lite/pull/5276#issuecomment-975600565.
> GroupManager: Clean up any mappings when deleting a group

- Dockerfile
The Nodejs 14 slim image has quite a few vulnerabilities, and I have tested the latest slim image. It works just fine.
> Update to the latest slim package

- CHANGELOG.md
- src/node/db/API.js
- src/tests/backend/specs/api/pad.js
This is PR #5190 rebased and squashed. (I tried to reopen that PR but GitHub won't let you reopen a PR once its branch has been rebased, even if you undo the change by force-pushing the old revision.)
Fixes #5073
> API: `getText` with old revision should only return text, not atext

- CHANGELOG.md
- src/node/db/API.js
- src/node/db/Pad.js
- src/node/handler/PadMessageHandler.js
- src/node/utils/ImportHtml.js
- src/static/js/collab_client.js
- src/tests/backend/common.js
- src/tests/backend/specs/api/pad.js
- src/tests/backend/specs/messages.js
Also:
* Accept `USER_CHANGES` retransmissions. (Currently the client doesn't ever retransmit, but accepting retransmissions removes an awkward exception in the server code and opens the door to future protocol improvements.)
* Fix race conditions in the `setText`, `appendText`, `restoreRevision` HTTP API functions.
> Pad: Don't create no-op revisions

- CHANGELOG.md
- src/node/db/API.js
- src/node/db/Pad.js
- src/node/db/ReadOnlyManager.js
- src/node/db/SessionStore.js
- src/node/hooks/express/padurlsanitize.js
The relevant issue is https://github.com/ether/etherpad-lite/issues/5005
I still see crashes when configuring a READ LOCK. At one point we may need to shutdown Etherpad when there are lots of failing queries, however I think we need to be more robust.
The scenarios are probably one of either:
- read queries for large data or that scan the whole table can timeout
- all pool connection are used with long queries, when new queries arrived, so the latter timeout at one point
When loading pads when a READ LOCK is active, I see crashes due to:
- globalAuthor can't be set in `createAuthor`
- pad state can't be read (don't know which caller)
Theoretically any query can randomly fail (when running with READ or WRITE LOCK). In practice I assume that when all connections are used and long queries …
> await more queries / handle Inactivity timeouts

- CHANGELOG.md
- doc/api/hooks_server-side.md
- src/node/handler/PadMessageHandler.js
- src/node/hooks/express/webaccess.js
- src/package-lock.json
- src/package.json
- src/tests/backend/common.js
- src/tests/backend/specs/messages.js
> PadMessageHandler: Allow `handleMessageSecurity` to grant one-time write access

- src/templates/pad.html
- src/templates/timeslider.html
Prevent "TypeError: Cannot read properties of null (reading 'sheet')" exception leading to a crash
Google chrome can translate `<style type="text/css" title="dynamicsyntax"></style>` title attribute. So https://github.com/ether/etherpad-lite/blob/develop/src/static/js/ace.js#L310 will throw.
It also disables pad content translation.
> Prevent pad translation and crash

- src/static/js/Changeset.js
- src/tests/frontend/easysync-helper.js
- src/tests/frontend/specs/easysync-assembler.js
- src/tests/frontend/specs/easysync-mutations.js
Was part of https://github.com/ether/etherpad-lite/pull/5253
I removed the two problematic smartOpAssembler tests
> Enhance easysync tests and some Changeset.js docs

- src/node/hooks/express.js
- src/node/hooks/express/webaccess.js
- src/tests/backend/specs/webaccess.js
* Move the `cookie-parser` middleware up so that `expressPreSession` hook functions can enjoy easy cookie access.
* Move the `preAuthorize` hook after the `express-session` middleware. Rationale: The `ep_openid_connect` plugin needs access to session state before authorization checks are made (to securely redirect the user back to the start page when authentication completes). Now that the `expressPreSession` hook exists, the rationale for moving `preAuthorize` before the `express-session` middleware is gone. This change undoes the following commits: bf35dcfc5096a77b19bc2b50261b34c98fce7011, 0b1ec20c5c061c340db2e7feac2229d79d960296, 30544b564eb7658c6830ba38a31af856fd6509fc.
> express: Reorder middleware

- .github/dependabot.yml
I already use Dependabot for many projects. With Dependabot it is relatively easy to stay up to date with the dependencies and packages used. Instead of always checking for updates manually, you can e.g. use the dependabot.yml configuration to tell Dependabot to check the project once a week for new releases of the npm packages that are used. If there are new updates, a new pull request is automatically created for them.
Since this procedure takes at least some work off my hands over at my projects, I wanted to ask if you would be up to using it for npm as well.
> Add docker & npm ecosystem to dependabot

- CHANGELOG.md
- doc/api/hooks_server-side.md
- src/static/js/pluginfw/plugins.js
This makes it possible for plugins to stop assuming that log4js is available at `ep_etherpad-lite/node_modules/log4js`.
> plugins: Give each plugin a plugin-specific logger object

- .github/workflows/docker.yml
Add github action tasks to build for `amd64` and `arm64` platform.
`arm64` is now widely used: Raspberry PI, Docker for Mac (on Apple Silicon) and AWS Graviton.
Tested a docker building locally using the Dockerfile on an `arm64` system without issue.
Don't expect any issues with the same on Github Actions
> Docker: use buildx to build amd64 and arm64 images

- CHANGELOG.md
- src/node/db/DB.js
- src/package-lock.json
- src/package.json
> Bump ueberdb2 to 2.2.4, clean up DB initialization

- .github/workflows/frontend-admin-tests.yml
- .github/workflows/frontend-tests.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
> GitHub Workflows security hardening

- src/node/hooks/i18n.js
Fix for https://github.com/ether/etherpad-lite/issues/5628
> Fix: Plugin locales should overwrite core's locales

- Dockerfile
Installs java deps when `libreoffice` install is selected.
> fix(Docker): also install libreoffice deps.

- src/static/js/ace2_inner.js
It would be more natural to add the new code inside the code that handles ctrl-backspace, but then this couldn't delete multiple "tabs" (which are actually 4 spaces).
It would be nice to have this feature on Windows too, but I don't know what keybinding it should have.  Maybe ctrl-shift-backspace?
Fixes https://github.com/ether/etherpad-lite/issues/440
> feat(ace2_inner.js): Add keybinding meta-backspace to delete to beginning of line

- src/tests/backend/specs/api/chat.js
- src/tests/backend/specs/api/instance.js
- src/tests/backend/specs/api/pad.js
See https://github.com/ether/etherpad-lite/pull/5805
cc @SamTV12345
> Fix append revision test

- src/node/server.js
Now `exports.start()` is called only for cli: `if (require.main === module) exports.start();`
To run etherpad-lite also with Passenger it is needed to call `exports.start();` too.
fixes #5683
> Call exports.start() for Phusion Passenger

- Dockerfile
cc @rdelaage
on alpine, plugin command (used in src/node/utils/Abiword.js at line 31) is not installed by defaut. Add this plugin when installing abiword.
> fix abiword not working in container

- src/static/js/pad_editbar.js
When Etherpad is hosted on a different domain and the iframe is violating the same-origin policy, trying to close Import/Export window via Escape key results in an error:
This PR fixes that by removing the reference to `parent.parent` when accessing the jQuery ($).
> Don't access jQuery through `parent.parent`

- Dockerfile
This PR adds ability to specify configuration file as a docker build argument for custom build.
Usage example:
```sh
docker build --build-arg SETTINGS=./settings.json.docker.development .
```
This is useful when there's a need to have different configuration files, for example to specify plugin settings for different environments.
> Docker: Add ability to specify configuration file as a build arg

- Dockerfile
> fix: Always install npm@6 for correct package-lock.json version.

- README.md
This is a followup to #6067.
This corrects the install instructions for Node.js. Node.js 14 is EOL for very long now and the current version of Etherpad does not even work with it.
As per the [release notes](https://github.com/ether/etherpad-lite/releases/tag/v1.9.5) and the [requirements](https://github.com/ether/etherpad-lite#requirements) in the README, at least Node.js 18.x is required and Node.js 20 is recommended.
This also reduces the maintenance effort, as duplicating these third-party install instructions does not provide additional value.
> Correct Node.js install instructions

- src/node/hooks/express/specialpages.js
- src/tests/backend/specs/favicon.js
This pull request fixes the favicon issues related to urls. If a url is entered in the settings.json etherpad will redirect the favicon request to the url in settings.json. That way we can load images from any source in the internet and are not dependent from rebuilding a docker image.
Closes #3392
> Fixed favicon not being loaded from url.

- src/bin/repairPad.js
The current version of the script may take hours for some pads. This PR adds some output so that the user can have an idea of the progress. 
The new output looks like this:
```console
$ node bin/repairPad2.js some-pad
WARNING: This script must not be used while etherpad is running!
[2024-01-24T15:45:53.790] [INFO] settings - All relative paths will be interpreted relative to the identified Etherpad base dir: /opt/etherpad-lite
[2024-01-24T15:45:53.806] [INFO] settings - settings loaded from: /opt/etherpad-lite/settings.json
[2024-01-24T15:45:53.807] [INFO] settings - No credentials file found in /opt/etherpad-lite/credentials.json. Ignoring.
[2024-01-24T15:45:53.807] [INFO] settings - Using skin "colibris" in dir: /opt/etherpad-lite/src/static/skins/colibris
[2024-01-24T15:45:53.808] …
```
> Make repairPad.js more verbose

- doc/api/hooks_server-side.adoc
This PR fixes an incorrect link to 'known error identifiers' for `import` server side hook in documentation.
> Fix wrong link to error identifiers in documentation

- src/static/js/vendors/html10n.js
fixes #6129
Bug: #6129
Bug: #6144
Follows-Up: #3882
Change-Id: Ie3fcec84948fde36fa12448d5eabaf05f79f1283
> #6144 | Fix Accept-Language detection

- src/static/js/pluginfw/installer.js
The output of `pnpm ls` command is different to the `npm ls` and forces live-plugin-manager to install all plugins from node_modules.
Here's an example of how the output looks like for pnpm:
```
ep_user_displayname: {
from: 'ep_user_displayname',
version: '1.0.4',
resolved: 'https://registry.npmjs.org/ep_user_displayname/-/ep_user_displayname-1.0.4.tgz',
description: "Etherpad plugin to set each user's display name via config or authentication plugin.",
license: 'Apache-2.0',
author: { name: 'Richard Hansen', email: 'rhansen@rhansen.org' },
homepage: 'https://github.com/ether/ep_user_displayname#readme',
repository: 'git+https://github.com/ether/ep_user_displayname.git',
path: '/opt/etherpad-lite/node_modules/.pnpm/ep_user_displayname@1.0.4_ep_etherpad-lite@src/node_modules/ep_user_display …
```
> Don't install all dependencies from node_modules

- src/static/js/pluginfw/LinkInstaller.ts
Due to an issue in the configuration of the live plugin manager subdependencies were not installed in some cases. This fixes the issue that the manager assumes a package is already installed while it is not. Thanks to @dhalenok for the fix.
> Added hostrequire undefined to always install all subdependencies.

- Dockerfile
> fix crash in docker build as src/pnpm-lock.yaml does not exists anymore

- Dockerfile
- bin/installPlugins.ts
Due to new changes in the version 2.0, it's no longer possible to specify local plugins when building a Docker image.
In my testing, executing `pnpm run install-plugins` (one for remote and one for local plugins via `--path`) made it so only the plugins specified in the latest command were loaded.
This PR changes that, so you can specify both remote and local plugins in one command: `pnpm run install-plugins ep_openid_connect --path ../ep_my_local_plugin`. It should still be possible to specify only remote or local plugins.
In addition, this PR introduces a new Dockerfile argument called `ETHERPAD_LOCAL_PLUGINS`, value of which gets passed to `install-plugins` script.
There is, however, one thing left to do, which is copying the plugins to the docker image. IIRC, before v.2.0 the root …
> Allow providing local plugins to Docker image

- src/node/utils/Settings.ts
- src/node/utils/SettingsTree.ts
- src/tests/backend/specs/settings.ts
This pull requests adds the possibility to add arbitrary settings as environment variables. This enables adding the configuration of plugins via environment variables. 
To add an environment variable you need to prefix it with EP and two underscores. Generally two underscores separate an environment variable.
As an example we want to add ep_prefer_color_scheme with dark mode setting enabled.
For this we would need to add the following in settings.json
```javascript
const nightColors = {
toolbar: 'dark',
background: 'super-dark',
editor: 'dark',
}
```
We require 3 env variables, toolbar, background and editor. The following set this configuration
```
EP__nightColors__toolbar="dark"
EP__nightColors__background="super-dark"
EP__nightColors__editor="dark"
```
Closes #6195
> Added env.

- bin/installPlugins.ts
You can now install specific versions of a plugin using: `pnpm run install-plugins ep_headings2@0.2.61`
> Added support for installing a specific version of a plugin.

- admin/src/pages/LoginScreen.tsx
Found a typo in LoginScreen where is says Passwort instead of Password.
> LoginScreen.tsx -> Passwort -> Password

- doc/docker.md
This is required to make installed plugins persistent over container recreation.
Also remove deprecated yaml version, as discussed in Discord.
> Documentation fix: Add var volume to Docker Compose file

- admin/src/pages/HomePage.tsx
- src/node/server.ts
- src/node/utils/UpdateCheck.ts
You can now use http_proxy and https_proxy and specify an axios proxy server that is used for retrieving Etherpad's latest version and also the plugins list
> Added proxy support for axios.

- pnpm-lock.yaml
- src/package.json
This version updates several super outdated dependencies, see https://github.com/davideicardi/live-plugin-manager/pull/88.
:hammer_and_pick: with :heart: by [Siemens](https://opensource.siemens.com/)
> chore: bump live-plugin-manager to 0.20.0

- doc/api/http_api.md
- settings.json.docker
- settings.json.template
- src/node/security/OAuth2Provider.ts
- src/node/utils/Settings.ts
Is it possible to add expiration date that is greater than 3600s?
> chore: add docs how to obtain bearer token

- src/ep.json
- src/node/hooks/express/pwa.ts
- src/templates/export_html.html
- src/templates/index.html
- src/templates/javascript.html
- src/templates/pad.html
- src/templates/timeslider.html
This pr adds progressive web app support to Etherpad. 
A progressive web app enables the Etherpad user to install a given Etherpad instance onto his desktop. That way users don't need to remember the instance url and just need to search their programs for Etherpad.
> Added Progressive Web App support for Etherpad

- bin/plugins.ts
- package.json
- pnpm-lock.yaml
- src/package.json
- src/static/js/pluginfw/installer.ts
- src/static/js/pluginfw/plugins.js
To fix #6330, upgrade the live-plugin-manager.
The live-plugin-manager has been updated to allow plug-ins to depend on several different versions of packages.
Dependency packages are now managed by directory names that include version numbers, and symlinks to them are placed in the `plugin_packages` directory.
Ref: https://github.com/davideicardi/live-plugin-manager/pull/90
Therefore, the conversion below (`fs.realpath`) would cause unexpected symlink resolution, I fixed that.
```
plugin.realPath = await fs.realpath(plugin.location);
```
> Upgrade live-plugin-manager to 1.0.0

- bin/plugins.ts
Fix #6419 - Run `checkForMigration` to load the list of plugins in `src/plugin_packages` before performing plugin removal and installation.
> Fix initialization of plugins

- src/static/skins/colibris/src/layout.css
- src/templates/pad.html
This patches a bug where users cannot scroll a document on iOS, because iOS does not allow iframes to be scrolled.
See https://davidwalsh.name/scroll-iframes-ios for details.
This is purely a cosmetic change, so a frontend test is not applicable for it.
Tested on iOS 12
> Fix document not scrolling in iOS (all browsers)

- admin/src/index.css
- admin/src/pages/SettingsPage.tsx
- admin/src/utils/utils.ts
- package.json
- src/package.json
- src/tests/backend/specs/admin_utils.ts
Add new function to remove the comments from the settings file.
It reduces the size of the payload when we save on the admin page `.../admin/settings`
____
I was considering changing the font to `font-family: monospace;` see the before and after, 
I think it looks better that way, if we all agree we can change it.
> Clean comments

- admin/src/pages/HomePage.tsx
- src/node/hooks/express/adminplugins.ts
Fixes #6440
Refactor the plugin search behavior in the `HomePage.tsx` instead of using the toast with the message:
`Error retrieving plugins`
we will now show a much softer message in the table letting the user that no plugins are found, it also uses the correct language messages instead of the hardcoded english in the toast  
https://github.com/ether/etherpad-lite/assets/545474/c166d9f2-e690-4454-b55a-9ac372e9534e
____
Add 'results:searcherror' event to truly show errors in the search
Also add logger to the adminPlugins
> Move away from using toast in the plugin search

- src/static/js/ace2_inner.js
Fixes #4456
In case of a ctrl click what we can do to open in the background is keep the focus in the current one:
`if (evt.ctrlKey) window.focus();`
Here is a short video showing my testing on Chrome
https://github.com/ether/etherpad-lite/assets/545474/fdea80e8-8dbe-401c-b80e-9d501f924cb4
> On Ctrl+Click bring the window back to focus

- Dockerfile
When checked out as a git submodule, `.git` is not a folder containing `refs` and `HEAD`, but a file pointing to the parent repositories' git metadata.
This commit fixes the failing Docker build by making the file references copied from the `.git` folder glob patterns, which don't fail when no source file can be found.
I could not resist to fix some linter errors in the `Dockerfile` along the way.
> fix #6495 failing Docker build when checked out as git submodule

- src/package.json
- src/static/js/pad.js
- src/static/js/socketio.js
Fixed silent disconnect of pad
- Errors were calling explicit socket.connect() even if this is now handled by socket io event loop
- Deprecated APIs: Some events like reconnect, reconnect_attempt were moved to the manager
> fix: Silent disconnect of pad

- Dockerfile
This intends to fix a bug introduced recently by a typo in 550a29f3e62712f856899a082000481a24a57e6b
> Fix #6538 (admin page broken)

- src/node/hooks/express/specialpages.ts
Fixes #6620 - Fixed relative path specifiers for template entrypoints.
The path prefixes have been modified for each page as follows:
- index(`/`) ... Modified to specify `. /` as the path prefix because the script appears to be in the same directory.
- pad(`/p/padname`) ... Modified to specify `../` as the path prefix because the script appears to be in the parent directory.
- history(`/p/padname/timeslider`) ... Modified to specify `../../` as the path prefix because the script appears to be in the parent's parent directory.
> Fix relative paths for template enrtypoints

- admin/src/App.tsx
- admin/src/pages/HomePage.tsx
- admin/src/store/store.ts
- src/node/hooks/express/adminplugins.ts
This pull request addresses the issue that plugins can't be updated. This is because at first the setInterval function is not triggered resulting in nothing happening. You'd have to wait 60 minutes until the update button is shown.
> fix(admin): Fixed updating plugins

- README.md
Update documentation.
- Added simple update process for Etherpad
Issue : https://github.com/ether/etherpad-lite/issues/6728#
> Simple Readme documentation

- Dockerfile
- 
This pull request includes updates to the `Dockerfile` to introduce new build arguments for Etherpad plugins. These changes aim to enhance the flexibility and configurability of the Docker build process.
Enhancements to Docker build process:
* Added new build arguments `ETHERPAD_PLUGINS`, `ETHERPAD_LOCAL_PLUGINS`, and `ETHERPAD_GITHUB_PLUGINS` to the development stage.
* Added new build arguments `ETHERPAD_PLUGINS`, `ETHERPAD_LOCAL_PLUGINS`, and `ETHERPAD_GITHUB_PLUGINS` to the production stage.Declared ARG ETHERPAD_PLUGINS in build, development, and production stages to ensure it is recognized and used correctly throughout the build process.
- This resolves the issue of the ETHERPAD_PLUGINS argument appearing empty during the build process.
> fix: Ensure ETHERPAD_PLUGINS ARG is recognized in all stages

- Dockerfile
- bin/installLocalPlugins.sh
- local_plugins/.gitignore
The background for this pull request is contained in #6912.
This pull request does 3 things:
1. creates a directory `local_plugins` in the root repository, with a `.gitignore` file that ignores all of its contents.
2. creates a script `bin/installLocalPlugins.sh`.
3. modifies the `Dockerfile` to change the installation process of local plugins:
* copies the contents of the `local_plugins` directory into the container (if the directory does not exist, it skips it).
* defines a new build arg variable `ETHERPAD_LOCAL_PLUGINS_ENV`
* install the local plugins with the script `bin/installLocalPlugins.sh` (which uses `pnpm install -w "local_plugins/${plugin}/"`)
(**note:** I am not sure that the `pnpm -w install` command is the best way to install a plugin, I am not an expert node user.)
To …
> Fix installation of local plugins (fixes #6912)

- .github/workflows/docker.yml
> Adapted docker.yml

- src/node/hooks/express/webaccess.ts
Basically the same thing as I reported in https://github.com/ether/etherpad-lite/issues/6893, except it's the timeslider. Since it's not loaded when accessing a pad, I missed it in my initial report.
Also I'm not sure but looking at the `src/node/hook/express/specialpages.ts` maybe a entry should be added for indexBootstrap ? I wasn't able to find where it is used so that's why I didn't include it in this PR.
> fix(frontend): add timesliderBootstrap to static resources

- src/static/js/ace2_inner.ts
On some keyboard layouts (eg. pl) the right alt key (a.k.a. Alt Gr) is used in combination with letters to type special characters, eg. AltGr-C makes a 'ć' on a pl keyboard layout.
At least on Firefox on macOS it seems like events that would otherwise result in a special character still get passed to keydown and friends. This means that if etherpad handles alt-c, it might swallow someone's intent to type in 'ć' and instead open up the chat window.
This could arguably be a bug in Firefox or macOS, as the same doesn't happen in Firefox on Linux/X11. But before I bring the discussion to a wider audience I'd like to at least make the issue go away at etherpad level.
> Do not respond to right alt (Alt Gr) keyboard events.

- Dockerfile
We should use the latest LTS version of node instead of the newest version.
To also get rid of messages like those:
```
etherpad  | [2025-06-28T09:32:09.729] [WARN] settings - oidc-provider WARNING: Unsupported runtime. Use Node.js v22.x LTS, or a later LTS release.
```
> use node lts docker image instead of newest version

- src/static/js/pad_editor.ts
> After delete the user will now redirected to home page

- src/node/utils/Settings.ts
- src/static/skins/no-skin/index.css
- src/static/skins/no-skin/index.js
> chore: fixed git determination and fixed no skin css issues

- .github/workflows/release.yml
Potential fix for [https://github.com/ether/etherpad-lite/security/code-scanning/107](https://github.com/ether/etherpad-lite/security/code-scanning/107)
To fix the problem, explicitly set the `permissions` key in your GitHub Actions workflow. This can be placed at the workflow root (applies to all jobs), or at the job level if different jobs need different scopes (not the case here: there is only one job). The minimal permissions for most CI/CD jobs are `contents: read`, which blocks write and admin access by default but allows the workflow to read the repo contents. If the workflow requires more privileges (e.g., to create releases, push tags, comment on issues or PRs), then those should be added explicitly, but from the code provided it seems only read access is needed for GITHUB_TOKEN. …
> Potential fix for code scanning alert no. 107: Workflow does not contain permissions

- bin/plugins.ts
With previous code, "pnpm run plugins i ep_xxx" is working correctly, but "pnpm run plugins install ep_xxx" does not work correctly (since var `registryPlugins` is empty)
Either "pnpm run plugins install ep_xxx" should be disallowed (by removing `case "install"`) or this fix should be applied.
> fix "pnpm run plugins install ep_xxx"

- admin/src/components/IconButton.tsx
- admin/src/index.css
- admin/src/pages/PadPage.tsx
- src/locales/de.json
- src/node/hooks/express/adminsettings.ts
> chore: added possibility to create pads via admin menu

- admin/package.json
- admin/public/brand.svg
- admin/src/pages/ShoutPage.tsx
- admin/src/utils/LoadingScreen.tsx
- admin/vite.config.ts
- doc/package.json
- pnpm-lock.yaml
- ui/package.json
- ui/vite.config.ts
We only use rolldown which has freebsd support so you can also build Etherpad on freebsd x86. No more manual patching is required from now on.
> chore: use only rolldown for building
