- tests/frontend/specs/importexport.js
should fix https://github.com/ether/etherpad-lite/issues/2431
> fix importexport-tests

- src/static/js/contentcollector.js
frontend and backend tests pass
> fix for uls without class

- bin/installDeps.sh
> check for io.js

- src/static/js/admin/plugins.js
- Prevents a page reload when pressing enter on the admin plugin page
- Prevents dublicates in search results on plugin page
> Plugin page improvements

- src/static/js/pluginfw/installer.js
The file on http://static.etherpad.org/plugins.json will be updated every our
> Change domain for plugins.json request

- src/static/js/timeslider.js
This fix is due to the timeslider not working if the base URL is not document root.
> Timeslider proxy fix

- src/node/db/API.js
- src/node/handler/ImportHandler.js
- src/node/utils/ImportHtml.js
- tests/backend/specs/api/pad.js
for posterity..  Follow up of https://github.com/ether/etherpad-lite/pull/2403
> I need to do some more work on this at some point..  Leaving here

- src/locales/en.json
- src/static/css/pad.css
- src/static/js/chat.js
- src/static/js/pad.js
- src/templates/pad.html
Adds new functionality that should be in core.
To test
1. Go into a pad
2. Click Settings
3. Click "Show Chat and Users"
It will need some polish but anyone can do that, the basic functionality is in..
Maybe cc @0ip for the polish
> Show users and Chat at the same time

- CONTRIBUTING.md
How to create an issue and which information should be given
@JohnMcLear as you pointed me to the external source, i fixed you CONTRIBUTING.md :smile: cu
> Add: How to create an issue

- src/static/js/ace2_inner.js
> Return true from handleCut function

- src/node/utils/ExportEtherpad.js
> oops, fix export with wildcards

- src/static/js/contentcollector.js
> chrome list handling fix for #2412

- settings.json.template
- src/node/utils/Settings.js
For https://github.com/ether/etherpad-lite/issues/2575
> pass error messages to pad text if shown during startup

- settings.json.template
- src/node/utils/Settings.js
The new logic will force a user to enter a sessionKey or will automatically generate one.
> Move sessionKey setting from settings.json to SESSIONKEY.txt

- src/node/utils/Minify.js
in relation to 9d4e5f6e35153129377206ef545d4965afae627d
> dont allow directory traversal #2

- src/static/css/pad.css
I am really sorry that this gets "fixed" rather late, while at the same time, looking almost like a joke or not worthwile. Yet, it was bothering me too much in order to leave it as it is, when I noticed it.
I hope, I can contribute something more meaningful the next time ;)
> Fix popup border border

- src/static/js/ace2_inner.js
- src/static/js/chat.js
- src/static/js/collab_client.js
Should solve https://github.com/ether/etherpad-lite/issues/2634
> Iframe issues

- src/node/utils/toolbar.js
> Do not extend Array.prototype

- src/node/utils/Settings.js
> Fix link to etherpad-lite on GitHub

- src/static/js/pad.js
> Fix broken switchToPad method

- src/node/db/API.js
- src/node/handler/PadMessageHandler.js
> Fix API call appendChatMessage to send new message to all connected clients

- doc/api/http_api.md
- src/node/db/API.js
Add missing API function to docs
> Add appendChatMessage API to docs

- src/static/css/timeslider.css
> Timeslider: Fix "Return to pad" button

- src/node/db/API.js
Since @Gared seems to agree, I'm proposing this to fix #2751.
> Fix off-by-one: The chatHead is in fact a valid message index.

- bin/installDeps.sh
> Support version 4 of node.js

- src/node/hooks/express/padurlsanitize.js
> Fix decode error if pad name contains special characters and is sanitized

- README.md
> Pedantic Space

- src/node/handler/PadMessageHandler.js
- src/node/hooks/express/importexport.js
- src/node/utils/Settings.js
- src/static/js/pad_impexp.js
This is an initial pull request for #2858.
As this is my first PR for etherpad-lite core, I would appreciate any feedback.
> Check for SOffice before removing export links

- src/static/js/collab_client.js
- src/static/js/pad_userlist.js
pad_userlist.js:
* BUGFIX: users() returning duplicates on several calls. 
* BUGFIX: ``handleClientMessage_USER`` to contain user info.
* FEATURE: usersOnline() returns only online users. Useful when one wants to implement it's own online users list.
> pad_userlist.js: BUGFIX: users() returning duplicates on several calls. FEATURE: usersOnline() returns only online users

- src/static/js/ace2_inner.js
> Editor List Fix for 2844 and 2812

- src/node/hooks/express/specialpages.js
> Set language cookie on initial load Issue #2882

- src/static/js/pad.js
> Timeslider Not Translated Issue 2885

- src/static/css/iframe_editor.css
CSS default colors for Firefox Issue #2853
> Css default colors Issue 2853

- bin/installDeps.sh
- Check if version of node is higher than 4
- Remove support for io.js
> Improve node version check

- bin/buildForWindows.sh
- Update node to version 4.4.0
- Create temp folder dynamically
> Update windows build

- src/templates/timeslider.html
- tests/frontend/runner.js
> Fix document.domain error in frontend tests

- tests/backend/specs/api/sessionsAndGroups.js
Fixes https://github.com/ether/etherpad-lite/issues/2951.
> Fix useless comparison in sussonsAndGroups test.

- bin/run.sh
> Fix error if whitespace in etherpad path

- src/node/hooks/i18n.js
- src/node/utils/caching_middleware.js
> Use fs.statSync instead of fs.existsSync (deprecated)

- bin/migrateDirtyDBtoRealDB.js
> Fix module paths for db migration script

- settings.json.template
- src/node/hooks/express/adminsettings.js
- src/node/utils/Settings.js
- src/static/css/admin.css
- src/static/js/admin/settings.js
- src/templates/admin/settings.html
Deactivate settings.json in Admin dashboard.
I have added an option in the setttings.json "showSettingsInAdminPage" : true /*default option is true*/
to show/hide the settings.json in admin page
Let me know if this is fine.
> Issue #2960 - deactivate settings.json

- src/node/hooks/i18n.js
- src/node/utils/caching_middleware.js
- src/node/utils/path_exists.js
Fixes #3002 
Migrated check to separate file
> Fixed path check

- settings.json.template
Also fixed some errant EOL whitespace.
> Fix value to be valid JSON.

- bin/installDeps.sh
Otherwise anyone can MITM the connection and add rogue code there.
You should be more careful with downloading things from remote servers.
> Download JQuery over HTTPS

- settings.json.template
- src/static/js/admin/plugins.js
- src/static/js/pad_utils.js
- src/templates/pad.html
The correct spelling is occurred. See
http://www.gingersoftware.com/english-online/spelling-book/misspelling/occurred-occured-ocurred
or other dictionary search results.
> Correct the spelling of occured to occurred

- src/package.json
- src/static/js/pad.js
> Updated option parameters for socket.io to work with latest version

- src/package.json
- src/static/js/pluginfw/plugins.js
> Updated npm to 4.0.2 and removed recursive searching for ep-plugins

- src/node/handler/ExportHandler.js
> Fixed crash on invalid export url

- src/node/utils/Minify.js
This PR fixes the issue #3081.
> Fix minification of JS files

- doc/api/editbar.md
- doc/api/editorInfo.md
- doc/api/hooks_server-side.md
- doc/database.md
- doc/localization.md
Also includes a few fixes for run-ons, some grammar corrections, and some whitespace cleanups.
> Docs: Lots of spelling fixes

- tests/frontend/travis/sauce_tunnel.sh
Could not dowload `Sauce-Connect-latest.zip` anymore, need to change to
new version of SauceConnect.
> Fix connection to sauce labs

- settings.json.template
- src/locales/en.json
- src/node/handler/PadMessageHandler.js
- src/node/utils/Settings.js
- src/static/css/pad.css
- src/static/js/pad_automatic_reconnect.js
- src/static/js/pad_modals.js
- src/templates/pad.html
- tests/frontend/specs/automatic_reconnect.js
When user is disconnected and button "Force reconnect" is displayed, provide a way to reconnect automatically, after some seconds.
- time to wait until reconnection is defined on `settings.json` (`automaticReconnectionTimeout`);
- provide button to cancel automatic reconnection if user does not want to reconnect to server;
- only force reconnection when it is possible to establish a connection between client and server (avoid reconnecting when there is no network, for example);
> Feature: automatic force reconnect

- src/node/db/SecurityManager.js
> Fix a typo in SessionManager

- src/locales/en.json
Going through translatewiki.net for this case would be very hard, I hope a PR is ok.
> Fix AbiWord wikilink and capitalization

- src/node/handler/ImportHandler.js
This is a fix for the issue - #2864
Which is import failure of PDF after importing a text file
> FIX-2864: Add useAbiword flag

- src/static/js/html10n.js
Last update was from 2014.
Fix #3244.
> [feat] Update l10n lib

- src/static/js/html10n.js
This reverts commit 6bcaa00a4ba70320a390457c90dbf699d0e4a4b9.
There were some changes made on Etherpad copy of the file, we need to merge them with the up-to-date file on https://github.com/marcelklehr/html10n.js.
> Revert "[feat] Update l10n lib (#3248)"

- .gitignore
- CONTRIBUTING.md
- Makefile
- README.md
- bin/buildDebian.sh
- bin/checkPad.js
- bin/cleanRun.sh
- bin/createRelease.sh
- bin/debugRun.sh
- bin/deletePad.js
- bin/doc/json.js
- bin/extractPadData.js
- bin/importSqlFile.js
- bin/installDeps.sh
- bin/installOnWindows.bat
- bin/repairPad.js
- bin/run.sh
- bin/safeRun.sh
- doc/api/changeset_library.md
- doc/api/embed_parameters.md
- doc/api/hooks_server-side.md
- doc/api/http_api.md
- doc/api/pluginfw.md
- doc/documentation.md
- doc/easysync/easysync-full-description.tex
- doc/localization.md
- doc/plugins.md
Here are some typos, tabs, etc. in the bin folder, I'll do other folders when this gets merged. After that hopefully something more substantial :)
> Typos and other minor fixes

- src/static/js/AttributeManager.js
- src/static/js/ace2_inner.js
- tests/frontend/specs/select_formatting_buttons.js
- tests/frontend/specs/styling_buttons.js
Now when the caret or selection is in a text with formatting, we select the style button applied.
> Select formatting button on selection

- src/node/hooks/express/apicalls.js
- src/package.json
> better sanitize jsonp

- src/static/js/pad_utils.js
> better sanitize window location in error messages

- src/node/hooks/express/apicalls.js
> Fix jsonp checking

- bin/installOnWindows.bat
fix provide by skupfer from github.
It fix the installOnWindows.bat problem
> FIX the installOnWindows Error

- src/templates/admin/plugins-info.html
> Correctly display plugin list in troubleshooting tab

- CONTRIBUTING.md
- bin/backendTests.sh
- src/package.json
- tests/README.md
> Backend tests rework

- src/node/handler/ImportHandler.js
Currently, you have to use Abiword to convert odt, pdf and doc files to be able to import those files.
This add soffice as convertor too.
Replace https://github.com/ether/etherpad-lite/pull/3339 (I can't update that PR anymore).
> Allow to import files using soffice

- src/node/utils/AbsolutePaths.js
A Windows manual install has the same directory layout of a normal Unix one (e.g. the nice symlink `node_modules/ep_etherpad-lite` -> `../src`).
Only when running from the pre-built Windows package the directory layout is different (e.g. `src` is physically copied into `node_modules/ep_etherpad-lite`).
The previous version of the code wrongly assumed that all Windows installs would be run from the pre-built pakage.
In this version the path search is the same on all platform. If it fails, and we are on Windows, there is a fallback for the specific case of the pre-built package.
Fixes #3550
> AbsolutePaths.js: do not break when running as a Windows manual install

- src/static/js/pluginfw/hooks.js
- src/static/skins/colibris/src/components/chat.css
- src/static/skins/colibris/src/components/form.css
- src/static/skins/colibris/src/components/users.css
- src/static/skins/colibris/src/layout.css
- src/static/skins/colibris/src/plugins/font_color.css
- src/templates/pad.html
> Colibris chat improvements

- docker/Dockerfile
Fix "one" -> "done", and add missing closing parenthesis.
> Fix typos in docker/Dockerfile

- src/static/skins/colibris/index.css
> Fix chrome alignment

- doc/docker.md
Supersedes https://github.com/ether/etherpad-lite/pull/3631
> docker: Add Run with volume example

- src/static/skins/colibris/src/components/table-of-content.css
Hello, a fix asked by @revast here : https://github.com/seballot/ep_embedded_hyperlinks2/issues/1
> skin colibris: Fix table of content with ep_resizable_bar

- doc/api/hooks_client-side.md
- src/static/js/chat.js
...when new chat message arrives.
Adds "duration" var to chatNewMessage hook context to allow plugins to change it. Adjusts docs appropriately.
> Allow setting length of time gritter notification appears... - Ready to Review / Merge @muxator

- src/node/db/SecurityManager.js
A simple fix to make different cookie versions work
> Fix #3819 Strip cookie value from optional quotes

- README.md
📝 Add Travis-CI badge to README
Signed-off-by: mathieu.brunot <mathieu.brunot@monogramm.io>
> README.md: Add Travis-CI badge

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
github: Templates for Issues and PR
Mentioned in #3854 with @muxator.
Signed-off-by: mathieu.brunot <mathieu.brunot@monogramm.io>
> github: Templates for Issues and PR

- tests/backend/specs/api/instance.js
simple PR against develop to get backend tests in working condition. This PR finishes the work in 44186ed.
> test: fix settings loading in api/instance backend test

- tests/frontend/specs/scroll.js
To hopefully fix Firefox tests...
> Comment out last line due to browser restriction of test

- tests/frontend/specs/scroll.js
Reverts ether/etherpad-lite#3888
> Revert "Comment out last line due to browser restriction of test"

- src/static/js/ace2_inner.js
I haven't tested much, this is just a patch fix to show a solution to the problem.  If someone wants to investigate further IE on the server then this would be a good reference.  This can probably be merged as it wont cause any damage / harm, or at least, shouldn't...
Solves: https://github.com/ether/etherpad-lite/issues/3861
> Hack fix for 3861

- src/locales/en.json
- src/node/handler/PadMessageHandler.js
- src/static/css/pad.css
- src/static/js/collab_client.js
- src/static/js/pad_editbar.js
- src/static/js/pad_impexp.js
- src/templates/pad.html
Details are on the github issue.
**Edit**: this is a follow up to #3864.
> Notify the user on failed import for permission denied (and max file size, already integrated in develop)

- .gitignore
PhpStorm IDE configuration files are excluded.
> .gitignore add a new rule

- CHANGELOG.md
- src/package.json
> release: prepare for 1.8.3

- src/static/css/admin.css
- src/static/css/iframe_editor.css
- src/static/css/pad/chat.css
- src/static/css/pad/form.css
- src/static/css/pad/gritter.css
- src/static/css/pad/layout.css
- src/static/css/pad/popup.css
- src/static/css/pad/popup_users.css
- src/static/css/pad/toolbar.css
- src/static/css/timeslider.css
- src/static/js/ace2_inner.js
- src/static/js/pad.js
- src/static/js/pad_editbar.js
- src/static/js/pad_editor.js
- src/static/skins/colibris/index.css
- src/static/skins/colibris/pad.css
- src/static/skins/colibris/src/components/chat.css
- src/static/skins/colibris/src/components/gritter.css
- src/static/skins/colibris/src/components/popup.css
- src/static/skins/colibris/src/components/sidediv.css
- src/static/skins/colibris/src/components/toolbar.css
- src/static/skins/colibris/src/layout.css
- src/static/skins/colibris/src/pad-editor.css
- src/static/skins/colibris/src/pad-variants.css
- src/static/skins/colibris/src/plugins/set_title_on_pad.css
- src/static/skins/colibris/timeslider.css
- src/templates/index.html
>  Some ui fix after 1.8.3 closes #3954

- doc/api/hooks_server-side.md
just a typo, maybe the smallest commit in this repo :p
> typo on index.html hooks

- src/static/css/iframe_editor.css
- src/static/css/pad/form.css
- src/static/css/pad/gritter.css
- src/static/js/pad_utils.js
- src/static/skins/colibris/src/components/gritter.css
- src/static/skins/colibris/src/components/scrollbars.css
- src/static/skins/colibris/src/layout.css
- src/static/skins/colibris/src/pad-editor.css
One of them, re wrapping, is critical because some functionalities have been broken because of this
> Various fix for 1.8.4

- src/node/db/SessionStore.js
This reverts commit 53f126082a8b3d094e48b159f0f0bc8a5db4b2f4, which
broke user authentication.
Fixes issue #4016.
Reopens issue #3421.
> Revert "SessionStore: replace password with PASSWORD_HIDDEN when storing in db"

- src/node/hooks/i18n.js
> Remove superfluous semicolon

- src/node/db/SessionStore.js
> Cherry pick auth fix to master

- src/static/js/pad_userlist.js
- tests/frontend/specs/embed_value.js
Fix the test for embed values, afaik @seballot changed values but didn't update test.
> Embed test fix

- tests/frontend/specs/helper.js
name uses a placeholder instead of a value so this should be nothing
> Tests: Fix Clear cookies test

- tests/frontend/specs/font_type.js
- tests/frontend/specs/pad_modal.js
1. Fixes modal check with a commented section.
1. Fixes select check with a proper fix.
> Safari test fixes

- src/static/js/contentcollector.js
Fixes https://github.com/JohnMcLear/ep_copy_paste_images/issues/20
> proposed fix for cc 2412

- src/node/handler/ImportHandler.js
Bugfix for error handling of file sizes.
> URGENT: Error handling import - as per Foundation Email

- src/node/hooks/express/webaccess.js
> webaccess: Log authentication attempts

- src/static/js/pad_editbar.js
This solution fixes the problem #3883
> setEmbedLinks: fix the wrong URL when we use etherpad without /p/ in the URL

- doc/api/hooks_server-side.md
see https://github.com/ether/etherpad-lite/pull/3996#issuecomment-637527714
> add doc for new index hooks / ref #3978

- src/static/js/ace2_inner.js
- tests/frontend/specs/unordered_list.js
- tests/frontend/travis/remote_runner.js
The problem with the first attempt was that I used ``let``
FML .
> editor: outdent on ol removal

- src/static/robots.txt
I don't see any occurence in the code for /newpad so I deleted the entry
> Remove unnecessary robots.txt entry

- src/static/js/broadcast.js
- src/static/js/collab_client.js
- src/static/js/pad.js
- src/static/js/timeslider.js
- tests/frontend/specs/caret.js
- tests/frontend/specs/clear_authorship_colors.js
- tests/frontend/specs/ordered_list.js
- tests/frontend/specs/redo.js
- tests/frontend/specs/responsiveness.js
- tests/frontend/specs/unordered_list.js
I think these are unnecessary. When debug logging happened in a catch-clause I kept them, because I find them helpful.
> Remove unecessary consolelogs

- bin/convert.js
Colorpallet has 64 colors, not 32, see line 26 in [src/node/db/AuthorManager.js](https://github.com/ether/etherpad-lite/blob/4c45ac3cb1aefcfdeb8871641de01f5d937fb686/src/node/db/AuthorManager.js) 
By expanding to full range, get better contrasts when there are more than 15 users. It may be helpful to examine color choices a little more and find a better algorithm for automatically assigning colors to users.
> Fix for better user color selection.

- src/node/hooks/express/specialpages.js
> Fix typo in comment

- src/node/utils/LibreOffice.js
> Fix PDF import with libreoffice

- src/static/js/collab_client.js
This pull request shall fix #4132 
Unfortunately I`m not sure how I would write a test covering that.
> fix for jQuery.Deferred exception

- src/static/js/timeslider.js
> bugfix: only update timeslider on correct message type

- README.md
https://github.com/ether/etherpad-lite/pull/4210
> Add link to Etherpad plugin list in README.md

- src/node/utils/LibreOffice.js
- tests/backend/specs/api/importexportGetPost.js
.doc import was broken.
also includes uncommenting of test coverage
> bugfix/import: doc import bugfix

- doc/api/hooks_server-side.md
- src/node/handler/PadMessageHandler.js
Also revise the clientVars hook documentation.
> PadMessageHandler: Pass socket.io Socket object to clientVars hook

- src/static/css/pad/popup_users.css
This makes it easier for an eejsBlock_userlist plugin to add something to that row.
> User list: Use flexbox for #myuser div

- src/node/db/GroupManager.js
fix for https://github.com/ether/etherpad-lite/issues/4227
WIP because test coverage missing for deleteGroup with at least one active session in it
> WIP: GroupManager: typo during session deletion

- src/node/db/SecurityManager.js
This reduces the chances of a typo-induced bug.
> SecurityManager: Use constants for returned rejections

- src/node/hooks/express/socketio.js
socket.io expects Error objects, otherwise it won't propagate the message to the client.
Also do some cleanup.
> socketio: Use Error objects for socket.io connection errors

- src/node/db/SecurityManager.js
- src/node/handler/PadMessageHandler.js
- src/node/handler/SocketIORouter.js
- src/node/hooks/express/importexport.js
- src/node/padaccess.js
In addition to providing defense in depth, this change makes it easier to implement future enhancements such as support for read-only users.
> security: Check authentication in SecurityManager checkAccess

- src/node/handler/PadMessageHandler.js
> PadMessageHandler: Move code out of unnecessary closure

- src/node/hooks/express/socketio.js
- src/package-lock.json
- src/package.json
- tests/backend/specs/socketio.js
#4288 must be merged first.
Also: `mocha` hangs after the tests finish, which I think indicates that something somewhere in the depths of Etherpad is holding onto an open connection. I would appreciate help troubleshooting and fixing that.
> tests: Add authentication, authorization bypass tests

- src/node/db/SessionManager.js
This bug was introduced in 8b0baa96797718985b0557d25d4696c19220c309.
Fixes #4323
> SessionManager: Fix session expiration check

- CHANGELOG.md
> changelog: Mention fix for authz bypass vulnerability in 1.8.6

- .travis.yml
As per https://github.com/ether/ep_hash_auth/issues/9
> tests: include ep_hash_auth in tests

- src/locales/en.json
- src/static/js/pad_connectionstatus.js
- src/templates/pad.html
This reason will be used in a future commit that will reject erroneous messages.
> Add a new 'rejected' disconnect reason

- bin/rebuildPad.js
- src/node/db/API.js
- src/node/db/AuthorManager.js
- src/node/db/Pad.js
- src/node/db/PadManager.js
- src/node/handler/ImportHandler.js
- src/node/handler/PadMessageHandler.js
- src/node/utils/ImportHtml.js
Where feasible I put the `await` at the end of the function to minimize the impact on latency.
My motivation for this change: Eliminate a race condition in tests I am writing.
> async-ify more functions, and await completion

- tests/frontend/specs/responsiveness.js
> tests: Allow longer timeout for responsiveness test

- bin/plugins/checkPlugin.js
Plugins don't always need translations.
> plugins: no need to ask for translations if no template files are included

- src/node/handler/PadMessageHandler.js
Before, the author ID was only saved in the session info during the initial `CLIENT_READY`, not when the client sent a `CLIENT_READY` due to a reconnect. This caused the handling of subsequent messages to use an undefined author ID.
> PadMessageHandler: Always save the author ID in the session info

- src/node/db/SecurityManager.js
Hopefully this will fix #4347.
> Fix typo in session check (sesion -> session)

- src/package-lock.json
> Bump Etherpad version in src/package-lock.json

- doc/api/hooks_server-side.md
- src/node/hooks/express/webaccess.js
- tests/backend/specs/webaccess.js
This makes it possible for plugins to return different pages to the user depending on whether the auth failure was authn or authz.
> webaccess: Split authFailure hook into authnFailure and authzFailure

- src/node/hooks/express/webaccess.js
This loses some of the granularity of the default HTTP basic auth (unknown username vs. bad password), but there is considerable value in having logging that is consistent no matter what authentication plugins are installed.
> webaccess: Log all authentication successes/failures

- tests/frontend/specs/timeslider_revisions.js
This test sometimes errored and hopefully this will make it be more consistent to pass.
> tests: allowing longer to do timeslider rev test

- src/package-lock.json
- src/package.json
I updated some dependencies as an update was due.
npm audit resolved some potential security issues.
> package updates: update deps and resolve some potential security issues

- .travis.yml
- src/node/handler/PadMessageHandler.js
- src/package-lock.json
- src/package.json
- tests/ratelimit/Dockerfile.anotherip
- tests/ratelimit/Dockerfile.nginx
- tests/ratelimit/nginx.conf
- tests/ratelimit/send_changesets.js
- tests/ratelimit/testlimits.sh
> security: Support proxy with rate limiting and include CI test coverage for nginx rev proxy

- CHANGELOG.md
> Update `CHANGELOG.md` with the changes so far

- doc/api/hooks_server-side.md
- src/static/js/linestylefilter.js
**Please do not squash merge** because these commits are intentionally separate:
* Call the aceAttribClasses hook synchronously
* Make the aceAttribClasses hook harder to misuse
> aceAttribClasses hook improvements

- src/node/handler/PadMessageHandler.js
- src/node/handler/SocketIORouter.js
- src/node/hooks/express/socketio.js
- src/node/utils/RemoteAddress.js
- src/package.json
This also makes it easier for plugins to get the client IP address.
> socketio: Mimic what Express does to get client IP address

- src/node/utils/ExportHtml.js
- src/node/utils/padDiff.js
> HTML export: Wait for async hook completion before processing results

- src/node/handler/APIHandler.js
- tests/backend/common.js
- tests/backend/fuzzImportTest.js
- tests/backend/specs/api/api.js
- tests/backend/specs/api/characterEncoding.js
- tests/backend/specs/api/chat.js
- tests/backend/specs/api/fuzzImportTest.js
- tests/backend/specs/api/importexport.js
- tests/backend/specs/api/importexportGetPost.js
- tests/backend/specs/api/instance.js
- tests/backend/specs/api/pad.js
- tests/backend/specs/api/sessionsAndGroups.js
> tests: Simplify API key reading

- doc/api/hooks_server-side.md
- src/static/js/pluginfw/shared.js
- src/templates/index.html
> CSP: Disable the indexCustomInlineScripts hook

- src/static/js/index.js
- src/templates/index.html
> CSP: Move `index.html` inline code to separate `.js` file

- tests/backend/specs/api/api.js
- tests/backend/specs/api/characterEncoding.js
- tests/backend/specs/api/chat.js
- tests/backend/specs/api/importexport.js
- tests/backend/specs/api/importexportGetPost.js
- tests/backend/specs/api/instance.js
- tests/backend/specs/api/pad.js
- tests/backend/specs/api/sessionsAndGroups.js
- tests/backend/specs/api/tidy.js
- tests/backend/specs/contentcollector.js
- tests/backend/specs/promises.js
- tests/backend/specs/socketio.js
- tests/backend/specs/webaccess.js
Also some minor consistency cleanups.
> tests: Include the filename in the test output

- tests/frontend/specs/helper.js
This should have been done in c222fc5d0b8e1058ebfae93fb95aae9f56b6eeea but I forgot.
> tests: Tune `waitForPromise()` poll count test

- src/static/js/broadcast.js
There is a small edge case regarding the follow pad contents functionality:
Currently the changeset that is applied to get the next revision is parsed and the lines property of the first opcode is used to find the line where the change happens.
Given:
pad content rev 0: [default Pad text]
pad content rev 1: [''] (delete everything)
pad content rev 2: ['Test line','',''] (insert "Test line\n\n"
pad content rev 3: ['Test line','','Another test line'] (insert "Another test line" at line 3)
When you go from revision 2 to 1 (changeset: `Z:c<b|2-b$`) the lines property is 2.
When you go from revision 0 to 1 (changeset: `Z:bk<bj|7-bj$`) the lines property is 7.
I think it would be better if we'd scroll to line 1 in both cases. Probably it's only relevant for the "delete everything" edge case, …
> better follow contents

- README.md
> docs: Discord channel link in README

- src/static/css/pad/form.css
- src/static/css/pad/toolbar.css
- src/static/skins/colibris/src/components/form.css
> Display outline when toolbar button focused refs #4422

- src/node/hooks/express/webaccess.js
> webaccess: Remove user's password from session info

- .travis.yml
Lint the ``package-lock.json`` to check for shady inputs
https://snyk.io/blog/why-npm-lockfiles-can-be-a-security-blindspot-for-injecting-malicious-modules/
See: https://github.com/lirantal/lockfile-lint for details
> security: lockfile lint check

- .travis.yml
* .travis.yml: Wrap long plugin install lines
* .travis.yml: Sort plugins
* .travis.yml: Don't install ep_comments_page
* .travis.yml: Factor out common plugin install command
> tests: .travis.yml cleanups

- tests/backend/specs/webaccess.js
Also factor out common test setup code.
> tests: Clear hooks before running webaccess tests

- src/static/js/pad_utils.js
remove unnecessary conditional statement
if animationState evaluates to -1 or 0, it would end up in a conditional statement that assign animationState's value to itself. Since this is redundant, it is better to remove this conditional, to avoid an extra check
> remove unnecessary conditional statement

- doc/api/hooks_server-side.md
- src/node/utils/ExportHtml.js
Part of https://github.com/ether/ep_comments/pull/151
> pluginfw: Hook to include additional body in HTML exports

- doc/api/hooks_server-side.md
- src/node/utils/ExportEtherpad.js
- src/node/utils/ImportEtherpad.js
Also:
* Improve parallelization
* Refine the documentation
> import/export: Simplify exportEtherpadAdditionalContent processing

- .travis.yml
- tests/frontend/travis/runner.sh
- tests/frontend/travis/runnerBackend.sh
- tests/frontend/travis/runnerLoadTest.sh
- tests/frontend/travis/sauce_tunnel.sh
* tests: Factor out LibreOffice installation
* tests: Fix setting loglevel to WARN
* tests: Set loglevel to WARN instead of suppressing stdout
* tests: Kill Etherpad and wait for it to exit
* tests: Clean up Travis runner scripts
> tests: Various minor Travis fixes

- bin/plugins/checkPlugin.js
Support for @rhansen eslint into checkPlugins.
Allows for autofix, very early dev
> plugins: include eslint in checkPlugins.js

- bin/plugins/checkPlugin.js
- bin/plugins/getCorePlugins.sh
- bin/plugins/lib/README.md
- bin/plugins/lib/npmpublish.yml
Doesn't include support for adaptive package.json, not sure that's required..
> checkPlugins: Support adaptive npmpublish.yml

- bin/plugins/lib/npmpublish.yml
* Add commentary explaining why things are done the way they are.
* Delete steps that were added for debugging.
* Pass `--no-save` when installing `ep_etherpad-lite`.
> checkPlugins: Revise `npmpublish.yml`

- src/node/utils/Minify.js
This fixes a bug introduced in commit 8e5fd19db2dbbfacf61b2cc223614a0517d4a15b.
> Minify: Accept single quotes in `ace.js`'s `$$INCLUDE_*(...)` lines

- tests/frontend/runner.js
* test runner: Pass single argument to `append()`
* lint: Fix most ESLint errors in `runner.js`
* test runner: Simplify `getURLParameter()`
> tests: Various minor `runner.js` cleanups

- bin/plugins/checkPlugin.js
- package-lock.json
- package.json
- src/package-lock.json
- src/package.json
> lint: Bump eslint-config-etherpad to 1.0.13

- src/static/css/pad/popup_users.css
Make color button from elipsoid to circle
current see https://easycaptures.com/fs/uploaded/1536/3084360130.png
> Make color button from elipsoid to circle

- bin/plugins/checkPlugin.js
- bin/plugins/lib/CONTRIBUTING.md
- bin/plugins/lib/travis.yml
> checkPlugins: Check plugin mkdir fix

- src/package-lock.json
- src/package.json
May experience some performance gains.
> database: bump ueberdb to 056 to ensure correct engine is used

- src/node/utils/ImportHtml.js
> Fix whitespace

- bin/plugins/lib/travis.yml
> checkPlugin: dont run sauce labs connector on travis backend tests

- src/node/utils/ExportHtml.js
- src/static/js/ace2_inner.js
- src/static/js/linestylefilter.js
- src/static/js/pad_utils.js
- tests/frontend/helper/methods.js
- tests/frontend/specs/timeslider_follow.js
- tests/frontend/specs/urls_become_clickable.js
* lint: Fix some straightforward ESLint errors
* tests: New `helper.clearPad` method
* tests: Expand the tests in `urls_become_clickable.js`
* Factor out common URL regular expression code
* Exclude `?`, `!`, and `)` from last character of URL
* Add `'` and `*` to acceptable URL characters
> URL regex improvements

- package-lock.json
- src/package-lock.json
- src/package.json
* Update `package-lock.json` and `src/package-lock.json`
* Add missing dependency on mime-types
> Minor dependency fixes

- src/static/js/ace2_inner.js
- src/static/js/contentcollector.js
Fixes from @webz into my branch
> Refactor ace2 inner fixes

- bin/plugins/checkPlugin.js
- package-lock.json
- package.json
- src/node/eejs/index.js
- src/node/handler/APIHandler.js
- src/node/utils/ImportHtml.js
- src/node/utils/Minify.js
- src/node/utils/toolbar.js
- src/package-lock.json
- src/package.json
- src/static/js/ace.js
- src/static/js/contentcollector.js
- src/static/js/pad_editor.js
- src/static/js/pluginfw/hooks.js
- src/static/js/pluginfw/plugins.js
- src/static/js/pluginfw/shared.js
- src/static/js/scroll.js
* lint: Bump `eslint` and `eslint-config-etherpad` versions
* lint: Re-run `eslint --fix`
> lint: Bump eslint and eslint-config-etherpad versions, re-run `eslint --fix`

- src/static/js/pluginfw/tsort.js
Lint `/src/static/js/pluginfw/tsort.js`
> Lint: pluginfw tsort.js

- src/static/js/pad.js
- src/static/js/pad_automatic_reconnect.js
- src/static/js/pad_connectionstatus.js
- src/static/js/pad_cookie.js
- src/static/js/pad_editbar.js
- src/static/js/pad_editor.js
- src/static/js/pad_impexp.js
- src/static/js/pad_modals.js
- src/static/js/pad_savedrevs.js
- src/static/js/pad_userlist.js
- src/static/js/pad_utils.js
Lint of the rest of the "pad" files.
> lint: pad prefix files

- src/static/js/timeslider.js
> timeslider/bugfix: timeslider wasn't updating when on new contents

- src/static/js/timeslider.js
Lint `/src/static/js/timeslider.js`
> Lint: timeslider

- src/static/js/broadcast.js
- src/static/js/broadcast_revisions.js
- src/static/js/broadcast_slider.js
> lint: broadcast_revisions

- src/static/js/chat.js
If username isn't set I noticed it doesn't pass "" value as chat name but some weird value..  I think this is because underscore is now being required..
> lint: chat

- src/static/css/pad/loadingbox.css
fix issue with loading message alignment
> css: loading position box

- CHANGELOG.md
> changelog: updated changelog

- bin/release.js
> A script to create an Etherpad release

- src/static/js/scroll.js
single commit for resolving linting issues in scroll.js
various commits at https://github.com/ether/etherpad-lite/pull/4604
> lint: scroll.js

- src/node/hooks/express/tests.js
- tests/frontend/helper/ui.js
- tests/frontend/specs/change_user_name.js
This test sporadically failed in CI
Don't merge yet. locall it seemes to work in firefox/chrome, but not in CI. Need to debug tomorrow
> change_user_name test: refactor

- bin/plugins/checkPlugin.js
> checkPlugins: various minor updates

- src/static/js/ace2_inner.js
- src/static/js/contentcollector.js
- src/static/js/domline.js
- src/static/js/farbtastic.js
- src/static/js/pad_userlist.js
* Remove msie from client side code
* Linting of ace2_inner
* Use strict in most javascript files and bugfix issues discovered in ``use strict``
> Refactor ace2 inner

- src/node/db/DB.js
- src/package-lock.json
- src/package.json
* db: Capitalize `Database` constructor
* db: Update ueberdb2 dependency
> db: Update ueberdb2 dependency

- bin/checkAllPads.js
- bin/checkPad.js
- bin/checkPadDeltas.js
- bin/createUserSession.js
- bin/deleteAllGroupSessions.js
- bin/deletePad.js
- bin/extractPadData.js
- bin/importSqlFile.js
- bin/migrateDirtyDBtoRealDB.js
- bin/plugins/checkPlugin.js
- bin/rebuildPad.js
- bin/release.js
- bin/repairPad.js
Apologies this is one large commit, things went a bit pete tong.
> bugfix, lint and refactor all bin scripts

- src/static/js/ace2_inner.js
* ace2_inner: Delete dead code
* ace2_inner: Avoid unnecessary use of underscore.js
* ace2_inner: Fix some ESLint errors
* ace2_inner: Improve readability of object creation
* ace2_inner: Fix argument bug in `execCommand()`
> ace2_inner fixes and cleanups

- src/package-lock.json
- src/package.json
> bugfix: bump ueberdb to 1.2.5 to resolve #4645 which caused a users color not to be persistent

- .github/workflows/backend-tests.yml
- .github/workflows/frontend-tests.yml
- .github/workflows/load-test.yml
- package-lock.json
* Update top-level `package-lock.json`
* GitHub workflows: Break list of plugins across multiple lines
* GitHub workflows: Synchronize plugin lists
* GitHub workflows: Install Etherpad deps after installing plugins
> Fix dependency installation in GitHub workflows

- src/static/js/ace2_common.js
> lint: ace2_common.js linting

- bin/plugins/checkPlugin.js
- package-lock.json
- package.json
- src/node/handler/PadMessageHandler.js
- src/package-lock.json
- src/package.json
- src/static/js/pad_automatic_reconnect.js
- src/static/js/pluginfw/tsort.js
* Bump eslint-config-etherpad to 1.0.24
* lint: Re-run eslint --fix
> Bump eslint-config-etherpad to 1.0.24

- bin/doc/json.js
Please check I got Line 419 right :)
> lint: json.js

- CHANGELOG.md
- bin/checkPadDeltas.js
- bin/cleanRun.sh
- bin/debugRun.sh
- bin/fastRun.sh
- bin/installDeps.sh
- bin/repairPad.js
- bin/run.sh
- doc/api/http_api.md
- doc/localization.md
- settings.json.docker
- settings.json.template
- src/node/db/DB.js
- src/node/db/PadManager.js
- src/node/handler/PadMessageHandler.js
- src/node/hooks/express/openapi.js
- src/node/hooks/express/socketio.js
- src/node/utils/Minify.js
- src/static/js/pad.js
- tests/backend/fuzzImportTest.js
- tests/backend/specs/api/importexport.js
- tests/backend/specs/api/pad.js
- tests/backend/specs/contentcollector.js
- tests/frontend/runner.js
> docs: fixed typos

- bin/checkAllPads.js
- bin/checkPad.js
- bin/checkPadDeltas.js
- bin/extractPadData.js
- bin/importSqlFile.js
- bin/migrateDirtyDBtoRealDB.js
- bin/rebuildPad.js
- bin/repairPad.js
> npm-load-remove: checkPad.js example

- src/static/css/iframe_editor.css
- src/static/js/ace2_inner.js
- src/static/js/pad_editor.js
Shouldn't be a change in behavior.
> editor: remove grayed logic and css which caused 4715

- src/tests/frontend/specs/drag_and_drop.js
- src/tests/frontend/specs/ordered_list.js
- src/tests/frontend/specs/pad_modal.js
- src/tests/frontend/specs/scrollTo.js
- src/tests/frontend/specs/select_formatting_buttons.js
- src/tests/frontend/specs/unordered_list.js
This fixes issues introduced in commit f8a19c4527cd1f4dd38ee45cf5769d47652421e0 for PR #4718.
> lint: Fix bugs and style issues introduced in PR #4718

- src/bin/release.js
> fix: release script output

- src/static/js/ace.js
- src/static/js/ace2_inner.js
* ace: Simplify Ace2Editor method creation
* ace: Use `globalThis` instead of non-strict default context
* lint: src/static/js/ace.js
> lint: src/static/js/ace.js

- src/tests/frontend/specs/ordered_list.js
This fixes a bug introduced in commit e9bb2c410ec95207e4461d0862e3afdba6aa6113.
> tests: Fix accidental functions in `ordered_list.js`

- CHANGELOG.md
- src/static/js/pad.js
> pad: Don't throw on socket.io error

- src/node/hooks/express/socketio.js
- src/tests/frontend/specs/chat_load_messages.js
Temporary band aid for SocketIO security issue.
> security: limit socketio to 1M chars

- src/node/handler/PadMessageHandler.js
- src/node/server.js
- src/node/utils/Settings.js
- src/package.json
- src/static/js/ace2_inner.js
- src/tests/backend/specs/api/api.js
- src/tests/backend/specs/api/sessionsAndGroups.js
- src/tests/frontend/helper.js
- src/tests/frontend/helper/methods.js
- src/tests/frontend/helper/ui.js
* lint: Treat `helper.js` and friends as normal browser files
* lint: Re-run `eslint --fix`
* lint: `src/tests/frontend/helper.js` and friends
* lint: `src/tests/backend/specs/api/api.js`
> Minor lint fixes

- src/node/hooks/i18n.js
Resolve i18n / locales.json issue at https://github.com/ether/etherpad-lite/issues/4443
> performance: i18n maxage

- src/node/hooks/express.js
This should make restarts via `/admin` actions (e.g., plugin installation) more reliable.
> express: Forcibly terminate HTTP connections when restarting

- src/node/hooks/express/specialpages.js
- src/node/hooks/express/static.js
Resolve favicon/ plugin-definition issue at https://github.com/ether/etherpad-lite/issues/4443
> performance: maxAge for favicon and plugin definitions

- src/bin/installDeps.sh
might break some things as it requires npm 6.31.4
> deps: use ci --no-optional flags, this might break some things

- CHANGELOG.md
- src/node/hooks/express.js
- src/tests/frontend/specs/adminsettings.js
* express: New `httpUptime` metric
* tests: Improve `/admin/settings` restart test
> tests: Improve `/admin/settings` restart test

- src/bin/buildForWindows.sh
- src/bin/release.js
Each time I release I spot small improvements we can make, here I spotted two minor issues we can easily fix.
> Release improvements

- CHANGELOG.md
- src/node/handler/ImportHandler.js
- src/static/js/pad_impexp.js
* import: Improve error logging
* import: Convert arrow function to regular function
* docs: Start CHANGELOG for 1.8.9
Fixes #4808
> Fix import 400 error

- src/node/server.js
* server: Improve log messages when exiting
* server: Fix Gate constructor
> server: Fix Gate constructor and improve logging

- src/static/js/ace2_inner.js
- src/static/skins/colibris/src/components/sidediv.css
Hi !
I made small change to your PR @JohnMcLear :
- small UI improvement
- make it compatible with author_neat (keeping span and using inline-block property)
- squashing the three commits into one
Nice work btw ! it's not perfect with ep_headings because there is also some margin involved, but still it's a good improvement !
> editor: line numbers alignment

- src/templates/timeslider.html
timeslider.html needs a decent rewrite but these minor changes help improve code quality until we get around to it.
> timeslider: slight improvement on javascript

- src/node/db/PadManager.js
- src/node/eejs/index.js
- src/node/handler/PadMessageHandler.js
- src/node/handler/SocketIORouter.js
- src/node/hooks/express/openapi.js
- src/node/hooks/express/padurlsanitize.js
- src/node/hooks/i18n.js
- src/node/padaccess.js
- src/node/utils/AbsolutePaths.js
- src/node/utils/ExportHtml.js
- src/node/utils/ExportTxt.js
- src/node/utils/ImportEtherpad.js
- src/node/utils/NodeVersion.js
- src/node/utils/Settings.js
Very easy low hanging fruit, nothing fancy, just grunt work.
> Lint backend low hanging

- Dockerfile
Update node version in docker from version 10 to 14
> Update node in docker to version 14

- src/node/db/API.js
- src/node/db/Pad.js
- src/node/utils/ExportHtml.js
- src/static/js/AttributeManager.js
- src/static/js/Changeset.js
- src/static/js/ace2_inner.js
- src/static/js/caretPosition.js
- src/static/js/contentcollector.js
- src/static/js/pluginfw/tsort.js
Various low hanging issues LGTM raised.  Mostly pointless declarations and tests of always true/false values.
> Lgtm bugfixes

- .github/workflows/frontend-admin-tests.yml
- .github/workflows/frontend-tests.yml
- src/tests/frontend/specs/importexport.js
Fixes https://github.com/ether/etherpad-lite/issues/4818 as much as possible without OS level control.
> tests: fix importexport frontend tests

- src/bin/plugins/checkPlugin.js
- src/package-lock.json
- src/package.json
This relaxes `no-constant-condition` to permit `while (true)`.
> lint: Update ESLint dependencies

- src/package-lock.json
- src/package.json
Addresses but is not a complete fix for #4684.
> deps: Update ueberdb2 to work around dirty DB bug

- src/static/js/vendors/nice-select.js
I accidently committed a breaking change in https://github.com/ether/etherpad-lite/commits/1b8cd0747dc76b7a46f7e00201b2b73b1591e456/src/static/js/vendors/nice-select.js
> nice-select restore to working

- src/node/hooks/express/padurlsanitize.js
- src/tests/backend/specs/pads-with-spaces.js
fix for https://github.com/ether/etherpad-lite/issues/4883
> fix pads with spaces

- CHANGELOG.md
- src/package-lock.json
- src/package.json
> deps: Update ueberdb2 to fix dirty DB bug

- src/node/utils/Minify.js
> Minify: Compatibility for all `vendors/*.js` files

- src/bin/plugins/stalePlugins.js
Outputs a list of pluginnames and email address for maintainers to contact.  Useful for me to bump folks to maintain there stuff and stop it getting stale :)
> plugins/tools: stalePlugins.js

- src/static/js/ace.js
This reverts commit a17f9bf3cfc745a44d0e57b77912e346ffd3ce1c, which caused a mysterious bug with the line numbers. Revert to avoid blocking a new release while I figure out the bug.
Fixes #4914.
> Revert "ace: Build the outer and inner iframes programmatically"

- src/static/css/iframe_editor.css
> CSS: Increase size of contenteditable area

- src/node/db/DB.js
- src/package-lock.json
- src/package.json
* deps: Update ueberdb2 to get metrics
* stats: Expose ueberdb2 metrics
The newer version of ueberdb2 comes with callback changes that could affect performance, so we should keep an eye out for performance issues.
cc @packardone
> stats: Expose ueberdb2 metrics

- src/node/server.js
This might help users troubleshoot rare crashes.
cc @packardone
> server: Log stats (metrics) on fatal error

- src/static/css/pad/layout.css
- src/templates/timeslider.html
instead of https://github.com/ether/etherpad-lite/pull/4939
let's see what frontend test output is
Fixes #4937
> add class pad to timeslider to fix height issue

- src/package-lock.json
- src/package.json
> deps: Bump ueberdb2 to get MySQL improvements

- src/tests/frontend/helper.js
* tests: Fix `helper.newPad()` retries
* tests: Make the `helper.newPad()` callback optional
* tests: New `helper.aNewPad()` (promisified `newPad()`)
> tests: New `helper.aNewPad()` (promisified `newPad()`)

- src/static/js/pad_cookie.js
- src/tests/frontend/helper.js
- src/tests/frontend/helper/multipleUsers.js
- src/tests/frontend/index.html
- src/tests/frontend/specs/authorship_of_editions.js
- src/tests/frontend/specs/helper.js
- src/tests/frontend/specs/language.js
- src/tests/frontend/specs/multiple_authors_clear_authorship_colors.js
* tests: Refine `helper/multipleUsers.js`
* tests: Promisify `authorship_of_editions.js`
* tests: Promisify `multiple_authors_clear_authorship_colors.js`
* tests: Promisify some of the `helper.js` tests
* tests: Fix encoding of prefs cookie
* tests: Always set cookie path to / (to match non-test behavior)
* tests: Fix cookie name in `helper.js` tests
* pad_cookie: Move initial cookie read+save to `init()`
* pad_cookie: Re-read prefs cookie on every call to `getPref()`
* tests: Use cookie libraries to manipulate cookies
* tests: Wait for commit rather than sleep
> tests: Fix cookies

- src/node/handler/PadMessageHandler.js
- src/node/utils/ImportEtherpad.js
- src/static/js/contentcollector.js
* import: Use a Set for supported elements
* import: Reduce log spam from unsupported elements
* PadMessageHandler: Improve logging of pre-CLIENT_READY drops
> Improve logged errors and warnings

- src/node/db/AuthorManager.js
- src/tests/backend/specs/regression-db.js
Should partially fix https://github.com/ether/etherpad-lite/issues/5000
createGroupIfNotExistsFor/createGroup seems to be using the correct code already, so I'm not sure yet what happened
> await in AuthorManager.js

- .github/workflows/upgrade-from-latest-release.yml
* tests: Rename workflow to "Upgrade from latest release"
* tests: Fix missing commit in "Upgrade from latest release" workflow
> tests: Fix bad ref in "Upgrade from latest release" workflow

- src/tests/frontend/runner.css
- src/tests/frontend/runner.js
* tests: Keep the `#mocha-stats` div visible
* tests: Don't auto-scroll Mocha results if user scrolls up
* tests: Display frontend spec loading progress
> tests: More frontend test UI improvements

- src/tests/frontend/travis/remote_runner.js
> tests: Enable fake webcam on Microsoft Edge

- src/static/css/pad/icons.css
- src/static/skins/colibris/src/components/buttons.css
> CSS: Fix button icon centering

- src/bin/importSqlFile.js
This avoids running out of memory if the file is large.
@almereyda Would you test this to see if it fixes your issue?
Fixes #5085
> bin/importSqlFile.js: Read the file line at a time

- src/tests/frontend/helper.js
- src/tests/frontend/helper/multipleUsers.js
* tests: Remove unnecessary `includeJquery` parameter
* tests: Add a comment explaining why `Promise.all()` is not used
* tests: Factor out duplicate `getFrameJQuery()`
* tests: Improve readability of `multipleUsers.js`
> tests: Various minor cleanups

- settings.json.docker
- src/package-lock.json
- src/package.json
* deps: Bump ueberdb2 to 1.4.13
* Docker: Add `dbSettings.collection` and `.url` settings
Fixes #5118
@Loki-Afro Would you please test this?
> Docker: Add variables for mongodb to settings.json.docker

- src/static/js/basic_error_handler.js
- src/static/js/pad_utils.js
- src/static/js/timeslider.js
- src/templates/pad.html
- src/templates/timeslider.html
* Pad: Add missing `<head>` and `<body>` tags
* Pad: Improve page load error handler
* Timeslider: Move `<title>` and `<script>` inside `<head>`
* Timeslider: Install an error handler
> Pad and Timeslider: Improve error handling

- src/tests/backend/specs/api/chat.js
- src/tests/backend/specs/api/importexportGetPost.js
- src/tests/backend/specs/api/pad.js
- src/tests/backend/specs/socketio.js
See https://github.com/ether/etherpad-lite/issues/4988 for rationale.
> tests: Delete overly aggressive timeouts

- src/package-lock.json
- src/package.json
- src/tests/frontend/travis/remote_runner.js
* tests: Update selenium-webdriver to 4.0.0-rc-1
* tests: Avoid deprecated `Builder.withCapabilities()` method
> tests: Update selenium-webdriver

- CHANGELOG.md
- settings.json.docker
- settings.json.template
- src/node/utils/Settings.js
- src/package.json
This will make it possible to upgrade log4js in a future version.
> log4js: Deprecate the `logconfig` setting

- src/node/utils/LibreOffice.js
* LibreOffice: Close stdin right away
* LibreOffice: Improve logging
> LibreOffice: Close stdin, improve logging

- src/static/js/AttributeManager.js
- src/static/js/ace2_inner.js
- src/tests/frontend/specs/clear_authorship_colors.js
> Don't throw error and allow attributes to be cleared on first line if line has line attribute

- src/tests/backend/specs/api/characterEncoding.js
- src/tests/backend/specs/api/instance.js
- src/tests/backend/specs/api/pad.js
- src/tests/backend/specs/api/sessionsAndGroups.js
* tests: Remove overly aggressive timeouts
* tests: Promisify some backend tests
* tests: Slight backend test reorganization, use `assert`
> Backend test improvements

- CHANGELOG.md
- doc/api/hooks_server-side.md
- src/node/handler/ImportHandler.js
- src/node/handler/PadMessageHandler.js
- src/static/js/pad.js
- src/static/js/pad_impexp.js
> Pad init improvements

- CHANGELOG.md
- doc/api/hooks_server-side.md
- src/node/handler/PadMessageHandler.js
- src/node/handler/SocketIORouter.js
- src/static/js/pad.js
- src/static/js/timeslider.js
- src/tests/backend/specs/socketio.js
Multiple commits, do not squash.
> Various PadMessageHandler improvements

- doc/api/hooks_server-side.md
- src/node/handler/ImportHandler.js
> ImportHandler: Pass the pad ID to the `import` hook, and other improvements

- src/node/handler/PadMessageHandler.js
- src/static/js/collab_client.js
- src/static/js/pad.js
> pad: Pass color and display name in `CLIENT_READY`

- src/static/js/Changeset.js
> Changeset: More JSDoc comment improvements

- src/static/js/Changeset.js
@webzwo0i This is a cherry-pick of your commit from #5253 (ef391f4e90c6edebf0710b0b41f29f2eecde9575) with some additional fixes.
> Changeset: Use string templates

- src/node/hooks/express/adminsettings.js
- src/node/utils/Settings.js
- src/static/js/admin/settings.js
> adminsettings: Pay attention to `--settings`

- src/tests/backend/specs/contentcollector.js
- src/tests/backend/specs/regression-db.js
- src/tests/backend/specs/specialpages.js
> tests: Remove overly aggressive timeouts

- src/node/utils/MinifyWorker.js
> MinifyWorker: Fix buggy error handling in `compressCSS`

- src/bin/doc/package-lock.json
Looks like this was accidentally deleted in commit 4a65acf417848a1f75d06e6019da9b26a19deeab.
> docs: Check in `src/bin/doc/package-lock.json`

- src/node/utils/ImportHtml.js
This PR is some yak shaving required to move import processing to a worker thread. (cc @packardone)
> ImportHtml: Wait for HTML processing to complete (and other cleanups)

- CHANGELOG.md
- src/node/db/Pad.js
- src/static/js/Changeset.js
- src/static/js/ace2_inner.js
- src/tests/frontend/specs/easysync.js
This is the next commit from PR #5233.
> Changeset: Replace `appendATextToAssembler()` with a generator

- CHANGELOG.md
- src/node/db/Pad.js
- src/static/js/AttributePool.js
- src/tests/backend/specs/api/pad.js
> Pad: Fix `copyPadWithoutHistory` apool corruption bug

- src/node/db/Pad.js
- src/static/js/Changeset.js
- src/tests/frontend/specs/easysync-other.js
> Changeset: Fix off-by-one bug in `makeSplice`

- src/tests/backend/common.js
- src/tests/backend/specs/messages.js
This will make it possible for other tests to reuse the code.
> tests: Factor out USER_CHANGES/ACCEPT_COMMIT helpers

- CHANGELOG.md
- doc/api/hooks_server-side.md
- src/ep.json
- src/node/hooks/express.js
- src/node/hooks/express/apicalls.js
- src/node/hooks/express/openapi.js
- src/node/hooks/express/specialpages.js
- src/node/hooks/express/static.js
- src/node/hooks/express/tests.js
- src/node/hooks/express/webaccess.js
- src/node/hooks/i18n.js
- src/tests/backend/specs/api/importexportGetPost.js
- src/tests/backend/specs/webaccess.js
> express: Avoid creating express-session state for static content, special pages

- src/node/db/Pad.js
- add a new function Pad.spliceText() which allows to append a splice to the
Pad's database.
- refactor Pad.setText() to use the new Pad.spliceText() function
- refactor Pad.appendText() to use the new Pad.spliceText() function
> add Pad.spliceText()

- CHANGELOG.md
- Dockerfile
- src/bin/etherpad-healthcheck
- src/node/hooks/express/specialpages.js
- src/package-lock.json
- src/package.json
- src/tests/backend/specs/health.js
> New `/health` endpoint for Docker health checks

- src/tests/frontend/specs/easysync-assembler.js
> easysync tests: Silence deprecation warnings

- src/node/db/PadManager.js
- src/node/hooks/express/openapi.js
- src/node/server.js
- src/node/utils/promises.js
This might help with #5343.
cc @0x46616c6b
> PadManager: Refactor `padList` to avoid duplicate loads

- CHANGELOG.md
- settings.json.template
- src/node/db/SessionStore.js
- src/node/handler/PadMessageHandler.js
- src/node/hooks/express.js
- src/node/hooks/express/socketio.js
- src/node/hooks/express/specialpages.js
- src/node/utils/Settings.js
- src/package-lock.json
- src/package.json
- src/static/js/pad.js
- src/static/js/timeslider.js
- src/tests/backend/specs/SessionStore.js
Addresses #5010 but does not completely fix it.
> express-session: Set finite lifetime, delete session record when it expires

- src/static/js/admin/settings.js
Added formal panics for invalid JSON.
> Edit settings.js

- CHANGELOG.md
- doc/api/hooks_server-side.md
- doc/api/http_api.md
- src/node/db/API.js
- src/node/db/GroupManager.js
- src/node/db/Pad.js
- src/node/db/PadManager.js
- src/node/handler/APIHandler.js
- src/node/handler/ImportHandler.js
- src/node/handler/PadMessageHandler.js
- src/node/hooks/express/importexport.js
- src/node/utils/ImportEtherpad.js
- src/node/utils/ImportHtml.js
- src/tests/backend/specs/api/restoreRevision.js
> Plumb author ID, add new `padDefaultContent` hook

- src/node/db/Pad.js
- src/node/handler/ImportHandler.js
- src/node/handler/PadMessageHandler.js
- src/tests/backend/specs/Pad.js
> Pad: `padDefaultContent` hook improvements

- CHANGELOG.md
- doc/api/hooks_server-side.md
- src/node/db/AuthorManager.js
- src/node/db/SecurityManager.js
- src/package-lock.json
- src/package.json
- src/static/js/pad.js
- src/static/js/pad_utils.js
- src/tests/backend/common.js
- src/tests/backend/specs/messages.js
Addresses https://github.com/ether/ep_openid_connect/issues/7
> AuthorManager: New `getAuthorId` hook

- src/tests/frontend/travis/remote_runner.js
> tests: use chrome for admin tests instead of safari

- src/package-lock.json
- src/package.json
> deps: jsdom 20 - waiting testing

- src/package-lock.json
- src/package.json
> deps: mocha 10 - waiting testing

- .github/workflows/backend-tests.yml
- .github/workflows/frontend-admin-tests.yml
- .github/workflows/frontend-tests.yml
- .github/workflows/lint-package-lock.yml
- .github/workflows/load-test.yml
- .github/workflows/rate-limit.yml
- .github/workflows/upgrade-from-latest-release.yml
- .github/workflows/windows.yml
- README.md
- src/package.json
> Require Node 16 and target Node 20 for testing

- CHANGELOG.md
- src/node/db/API.js
- src/node/db/Pad.js
- src/node/handler/ExportHandler.js
- src/node/handler/PadMessageHandler.js
- src/node/utils/ExportHelper.js
- src/node/utils/checkValidRev.js
- src/tests/backend/specs/api/importexportGetPost.js
- src/tests/backend/specs/messages.js
> Fix rev parsing

- Dockerfile
Adds an optimized alpine image for better security
> Added optimized alpine image for better security and smaller image.

- src/package-lock.json
- src/package.json
> Update/socket.io to latest 2.x version

- settings.json.docker
- settings.json.template
- src/node/db/PadManager.js
- src/node/handler/PadMessageHandler.js
- src/node/utils/Settings.js
- src/package-lock.json
- src/tests/backend/specs/enforceLowerCasePadIds.js
- src/tests/backend/specs/lowerCasePadIds.js
- src/tests/frontend/helper.js
- src/tests/frontend/helper/methods.js
fixes #3844
Adds Option to:
```
lowerCasePadIds = true // default is false
```
> allow option to make pad names case-insensitive

- .github/workflows/frontend-admin-tests.yml
- .github/workflows/frontend-tests.yml
> Skip instead of fail on dependabot.

- src/static/js/admin/settings.js
- src/static/js/vendors/farbtastic.js
> Use parse instead of parseJSON.

- src/node/utils/UpdateCheck.js
This change will change the user-agent for the requests to get the last version information from "axios/1.5.0" to "Etherpad/1.9.3".
I also added a caching for one hour to reduce those calls.
> Improve update check

- src/templates/export_html.html
> Use XHTML syntax for valid Abiword export.

- .github/workflows/backend-tests.yml
- .github/workflows/frontend-admin-tests.yml
- .github/workflows/upgrade-from-latest-release.yml
- src/package.json
> Deprecated Node 16, added Node 21.

- README.md
> Update required node.js version in README

- src/static/js/pluginfw/installer.js
> Handle exception during loading of plugins

- src/node/utils/Settings.js
> fix: The log level is now respected again.

- .github/workflows/docker.yml
> Automatically update README on docker hub

- src/node/hooks/i18n.js
> Added error handling if an unknown language code is entered.

- src/node/handler/ImportHandler.js
> Fixed determining file extension.

- src/static/css/pad.css
> Fix: #5001 Don't wrap URLs

- src/bin/cleanRun.sh
- src/bin/deb-src/sysroot/etc/init/etherpad.conf
- src/bin/debugRun.sh
- src/bin/fastRun.sh
- src/bin/run.sh
> Fixed scripts in bin folder

- src/node/db/PadManager.ts
- src/node/handler/APIHandler.ts
- src/node/handler/ExportHandler.ts
- src/node/handler/ImportHandler.ts
- src/node/handler/PadMessageHandler.ts
- src/node/handler/SocketIORouter.ts
- src/node/hooks/express/webaccess.ts
- src/node/types/ChangeSet.ts
- src/node/types/PadType.ts
- src/node/types/SocketAcknowledge.ts
- src/node/types/SocketClientRequest.ts
- src/node/types/SocketModule.ts
- src/node/types/WebAccessTypes.ts
- src/node/utils/ImportEtherpad.ts
- src/node/utils/ImportHtml.ts
- src/package.json
- src/tsconfig.json
> Added backend in typescript.

- src/node/db/DB.ts
- src/node/handler/PadMessageHandler.ts
- src/node/hooks/express/socketio.ts
- src/package.json
- src/tests/frontend/specs/collab_client.js
> Fixed frontend tests.

- src/node/hooks/express.ts
- src/node/hooks/express/socketio.ts
- src/tests/frontend-new/admin-spec/adminsettings.spec.ts
- src/tests/frontend-new/admin-spec/adminupdateplugins.spec.ts
> Increased timeout.

- src/package.json
This commit updates the version of the socket.io dependency in the server from its previous version to version 4. This update may include performance improvements, bug fixes, and new features provided by the latest version of socket.io. The change is part of the ongoing effort to keep the project's dependencies up-to-date and secure.
> Updated server socket io version to 4.

- .github/workflows/upgrade-from-latest-release.yml
- src/static/js/pluginfw/LinkInstaller.ts
- src/static/js/pluginfw/installer.ts
> Fixed upgrade from latest release.

- .github/workflows/upgrade-from-latest-release.yml
> Install playwright.

- src/node/hooks/express/static.ts
- src/node/utils/caching_middleware.ts
> Fixed cache server not working due to wrong url

- .github/dependabot.yml
Fixed dependabot by now looking at the parent pnpm workspace. This should be able to update all versions now accordingly.
> Fixed dependabot lookup directory.

- .github/dependabot.yml
> Increased to 30

- .github/workflows/backend-tests.yml
- .github/workflows/docker.yml
- .github/workflows/frontend-admin-tests.yml
- .github/workflows/frontend-tests.yml
- .github/workflows/load-test.yml
- .github/workflows/perform-type-check.yml
- .github/workflows/rate-limit.yml
- .github/workflows/upgrade-from-latest-release.yml
- .github/workflows/windows.yml
> Ignore docs path.

- .github/dependabot.yml
This will bundle all dev-dependecy updates for npm into a single PR
> Bundle dev-dependency updates

- src/node/db/API.ts
- src/node/utils/padDiff.ts
- src/static/js/pluginfw/hooks.js
- src/tests/frontend-new/specs/embed_value.spec.ts
> chore: remove repetitive words

- pnpm-lock.yaml
- src/package.json
- src/static/js/pluginfw/LinkInstaller.ts
> chore: Bumped live plugin manager

- doc/docker.md
> Fixed docker-compose.

- .env.dev.default
- README.md
- doc/docker.md
- docker-compose.dev.yml
- docker-compose.yml
- This adds volumes for storing configuration 
- Fixed the plugin_packages permissions
Closes #6327
> Fixed docker compose

- src/node/handler/PadMessageHandler.ts
> Fixed totalUsers being undefined thus not being displayed.

- src/static/js/contentcollector.js
- src/static/js/pad.js
- src/static/js/pluginfw/hooks.js
> chore: fix some typos in comments

- .editorconfig
> Added editorconfig configuration

- .github/workflows/backend-tests.yml
- .github/workflows/build-and-deploy-docs.yml
- .github/workflows/docker.yml
- .github/workflows/frontend-admin-tests.yml
- .github/workflows/frontend-tests.yml
- .github/workflows/load-test.yml
- .github/workflows/perform-type-check.yml
- .github/workflows/rate-limit.yml
- .github/workflows/upgrade-from-latest-release.yml
- .github/workflows/windows.yml
- Dockerfile
- pnpm-lock.yaml
> Bumped pnpm

- admin/package.json
- pnpm-lock.yaml
- src/node/hooks/express/admin.ts
This fixes the subdirectory hosting of Etherpad. The proxy hasn't been respected thus loading files from wrong directories. In this case also the socket io connection did fail. This is fixed with this pr and the updated documentation
Closes #6369
> Fixed proxying Etherpad with nginx.

- pnpm-lock.yaml
- src/node/handler/APIHandler.ts
- src/node/utils/Settings.ts
- src/static/js/pluginfw/tsort.js
Also allows authorization via the authorization header
> Fixed api header authorization

- .github/workflows/upgrade-from-latest-release.yml
- CHANGELOG.md
- Dockerfile
- README.md
- bin/plugins/lib/backend-tests.yml
- package.json
- pnpm-lock.yaml
> Fixed documentation to be pnpm run plugins i for plugin installation

- admin/src/pages/PadPage.tsx
> Fixed pagination of pads

- .github/workflows/backend-tests.yml
- .github/workflows/upgrade-from-latest-release.yml
> Updated plugin dependencies.

- src/node/hooks/express/adminsettings.ts
improve adminsettings.ts
- added a try/catch block around the fsp.writeFile
- replaced all the console.log with logger
I came across this as part of my troubleshooting into issue #6407
> small improvements to adminsetting.ts code

- .github/workflows/upgrade-from-latest-release.yml
> Use old script for compatibility

- .github/workflows/rate-limit.yml
> Fixed docker network

- admin/src/pages/PadPage.tsx
> next-page-disabled-if-zero-page

- src/static/js/vendors/jquery.js
> Bumped JQuery to 3.7.1

- pnpm-lock.yaml
- src/node/utils/Minify.js
- src/node/utils/MinifyWorker.js
- src/package.json
> Removed lightningcss

- pnpm-lock.yaml
- src/node/db/DB.ts
- src/node/utils/ImportEtherpad.ts
- src/package.json
> Fixed ueberdb2 build.

- settings.json.template
- src/node/utils/Settings.ts
Fixes #5303
Adding a new setting option (`logLayoutType`) this way the end users can change the console output to not output colors
> Add logLayoutType

- src/node/utils/Settings.ts
lt seems that the check to transport protocol introduced in #6497 does not match its description.
> fix: correct the transport protocol check

- admin/src/index.css
- admin/src/pages/HomePage.tsx
- admin/src/pages/PadPage.tsx
- admin/src/pages/Plugin.ts
> Added sorting for plugins

- bin/migrateDB.ts
- bin/package.json
- doc/cli.md
- pnpm-lock.yaml
- src/node/utils/Settings.ts
- src/package.json
- var/.gitignore
> Added new database rustydb

- src/static/js/vendors/html10n.ts
> Readded text shortcut

- doc/.vitepress/config.mts
- settings.json.docker
- settings.json.template
- src/node/utils/Settings.ts
- src/node/utils/UpdateCheck.ts
- src/static/js/pluginfw/installer.ts
> Added support for alternative update servers.

- src/static/js/vendors/html10n.ts
> Fix misuse of `in` instead of `includes` method for checking array

- pnpm-lock.yaml
- pnpm-workspace.yaml
- src/static/js/pad_userlist.ts
Check index when accessing pad data
> fix(frontend): index out of bounds

- .github/workflows/backend-tests.yml
- .github/workflows/frontend-admin-tests.yml
- .github/workflows/upgrade-from-latest-release.yml
> fix: remove node 18 and add node23

- .github/workflows/backend-tests.yml
- .github/workflows/build-and-deploy-docs.yml
- .github/workflows/docker.yml
- .github/workflows/frontend-admin-tests.yml
- .github/workflows/frontend-tests.yml
- .github/workflows/load-test.yml
- .github/workflows/perform-type-check.yml
- .github/workflows/rate-limit.yml
- .github/workflows/upgrade-from-latest-release.yml
- .github/workflows/windows.yml
- admin/src/pages/ShoutPage.tsx
- admin/vite.config.ts
- bin/plugins/lib/backend-tests.yml
- bin/plugins/lib/frontend-tests.yml
- bin/plugins/lib/npmpublish.yml
- doc/package.json
- pnpm-lock.yaml
- settings.json.docker
- settings.json.template
- src/node/hooks/express.ts
- src/node/hooks/express/adminplugins.ts
- src/node/hooks/express/specialpages.ts
- src/node/types/ArgsExpressType.ts
- src/node/utils/Settings.ts
- src/tests/frontend-new/admin-spec/adminupdateplugins.spec.ts
- src/tests/frontend-new/specs/indentation.spec.ts
> feat: disable stats endpoint if enableMetrics is false

- pnpm-lock.yaml
- src/node/db/SessionStore.ts
- src/node/hooks/express.ts
- src/package.json
> chore: use express session upstream

- bin/fastRun.sh
Remove last command with exec pnpm run prod "$@"
> chore: fixed fastRun.sh script

- doc/plugins.md
> correcting plugin install doc

- admin/package.json
- admin/src/pages/PadPage.tsx
- admin/vite.config.ts
- pnpm-lock.yaml
> chore: added react compiler and fixed url to manage pads
